# GENERATED by scripts/build_package.py from plugins/fin-fixed-income/skills/duration-convexity-and-dv01/scripts/duration.py - do not edit here.
# Edit the skill script and rerun the generator; validate.py checks they match.
# Owning skill: duration-convexity-and-dv01 (fin_skills.load('duration-convexity-and-dv01') returns its SKILL.md).

"""Macaulay, modified, effective and spread duration; DV01, PV01, convexity -- and which one
a given library actually returned.

WHY this exists: "duration" names at least four different numbers and "DV01" at least two, and
substituting one for another produces a risk report that is wrong by a few percent, which is
too small to notice and too large to hedge with.

  * MACAULAY IS NOT MODIFIED. They differ by exactly (1 + y/m). On a 5% semiannual bond that
    is 2.50%; on a 12% semiannual bond it is 6.00%. Feed a Macaulay duration to a DV01
    calculation and every hedge ratio is overstated by y/m, in the same direction, always.

  * DURATION IS A FIRST DERIVATIVE. On a long bond and a large move it is not close. The
    convexity term is not a refinement, it is most of the answer once the move is over 100 bp.

  * DV01 USES THE DIRTY PRICE. Modified duration is defined against the full price, so a DV01
    built on the clean price is short by ModDur * accrued * 1e-4 -- small, systematic, and
    invisible because it moves with the coupon cycle.

  * A FLOATER HAS TWO DURATIONS. Its interest-rate duration is roughly the time to the next
    reset -- days, not years -- while its SPREAD duration runs to maturity. Booking an FRN as
    a fixed-rate bond of the same maturity invents rate risk that does not exist.

Everything is a closed form here, cross-checked against a numerical bump and, when QuantLib is
importable, against BondFunctions.duration / convexity / basisPointValue.

Usage:
    from duration import macaulay_duration, modified_duration, dv01, convexity, frn_durations
"""
from __future__ import annotations

from typing import Callable, Sequence

import numpy as np

DURATION_TYPES = ("macaulay", "modified")


# ------------------------------------------------------------------ fixed-rate bond
def bond_cashflows(coupon: float, n: int, freq: int = 2, face: float = 100.0) -> np.ndarray:
    """Cash flows at periods 1..n. Coupon is an ANNUAL rate."""
    if n < 1:
        raise ValueError("n must be at least 1")
    cf = np.full(n, face * coupon / freq, dtype=float)
    cf[-1] += face
    return cf


def bond_price(coupon: float, y: float, n: int, freq: int = 2, face: float = 100.0) -> float:
    cf = bond_cashflows(coupon, n, freq, face)
    k = np.arange(1, n + 1, dtype=float)
    return float(np.sum(cf / (1.0 + y / freq) ** k))


def modified_duration(coupon: float, y: float, n: int, freq: int = 2,
                      face: float = 100.0) -> float:
    """-(1/P) dP/dy, in years. The number DV01 and every hedge ratio wants."""
    cf = bond_cashflows(coupon, n, freq, face)
    k = np.arange(1, n + 1, dtype=float)
    v = 1.0 + y / freq
    p = float(np.sum(cf / v ** k))
    dpdy = float(np.sum(cf * (-k / freq) / v ** (k + 1)))
    return -dpdy / p


def macaulay_duration(coupon: float, y: float, n: int, freq: int = 2,
                      face: float = 100.0) -> float:
    """PV-weighted average time to the cash flows. Exactly (1 + y/m) x modified."""
    return modified_duration(coupon, y, n, freq, face) * (1.0 + y / freq)


def convexity(coupon: float, y: float, n: int, freq: int = 2, face: float = 100.0) -> float:
    """(1/P) d2P/dy2, in years squared."""
    cf = bond_cashflows(coupon, n, freq, face)
    k = np.arange(1, n + 1, dtype=float)
    v = 1.0 + y / freq
    p = float(np.sum(cf / v ** k))
    d2 = float(np.sum(cf * k * (k + 1.0) / freq ** 2 / v ** (k + 2)))
    return d2 / p


def duration(coupon: float, y: float, n: int, kind: str = "modified", freq: int = 2,
             face: float = 100.0) -> float:
    if kind not in DURATION_TYPES:
        raise ValueError(f"kind must be one of {DURATION_TYPES}")
    fn = modified_duration if kind == "modified" else macaulay_duration
    return fn(coupon, y, n, freq, face)


def dv01(coupon: float, y: float, n: int, freq: int = 2, face: float = 100.0,
         notional: float = 1_000_000.0, accrued: float = 0.0) -> float:
    """Dollar value of one basis point, on the DIRTY price (clean + accrued).

    DV01 = ModDur x dirty x 1e-4 x notional/100. Pass `accrued` to see the size of the error
    a clean-price DV01 makes.
    """
    clean = bond_price(coupon, y, n, freq, face)
    md = modified_duration(coupon, y, n, freq, face)
    return md * (clean + accrued) * 1e-4 * notional / face


def pv01(coupon: float, y: float, n: int, freq: int = 2, face: float = 100.0,
         notional: float = 1_000_000.0) -> float:
    """The exact price change for a one-basis-point rise, by repricing. DV01 is its
    first-order approximation; on ordinary bonds they agree to several decimals."""
    p0 = bond_price(coupon, y, n, freq, face)
    p1 = bond_price(coupon, y + 1e-4, n, freq, face)
    return (p0 - p1) * notional / face


def price_change(coupon: float, y: float, n: int, dy: float, freq: int = 2,
                 face: float = 100.0) -> dict:
    """Exact reprice against the duration-only and duration+convexity approximations."""
    p0 = bond_price(coupon, y, n, freq, face)
    md = modified_duration(coupon, y, n, freq, face)
    cx = convexity(coupon, y, n, freq, face)
    exact = bond_price(coupon, y + dy, n, freq, face)
    dur_only = p0 * (1.0 - md * dy)
    dur_cvx = p0 * (1.0 - md * dy + 0.5 * cx * dy * dy)
    return {"dy": dy, "p0": p0, "exact": exact, "duration_only": dur_only,
            "duration_convexity": dur_cvx,
            "err_duration_only": dur_only - exact,
            "err_duration_convexity": dur_cvx - exact,
            "pct_err_duration_only": 100.0 * (dur_only - exact) / exact,
            "pct_err_duration_convexity": 100.0 * (dur_cvx - exact) / exact}


def effective_duration(price_fn: Callable[[float], float], y: float, bump: float = 1e-4) -> float:
    """-(P(+h) - P(-h)) / (2 h P(0)). Works on anything that reprices, including a curve
    shift or a bond with optionality, where the analytic formula does not apply."""
    up, dn, base = price_fn(y + bump), price_fn(y - bump), price_fn(y)
    return -(up - dn) / (2.0 * bump * base)


def effective_convexity(price_fn: Callable[[float], float], y: float,
                        bump: float = 1e-4) -> float:
    up, dn, base = price_fn(y + bump), price_fn(y - bump), price_fn(y)
    return (up + dn - 2.0 * base) / (bump * bump * base)


# ------------------------------------------------------------------ floating-rate note
def frn_price(index: float, quoted_margin: float, discount_margin: float, n: int,
              freq: int = 4, face: float = 100.0, w: float = 1.0,
              current_coupon: float | None = None) -> float:
    """Flat-forward FRN price: coupons at (index + quoted_margin), discounted at
    (index + discount_margin). `n` is the number of coupons left; `w` in (0, 1] is the
    fraction of the current period still to run; `current_coupon` fixes the already-set
    coupon (it does NOT move when the index moves -- that is the whole point).
    """
    if n < 1:
        raise ValueError("n must be at least 1")
    if not 0.0 < w <= 1.0:
        raise ValueError("w must be in (0, 1]")
    tau = 1.0 / freq
    disc = index + discount_margin
    v = 1.0 / (1.0 + disc * tau)
    c_now = (index + quoted_margin if current_coupon is None else current_coupon) * tau * face
    c_next = (index + quoted_margin) * tau * face
    # discount the current (already fixed) coupon over the stub, then the rest off the reset
    stub = 1.0 / (1.0 + disc * tau * w)
    tail = sum(c_next * v ** k for k in range(1, n)) + face * v ** (n - 1)
    return stub * (c_now + tail)


def frn_durations(index: float, quoted_margin: float, discount_margin: float, n: int,
                  freq: int = 4, w: float = 1.0, bump: float = 1e-4,
                  face: float = 100.0) -> dict:
    """Interest-rate duration (shift the INDEX, the fixed current coupon stays fixed) against
    spread duration (shift the DISCOUNT MARGIN only)."""
    c_now = (index + quoted_margin)          # already fixed at the last reset

    def rate_fn(i):
        return frn_price(i, quoted_margin, discount_margin, n, freq, face, w,
                         current_coupon=c_now)

    def spread_fn(s):
        return frn_price(index, quoted_margin, s, n, freq, face, w, current_coupon=c_now)

    p = frn_price(index, quoted_margin, discount_margin, n, freq, face, w,
                  current_coupon=c_now)
    return {"price": p,
            "rate_duration": effective_duration(rate_fn, index, bump),
            "spread_duration": effective_duration(spread_fn, discount_margin, bump),
            "time_to_reset": w / freq,
            "years_to_maturity": (w + n - 1) / freq}


# ------------------------------------------------------------------ QuantLib
def quantlib_cross_checks(coupon: float, y: float, years: int, freq: int = 2) -> dict | None:
    """BondFunctions.duration in all three Duration types, plus convexity and
    basisPointValue, under three compoundings. Returns None if QuantLib is absent."""
    try:
        import QuantLib as ql
    except ImportError:
        return None
    settle = ql.Date(15, 1, 2026)
    ql.Settings.instance().evaluationDate = settle
    sched = ql.Schedule(settle, ql.Date(15, 1, 2026 + years),
                        ql.Period(ql.Semiannual if freq == 2 else ql.Quarterly),
                        ql.UnitedStates(ql.UnitedStates.GovernmentBond), ql.Unadjusted,
                        ql.Unadjusted, ql.DateGeneration.Backward, False)
    dc = ql.ActualActual(ql.ActualActual.ISMA, sched)
    bond = ql.FixedRateBond(0, 100.0, sched, [coupon], dc, ql.Unadjusted)
    out: dict = {"version": ql.__version__, "by_compounding": {}}
    for label, comp in (("Compounded", ql.Compounded), ("Continuous", ql.Continuous),
                        ("Simple", ql.Simple)):
        rate = ql.InterestRate(y, dc, comp, ql.Semiannual if freq == 2 else ql.Quarterly)
        row: dict = {"clean": ql.BondFunctions.cleanPrice(bond, rate, settle)}
        for key, arg in (("macaulay", ql.Duration.Macaulay), ("modified", ql.Duration.Modified),
                         ("simple", ql.Duration.Simple)):
            try:
                row[key] = ql.BondFunctions.duration(bond, rate, arg)
            except RuntimeError as exc:                 # QuantLib refuses some compoundings
                row[key] = None
                row.setdefault("error", str(exc).strip().splitlines()[-1])
        for key, fn in (("convexity", ql.BondFunctions.convexity),
                        ("bpv", ql.BondFunctions.basisPointValue)):
            try:
                row[key] = fn(bond, rate)
            except RuntimeError as exc:
                row[key] = None
                row.setdefault("error", str(exc).strip().splitlines()[-1])
        out["by_compounding"][label] = row
    out["periods"] = freq * years
    return out


# ------------------------------------------------------------------ demo
if __name__ == "__main__":
    W = 92
    NOTIONAL = 1_000_000.0

    print("=" * W)
    print("DURATION, CONVEXITY AND DV01 -- four numbers called 'duration' and two called 'DV01'")
    print("=" * W)

    print("\n1. MACAULAY AND MODIFIED DIFFER BY EXACTLY (1 + y/m)")
    print(f"   {'bond':<26}{'Macaulay':>12}{'Modified':>12}{'ratio':>11}{'1 + y/m':>11}"
          f"{'DV01 error':>13}")
    for cpn, y, yrs, m in ((0.05, 0.05, 10, 2), (0.05, 0.05, 10, 4), (0.04, 0.04, 30, 2),
                           (0.12, 0.12, 10, 2), (0.00, 0.05, 10, 2)):
        n = yrs * m
        mac, mod = macaulay_duration(cpn, y, n, m), modified_duration(cpn, y, n, m)
        print(f"   {f'{cpn:.0%} {yrs}y x{m}/yr @ {y:.0%}':<26}{mac:>12.8f}{mod:>12.8f}"
              f"{mac / mod:>11.8f}{1.0 + y / m:>11.8f}{100 * (mac / mod - 1):>+12.2f}%")
    print("   -> the ratio is (1 + y/m) to the last digit, so the error is entirely predictable")
    print("   -> passing Macaulay where Modified is wanted OVERSTATES every DV01 and every")
    print("      hedge ratio by y/m -- 2.50% on a 5% semiannual bond, 6.00% on a 12% one")

    print("\n2. DURATION IS A FIRST DERIVATIVE -- a 30y 4% bond at par")
    CPN, Y, N = 0.04, 0.04, 60
    p0 = bond_price(CPN, Y, N)
    md, cx = modified_duration(CPN, Y, N), convexity(CPN, Y, N)
    print(f"   P0 = {p0:.6f}   ModDur = {md:.6f}   Convexity = {cx:.4f}")
    print(f"   {'shift':>8}{'exact':>12}{'dur only':>12}{'error':>11}{'error %':>10}"
          f"{'dur+cvx':>12}{'error':>11}")
    for dy in (0.0025, 0.005, 0.01, 0.02, -0.005, -0.01, -0.02):
        r = price_change(CPN, Y, N, dy)
        print(f"   {dy:>+8.2%}{r['exact']:>12.5f}{r['duration_only']:>12.5f}"
              f"{r['err_duration_only']:>+11.5f}{r['pct_err_duration_only']:>+10.3f}"
              f"{r['duration_convexity']:>12.5f}{r['err_duration_convexity']:>+11.5f}")
    m100 = price_change(CPN, Y, N, -0.01)
    m200 = price_change(CPN, Y, N, -0.02)
    print(f"   -> at -100 bp duration alone misses {abs(m100['err_duration_only']):.2f} points "
          f"({m100['pct_err_duration_only']:+.3f}%); at -200 bp it misses "
          f"{abs(m200['err_duration_only']):.2f} points ({m200['pct_err_duration_only']:+.3f}%)")
    print(f"   -> convexity cuts the -200 bp error from "
          f"{abs(m200['err_duration_only']):.2f} to "
          f"{abs(m200['err_duration_convexity']):.2f} points")
    print("   -> and the error is ONE-SIDED: duration alone always underestimates the price")

    print("\n3. DV01, PV01, AND THE CLEAN-PRICE MISTAKE")
    CPN2, Y2, N2 = 0.05, 0.045, 20
    clean = bond_price(CPN2, Y2, N2)
    for w, label in ((1.0, "on a coupon date"), (0.5, "half a period in")):
        acc = 100.0 * CPN2 / 2 * (1.0 - w)
        d_dirty = dv01(CPN2, Y2, N2, notional=NOTIONAL, accrued=acc)
        d_clean = dv01(CPN2, Y2, N2, notional=NOTIONAL, accrued=0.0)
        print(f"   {label:<20} clean {clean:.6f}  accrued {acc:.6f}  "
              f"DV01(dirty) {d_dirty:,.2f}  DV01(clean) {d_clean:,.2f}  "
              f"error {d_clean - d_dirty:+,.2f}")
    print(f"   PV01 by repricing 1 bp: {pv01(CPN2, Y2, N2, notional=NOTIONAL):,.4f}   "
          f"DV01 from modified duration: {dv01(CPN2, Y2, N2, notional=NOTIONAL):,.4f}")
    print(f"   -> they differ by {abs(pv01(CPN2, Y2, N2, notional=NOTIONAL) - dv01(CPN2, Y2, N2, notional=NOTIONAL)):.4f}"
          f" on 1,000,000: the second-order term inside one basis point")

    print("\n4. EFFECTIVE DURATION AGREES WHERE THE CLOSED FORM APPLIES")
    for cpn, y, yrs in ((0.04, 0.04, 30), (0.05, 0.045, 10), (0.0, 0.05, 30)):
        n = 2 * yrs
        eff = effective_duration(lambda yy, c=cpn, nn=n: bond_price(c, yy, nn), y)
        ana = modified_duration(cpn, y, n)
        effc = effective_convexity(lambda yy, c=cpn, nn=n: bond_price(c, yy, nn), y, 1e-4)
        anac = convexity(cpn, y, n)
        print(f"   {cpn:.0%} {yrs}y @ {y:.1%}: effective {eff:.8f} vs analytic {ana:.8f} "
              f"(|diff| {abs(eff - ana):.1e});  convexity {effc:.4f} vs {anac:.4f} "
              f"(|diff| {abs(effc - anac):.1e})")
    print("   -> effective duration is the one to use when the cash flows themselves move "
          "with the rate")

    print("\n5. A FLOATER HAS TWO DURATIONS AND ONLY ONE OF THEM IS FIVE YEARS")
    INDEX, QM, DM, NQ = 0.05, 0.004, 0.004, 20
    print(f"   5y quarterly FRN, index {INDEX:.2%} flat, quoted margin {QM * 1e4:.0f} bp, "
          f"discount margin {DM * 1e4:.0f} bp")
    fixed_dur = modified_duration(INDEX + QM, INDEX + DM, NQ, 4)
    print(f"   the naive comparator -- a 5y quarterly FIXED bond at {INDEX + QM:.2%} -- has "
          f"modified duration {fixed_dur:.6f}")
    print(f"   {'settled':<22}{'dirty':>11}{'rate dur':>11}{'spread dur':>12}"
          f"{'time to reset':>15}{'phantom risk':>15}")
    for w, label in ((1.0, "just after a reset"), (0.5, "half a quarter in"),
                     (0.01, "one day before reset")):
        f = frn_durations(INDEX, QM, DM, NQ, 4, w)
        phantom = (fixed_dur - f["rate_duration"]) * 1e-2 * NOTIONAL
        print(f"   {label:<22}{f['price']:>11.6f}{f['rate_duration']:>11.6f}"
              f"{f['spread_duration']:>12.6f}{f['time_to_reset']:>15.6f}{phantom:>15,.0f}")
    f = frn_durations(INDEX, QM, DM, NQ, 4, 1.0)
    print(f"   -> rate duration tracks the TIME TO THE NEXT RESET ({f['rate_duration']:.6f} vs "
          f"{f['time_to_reset']:.6f} years just after a reset) -- the coupon reprices with the "
          f"curve, so there is almost nothing left to hedge")
    print(f"   -> spread duration is {f['spread_duration']:.6f} years and runs to maturity; it "
          f"matches the fixed comparator to {abs(f['spread_duration'] - fixed_dur):.1e}")
    print(f"   -> booking the FRN as a 5y FIXED bond invents "
          f"{(fixed_dur - f['rate_duration']) * 1e-2 * NOTIONAL:,.0f} of rate risk per 100 bp "
          f"on 1,000,000 that the instrument does not have, and hides the spread risk it does")

    print("\n6. CROSS-CHECK AGAINST QUANTLIB")
    live = quantlib_cross_checks(0.05, 0.05, 10)
    if live is None:
        print("   QuantLib not installed - the closed forms above stand on the bump check in 4")
    else:
        print(f"   QuantLib {live['version']}  (10y 5% semiannual at y = 5.00%)")
        n = live["periods"]
        mine_mac, mine_mod = macaulay_duration(0.05, 0.05, n), modified_duration(0.05, 0.05, n)
        mine_cx = convexity(0.05, 0.05, n)
        def fmt(x, w=13, p=8):
            return f"{x:>{w}.{p}f}" if x is not None else f"{'RAISES':>{w}}"

        print(f"   {'compounding':<14}{'Macaulay':>13}{'Modified':>13}{'Simple':>13}"
              f"{'convexity':>13}{'BPV':>12}")
        for label, d in live["by_compounding"].items():
            print(f"   {label:<14}{fmt(d['macaulay'])}{fmt(d['modified'])}{fmt(d['simple'])}"
                  f"{fmt(d['convexity'], 13, 6)}{fmt(d['bpv'], 12)}"
                  + (f"   <- {d['error']}" if d.get("error") else ""))
        c = live["by_compounding"]["Compounded"]
        print(f"   mine          {mine_mac:>13.8f}{mine_mod:>13.8f}{mine_mac:>13.8f}"
              f"{mine_cx:>13.6f}")
        print(f"   -> |Macaulay diff| {abs(c['macaulay'] - mine_mac):.1e}, "
              f"|Modified diff| {abs(c['modified'] - mine_mod):.1e}, "
              f"|convexity diff| {abs(c['convexity'] - mine_cx):.1e}")
        print(f"   -> Duration.Simple == Duration.Macaulay "
              f"(|diff| {abs(c['simple'] - c['macaulay']):.1e}) -- THREE enum values, TWO "
              f"numbers, and the one you want is Modified")
        print(f"   -> BondFunctions.duration REFUSES a non-compounded rate: "
              f"{live['by_compounding']['Continuous'].get('error')!r} -- one of the few places "
              f"a convention mismatch here actually raises")
        print(f"   -> basisPointValue {c['bpv']:.8f} per 100 = "
              f"{-c['bpv'] * NOTIONAL / 100.0:,.2f} per 1,000,000; my DV01 "
              f"{dv01(0.05, 0.05, n, notional=NOTIONAL):,.2f}   NOTE THE SIGN: QuantLib's BPV "
              f"is the price CHANGE (negative), a DV01 is usually quoted positive")

    print("\n" + "=" * W)
    print("RULE: Macaulay = (1 + y/m) x Modified -- only Modified belongs in a DV01; DV01 is")
    print("      on the DIRTY price; past 100 bp you need convexity; and a floater's rate")
    print("      duration is the time to its next reset, not its maturity.")
    print("=" * W)
