# GENERATED by scripts/build_package.py from plugins/fin-fixed-income/skills/ex-dividend-and-rebate-interest/scripts/ex_dividend.py - do not edit here.
# Edit the skill script and rerun the generator; validate.py checks they match.
# Owning skill: ex-dividend-and-rebate-interest (fin_skills.load('ex-dividend-and-rebate-interest') returns its SKILL.md).

"""Ex-dividend periods, negative accrued (rebate interest), and the UK DMO gilt formulae.

WHY this exists: a gilt bought inside its ex-dividend window does NOT receive the coupon that
is about to be paid, so the buyer is compensated with NEGATIVE accrued interest -- "rebate
interest". Most fixed-income code has no branch for this, and the ones that do can have the
sign wrong without failing.

  * THE UK DMO RULE. "Formulae for Calculating Gilt Prices from Yields", 4th edition,
    18 December 2024, Note 5: the ex-dividend date for all gilts is the date SEVEN BUSINESS
    DAYS before the dividend date. Section Three gives the accrued interest as

        AI = (t/s) * d1        if settlement is on or before the ex-dividend date
        AI = (t/s - 1) * d1    if settlement is after the ex-dividend date

    with t = calendar days from the previous quasi-coupon date to settlement, s = calendar
    days in the full quasi-coupon period, d1 = the next dividend per 100 nominal. The "- 1"
    is the whole trap: it subtracts a full coupon and drives AI below zero.

  * THE QUANTLIB SIGN DEFECT. ql.FixedRateBond takes exCouponPeriod. Writing "seven days
    before" as ql.Period(-7, ql.Days) is ACCEPTED WITHOUT ERROR and does the opposite:
    fixedratecoupon.cpp advances by `-exCouponPeriod_`, so a negative period double-negates
    into a FORWARD advance and the ex-coupon date lands AFTER the coupon. The ex-dividend
    branch then never fires, on any date, and the accrued is silently the plain one.

  * THE BOUNDARY IS ONE DAY WIDE. QuantLib treats settlement ON the ex-coupon date as ex;
    the DMO formula treats settlement on the ex-dividend date as cum.

The reference implementation here is the DMO formula itself, so the QuantLib comparison is a
real check and not a restatement.

Usage:
    from ex_dividend import ex_dividend_date, dmo_accrued, gilt_price_from_yield
"""
from __future__ import annotations

import calendar
from datetime import date, timedelta
from typing import Iterable, Sequence

# UK DMO, "Formulae for Calculating Gilt Prices from Yields", 4th ed. 18 December 2024, Note 5.
GILT_EX_DIVIDEND_BUSINESS_DAYS = 7
# 3.5% War Loan carried a TEN-business-day ex-dividend period in the 3rd edition (16 March
# 2005). It was redeemed in full at par on 2015-03-09 and the 4th edition states seven
# business days for all gilts, with no exception. Kept here only so the number is dated.
WAR_LOAN_EX_DIVIDEND_BUSINESS_DAYS = 10
WAR_LOAN_REDEEMED = date(2015, 3, 9)


# ------------------------------------------------------------------ date helpers
def add_business_days(d: date, n: int, holidays: Iterable[date] = ()) -> date:
    hol = set(holidays)
    step = 1 if n >= 0 else -1
    left = abs(int(n))
    cur = d
    while left:
        cur = cur + timedelta(days=step)
        if cur.weekday() < 5 and cur not in hol:
            left -= 1
    return cur


def add_months(d: date, m: int) -> date:
    """Same day of month m months on, clamped to the month length."""
    y, mo = divmod(d.year * 12 + (d.month - 1) + m, 12)
    return date(y, mo + 1, min(d.day, calendar.monthrange(y, mo + 1)[1]))


def quasi_coupon_dates(maturity: date, earliest: date, freq: int = 2) -> list[date]:
    """The quasi-coupon cycle: dates on the semiannual cycle defined by the MATURITY date,
    whether or not a cash flow occurs on them (UK DMO, Introduction). Generated backwards."""
    if 12 % freq:
        raise ValueError("freq must divide 12")
    step = 12 // freq
    out = [maturity]
    while out[0] > earliest:
        out.insert(0, add_months(out[0], -step))
    return out


def surrounding_quasi_period(settle: date, maturity: date, freq: int = 2) -> tuple[date, date]:
    """(previous, next) quasi-coupon date around `settle`."""
    dates = quasi_coupon_dates(maturity, add_months(settle, -24), freq)
    for a, b in zip(dates, dates[1:]):
        if a <= settle < b:
            return a, b
    raise ValueError("settlement date is not inside the quasi-coupon cycle")


def ex_dividend_date(coupon_date: date, business_days: int = GILT_EX_DIVIDEND_BUSINESS_DAYS,
                     holidays: Iterable[date] = ()) -> date:
    """UK DMO Note 5: the date `business_days` business days before the dividend date."""
    if business_days < 0:
        raise ValueError("business_days is a count of days BEFORE the coupon; pass it positive")
    return add_business_days(coupon_date, -business_days, holidays)


# ------------------------------------------------------------------ the DMO accrued formula
def is_ex_dividend(settle: date, ex_div: date, boundary: str = "dmo") -> bool:
    """`dmo`: settlement AFTER the ex-dividend date is ex (DMO Section Three).
    `quantlib`: settlement ON OR AFTER the ex-coupon date is ex (measured behaviour)."""
    if boundary == "dmo":
        return settle > ex_div
    if boundary == "quantlib":
        return settle >= ex_div
    raise ValueError("boundary must be 'dmo' or 'quantlib'")


def dmo_accrued(coupon: float, settle: date, maturity: float | date, *,
                freq: int = 2, ex_div_business_days: int = GILT_EX_DIVIDEND_BUSINESS_DAYS,
                holidays: Iterable[date] = (), boundary: str = "dmo") -> dict:
    """Accrued interest per 100 nominal, UK DMO Section Three (1)(i).

        AI = (t/s) d1               settlement on or before the ex-dividend date
        AI = (t/s - 1) d1           settlement after it
    """
    prev_q, next_q = surrounding_quasi_period(settle, maturity, freq)
    t = (settle - prev_q).days
    s = (next_q - prev_q).days
    d1 = 100.0 * coupon / freq
    ex = ex_dividend_date(next_q, ex_div_business_days, holidays)
    in_ex = is_ex_dividend(settle, ex, boundary)
    ai = (t / s - (1.0 if in_ex else 0.0)) * d1
    return {"accrued": ai, "t": t, "s": s, "d1": d1, "prev_quasi": prev_q, "next_quasi": next_q,
            "ex_dividend_date": ex, "in_ex_dividend": in_ex}


# ------------------------------------------------------------------ the DMO price formula
def gilt_price_from_yield(coupon: float, y: float, settle: date, maturity: date, *,
                          freq: int = 2,
                          ex_div_business_days: int = GILT_EX_DIVIDEND_BUSINESS_DAYS,
                          holidays: Iterable[date] = (), boundary: str = "dmo") -> dict:
    """UK DMO Section One, conventional gilts (n >= 1):

        P = v^(r/s) [ d1 + d2 v + (c/f) v^2 (1 - v^(n-1)) / (1 - v) + 100 v^n ]

    with v = 1/(1 + y/f), r = calendar days from settlement to the next quasi-coupon date,
    s = days in the quasi-coupon period, n = full quasi-coupon periods from the next
    quasi-coupon date to redemption. d1 is ZERO if the gilt settles ex-dividend -- which is
    the price-side statement of the same fact as the negative accrued.
    """
    acc = dmo_accrued(coupon, settle, maturity, freq=freq,
                      ex_div_business_days=ex_div_business_days, holidays=holidays,
                      boundary=boundary)
    prev_q, next_q = acc["prev_quasi"], acc["next_quasi"]
    r = (next_q - settle).days
    s = acc["s"]
    cycle = quasi_coupon_dates(maturity, next_q, freq)
    n = len(cycle) - 1                       # full periods from next_q to redemption
    c_f = 100.0 * coupon / freq
    v = 1.0 / (1.0 + y / freq)
    d1 = 0.0 if acc["in_ex_dividend"] else c_f
    d2 = c_f if n >= 1 else 0.0
    if n >= 1:
        tail = c_f * v * v * (1.0 - v ** (n - 1)) / (1.0 - v) if n >= 2 else 0.0
        inner = d1 + d2 * v + tail + 100.0 * v ** n
    else:
        inner = d1 + 100.0
    dirty = v ** (r / s) * inner
    return {"dirty": dirty, "clean": dirty - acc["accrued"], "accrued": acc["accrued"],
            "d1": d1, "d2": d2, "n": n, "r": r, "s": s, "v": v,
            "ex_dividend_date": acc["ex_dividend_date"],
            "in_ex_dividend": acc["in_ex_dividend"]}


def ex_dividend_window(coupon: float, y: float, dates: Sequence[date], maturity: date, *,
                       freq: int = 2, holidays: Iterable[date] = (),
                       boundary: str = "dmo") -> list[dict]:
    """Accrued, dirty and clean across a settlement window that crosses the ex-dividend date."""
    rows = []
    for d in dates:
        p = gilt_price_from_yield(coupon, y, d, maturity, freq=freq, holidays=holidays,
                                  boundary=boundary)
        rows.append({"settle": d, "accrued": p["accrued"], "dirty": p["dirty"],
                     "clean": p["clean"], "in_ex_dividend": p["in_ex_dividend"],
                     "d1": p["d1"]})
    return rows


# ------------------------------------------------------------------ QuantLib
def quantlib_ex_coupon_signs(coupon: float, first_coupon: date, maturity: date,
                             settle_dates: Sequence[date],
                             ex_div_business_days: int = GILT_EX_DIVIDEND_BUSINESS_DAYS,
                             face: float = 1_000_000.0, y: float = 0.042) -> dict | None:
    """Build the same gilt three ways in QuantLib: no ex-coupon period, Period(-7, Days) --
    the natural way to write "seven days before", which is wrong -- and Period(7, Days).
    Returns None if QuantLib is not installed."""
    try:
        import QuantLib as ql
    except ImportError:
        return None

    def q(d: date):
        return ql.Date(d.day, d.month, d.year)

    cal = ql.UnitedKingdom(ql.UnitedKingdom.Exchange)
    sched = ql.Schedule(q(first_coupon), q(maturity), ql.Period(ql.Semiannual), cal,
                        ql.Unadjusted, ql.Unadjusted, ql.DateGeneration.Backward, False)
    dc = ql.ActualActual(ql.ActualActual.ISMA, sched)

    def build(period, pay_conv=ql.Unadjusted):
        # The DMO states that cash flows falling on non-business days are NOT adjusted, so
        # the pricer that matches its formula uses Unadjusted, not QuantLib's usual Following.
        if period is None:
            return ql.FixedRateBond(1, 100.0, sched, [coupon], dc, pay_conv)
        return ql.FixedRateBond(1, 100.0, sched, [coupon], dc, pay_conv, 100.0,
                                ql.Date(), cal, period, cal, ql.Preceding, False)

    seven = ql.Period(ex_div_business_days, ql.Days)
    bonds = {"none": build(None),
             "wrong_negative": build(ql.Period(-ex_div_business_days, ql.Days)),
             "correct": build(seven),
             "dmo_boundary": build(ql.Period(ex_div_business_days - 1, ql.Days))}
    bumped = build(seven, ql.Following)

    def ex_dates(bond):
        out = {}
        for cf in bond.cashflows():
            c = ql.as_coupon(cf)
            if c is None or c.exCouponDate() == ql.Date():
                continue
            out[date(c.date().year(), c.date().month(), c.date().dayOfMonth())] = \
                date(c.exCouponDate().year(), c.exCouponDate().month(),
                     c.exCouponDate().dayOfMonth())
        return out

    accrued = {k: [] for k in bonds}
    clean, dirty, clean_bumped = [], [], []
    rate = ql.InterestRate(y, dc, ql.Compounded, ql.Semiannual)
    for d in settle_dates:
        ql.Settings.instance().evaluationDate = q(d)
        for k, b in bonds.items():
            accrued[k].append(b.accruedAmount(q(d)))
        clean.append(ql.BondFunctions.cleanPrice(bonds["correct"], rate, q(d)))
        dirty.append(clean[-1] + bonds["correct"].accruedAmount(q(d)))
        clean_bumped.append(ql.BondFunctions.cleanPrice(bumped, rate, q(d)))
    return {"version": ql.__version__, "settle_dates": list(settle_dates),
            "accrued": accrued, "ex_coupon_dates": {k: ex_dates(b) for k, b in bonds.items()},
            "clean": clean, "dirty": dirty, "clean_following": clean_bumped,
            "yield": y, "face": face}


# ------------------------------------------------------------------ demo
if __name__ == "__main__":
    W = 92
    COUPON, YIELD = 0.04, 0.042
    FIRST, MAT = date(2025, 6, 7), date(2035, 6, 7)
    NEXT_CPN = date(2026, 12, 7)
    FACE = 1_000_000.0
    WINDOW = [date(2026, 11, 24), date(2026, 11, 25), date(2026, 11, 26), date(2026, 11, 27),
              date(2026, 11, 30), date(2026, 12, 4), date(2026, 12, 8)]

    print("=" * W)
    print("EX-DIVIDEND AND REBATE INTEREST -- a 4% gilt, coupons 7 Jun / 7 Dec, maturity "
          f"{MAT}")
    ex = ex_dividend_date(NEXT_CPN)
    print(f"coupon {NEXT_CPN} is a {calendar.day_name[NEXT_CPN.weekday()]}; "
          f"{GILT_EX_DIVIDEND_BUSINESS_DAYS} business days before is {ex} "
          f"({(NEXT_CPN - ex).days} calendar days)")
    print("=" * W)

    print("\n1. ACCRUED ACROSS THE EX-DIVIDEND DATE (UK DMO Section Three, per 100 nominal)")
    print(f"   {'settle':<12}{'ex-div?':>9}{'d1':>7}{'accrued':>12}{'dirty':>12}"
          f"{'clean':>12}{'cash accrued':>16}")
    for r in ex_dividend_window(COUPON, YIELD, WINDOW, MAT):
        print(f"   {str(r['settle']):<12}{'EX' if r['in_ex_dividend'] else 'cum':>9}"
              f"{r['d1']:>7.2f}{r['accrued']:>12.6f}{r['dirty']:>12.6f}{r['clean']:>12.6f}"
              f"{FACE * r['accrued'] / 100.0:>16,.2f}")
    cum = gilt_price_from_yield(COUPON, YIELD, date(2026, 11, 26), MAT)
    exd = gilt_price_from_yield(COUPON, YIELD, date(2026, 11, 27), MAT)
    print(f"   -> accrued falls {cum['accrued']:+.6f} -> {exd['accrued']:+.6f}, a drop of "
          f"{cum['accrued'] - exd['accrued']:.6f} = exactly one coupon ({COUPON / 2 * 100:.2f} "
          f"per 100)")
    print(f"   -> the DIRTY price drops {exd['dirty'] - cum['dirty']:+.6f} but the CLEAN price "
          f"moves only {exd['clean'] - cum['clean']:+.6f}")
    print("   -> that is the point: clean prices are continuous across the ex-dividend date "
          "and dirty ones are not")

    print("\n2. THE QUANTLIB exCouponPeriod SIGN DEFECT")
    live = quantlib_ex_coupon_signs(COUPON, FIRST, MAT, WINDOW)
    if live is None:
        print("   QuantLib not installed - the DMO reference implementation above stands alone")
    else:
        print(f"   QuantLib {live['version']}")
        for k, label in (("wrong_negative", "Period(-7, Days)  WRONG"),
                         ("correct", "Period( 7, Days)  right"),
                         ("dmo_boundary", "Period( 6, Days)  DMO boundary")):
            ecd = live["ex_coupon_dates"][k].get(NEXT_CPN)
            off = (ecd - NEXT_CPN).days
            print(f"   {label:<28} ex-coupon date for the {NEXT_CPN} coupon = {ecd} "
                  f"({off:+d} calendar days)")
        print(f"   {'':<28} -> a NEGATIVE Period advances FORWARD: fixedratecoupon.cpp "
              f"advances by -exCouponPeriod_")
        print(f"\n   {'settle':<12}{'none':>12}{'Period(-7)':>12}{'Period(7)':>12}"
              f"{'Period(6)':>12}{'DMO':>12}{'error on 1mm':>15}")
        for i, d in enumerate(live["settle_dates"]):
            a = live["accrued"]
            dmo = dmo_accrued(COUPON, d, MAT)["accrued"]
            err = FACE * (a["wrong_negative"][i] - a["correct"][i]) / 100.0
            print(f"   {str(d):<12}{a['none'][i]:>+12.6f}{a['wrong_negative'][i]:>+12.6f}"
                  f"{a['correct'][i]:>+12.6f}{a['dmo_boundary'][i]:>+12.6f}{dmo:>+12.6f}"
                  f"{err:>15,.2f}")
        i = live["settle_dates"].index(date(2026, 11, 26))
        a = live["accrued"]
        print(f"   -> on {live['settle_dates'][i]} the wrong sign reads "
              f"{a['wrong_negative'][i]:+.6f} where the right one reads {a['correct'][i]:+.6f}")
        print(f"   -> {FACE * (a['wrong_negative'][i] - a['correct'][i]) / 100.0:,.2f} on "
              f"1,000,000 nominal, and Period(-7) is identical to having NO ex-coupon period "
              f"on every date")
        print(f"   -> Period(7) matches the DMO formula everywhere except the ex-dividend date "
              f"itself, where QuantLib is already ex and the DMO is still cum; Period(6) "
              f"reproduces the DMO boundary")

        print(f"\n3. THE DMO PRICE FORMULA AGAINST QuantLib's, at y = {live['yield']:.3%}"
              f"  (boundary='quantlib' on both sides, so only the PRICER is compared)")
        print(f"   {'settle':<12}{'DMO dirty':>13}{'QL dirty':>13}{'|diff|':>10}"
              f"{'DMO clean':>13}{'QL clean':>13}{'|diff|':>10}{'QL Following':>14}")
        worst = 0.0
        for i, d in enumerate(live["settle_dates"]):
            mine = gilt_price_from_yield(COUPON, live["yield"], d, MAT, boundary="quantlib")
            e1 = abs(mine["dirty"] - live["dirty"][i])
            e2 = abs(mine["clean"] - live["clean"][i])
            worst = max(worst, e1, e2)
            print(f"   {str(d):<12}{mine['dirty']:>13.6f}{live['dirty'][i]:>13.6f}{e1:>10.1e}"
                  f"{mine['clean']:>13.6f}{live['clean'][i]:>13.6f}{e2:>10.1e}"
                  f"{live['clean_following'][i]:>14.6f}")
        bump = live["clean_following"][0] - live["clean"][0]
        print(f"   -> worst |diff| DMO vs QuantLib(Unadjusted) over the window = {worst:.1e}")
        print(f"   -> QuantLib's usual paymentConvention=Following bumps coupons off weekends "
              f"and shifts the clean price by {bump:+.6f} per 100 ({FACE * bump / 100.0:+,.2f} "
              f"on 1,000,000)")
        print("   -> the DMO says cash flows on non-business days are NOT adjusted, so a gilt "
              "pricer uses Unadjusted")

    print("\n4. THE RULE, AND WHAT IT IS NOT")
    print(f"   UK DMO 4th ed. (2024-12-18) Note 5: ex-dividend is {GILT_EX_DIVIDEND_BUSINESS_DAYS}"
          f" business days before the dividend date, for ALL gilts")
    print(f"   3.5% War Loan's {WAR_LOAN_EX_DIVIDEND_BUSINESS_DAYS}-business-day window was in "
          f"the 3rd edition (2005-03-16); the stock was redeemed at par on {WAR_LOAN_REDEEMED}")
    print("   US Treasuries and USD corporates have NO ex-dividend period: accrued runs "
          "straight through")

    print("\n" + "=" * W)
    print("RULE: inside an ex-dividend window accrued is NEGATIVE -- AI = (t/s - 1) * d1 --")
    print("      and QuantLib's exCouponPeriod counts days BACK from the coupon, so it takes")
    print("      Period(7, Days), never Period(-7, Days).")
    print("=" * W)
