# GENERATED by scripts/build_package.py from plugins/fin-fixed-income/skills/libor-transition-and-fallbacks/scripts/fallbacks.py - do not edit here.
# Edit the skill script and rerun the generator; validate.py checks they match.
# Owning skill: libor-transition-and-fallbacks (fin_skills.load('libor-transition-and-fallbacks') returns its SKILL.md).

"""What a US dollar LIBOR contract actually falls back to, from 12 CFR part 253 (Regulation ZZ).

WHY this exists: everyone remembers the five statutory tenor spread adjustments and almost
nobody remembers that the BASE RATE they attach to depends on what kind of contract it is.
"SOFR + 26.161 bp" is ambiguous as written in US law: the spread is the same for every
contract type and the base rate is not.

12 CFR 253.4 gives FIVE different Board-selected base rates for the SAME tenor spread:

  derivative transaction        ISDA "Fallback Rate (SOFR)" -- compounded IN ARREARS   253.4(a)(1)
  non-consumer cash contract    the corresponding CME Term SOFR -- forward-looking     253.4(b)(1)(ii)
  consumer loan                 CME Term SOFR, with the spread transitioning LINEARLY
                                over one year to the statutory value                   253.4(b)(2)
  FHFA-regulated-entity         30-day Average SOFR for EVERY tenor -- backward        253.4(b)(3)(i)(B)
  FFELP ABS                     30-day Average SOFR for 1M/6M/12M, 90-day for 3M       253.4(b)(4)

They are not variations on a theme. In arrears, in advance and backward-looking are three
different observation windows, and on a moving rate path they give materially different
coupons. This file measures that on one seeded path.

The five tenor spread adjustments below are quoted from 12 CFR 253.4(c) (eCFR, read
2026-09-09) and are exact statutory values, not estimates.

Usage:
    from fallbacks import TENOR_SPREADS, fallback_rate, fallback_comparison
"""
from __future__ import annotations

from datetime import date, timedelta
from typing import Iterable, Sequence

import numpy as np

# 12 CFR 253.4(c), verbatim: "(1) 0.00644 percent for overnight LIBOR; (2) 0.11448 percent for
# one-month LIBOR; (3) 0.26161 percent for three-month LIBOR; (4) 0.42826 percent for six-month
# LIBOR; and (5) 0.71513 percent for 12-month LIBOR."  Stored as decimals.
TENOR_SPREADS = {
    "overnight": 0.0000644,
    "1M": 0.0011448,
    "3M": 0.0026161,
    "6M": 0.0042826,
    "12M": 0.0071513,
}
# 12 CFR 253.2: "LIBOR replacement date means the first London banking day after June 30, 2023".
LIBOR_REPLACEMENT_DATE = date(2023, 7, 3)
CONSUMER_TRANSITION_END = date(2024, 7, 3)
# 12 CFR 253.2: LIBOR here is the overnight and 1-, 3-, 6- and 12-month tenors ONLY. The
# one-week and two-month tenors are explicitly excluded and have no Board-selected replacement.
COVERED_TENORS = ("overnight", "1M", "3M", "6M", "12M")
EXCLUDED_TENORS = ("1W", "2M")

# Base rate by contract type, from 12 CFR 253.4. The tenor spread is identical in every row.
BOARD_SELECTED_BASES = (
    # (contract type, base rate for a 3-month LIBOR contract, observation window, citation)
    ("derivative", "ISDA Fallback Rate (SOFR)", "compounded in arrears over the period",
     "253.4(a)(1)"),
    ("non_consumer_cash", "3-month CME Term SOFR", "forward-looking, set in advance",
     "253.4(b)(1)(ii)"),
    ("consumer_loan", "3-month CME Term SOFR", "forward-looking, spread transitions 1 year",
     "253.4(b)(2)"),
    ("fhfa_entity", "30-day Average SOFR", "compounded over the 30 days ENDING at the reset",
     "253.4(b)(3)(i)(B)"),
    ("ffelp_abs", "90-day Average SOFR", "compounded over the 90 days ENDING at the reset",
     "253.4(b)(4)"),
)
CONTRACT_TYPES = tuple(t for t, _, _, _ in BOARD_SELECTED_BASES)

# 12 CFR 253.2, "Relevant benchmark administrator" - five base rates, four administrators.
BENCHMARK_ADMINISTRATORS = {
    "ISDA Fallback Rate (SOFR)": "Bloomberg Index Services Limited",
    "CME Term SOFR": "CME Group Benchmark Administration, Ltd.",
    "consumer loan replacement": "Refinitiv Limited (USD IBOR Cash Fallbacks, Consumer)",
    "30-day / 90-day Average SOFR": "Federal Reserve Bank of New York",
}


def tenor_spread(tenor: str) -> float:
    """The statutory tenor spread adjustment, 12 CFR 253.4(c)."""
    if tenor in EXCLUDED_TENORS:
        raise ValueError(f"{tenor} LIBOR is outside 12 CFR 253 - the definition of LIBOR in "
                         f"253.2 excludes the one-week and two-month tenors")
    if tenor not in TENOR_SPREADS:
        raise ValueError(f"unknown tenor {tenor!r}; covered tenors are {COVERED_TENORS}")
    return TENOR_SPREADS[tenor]


def consumer_transition_spread(day_index: int, transition_days: int, initial_difference: float,
                               statutory: float) -> float:
    """12 CFR 253.4(b)(2)(i): during the one-year period the spread transitions LINEARLY for
    each business day from the day-before difference to the statutory tenor spread."""
    if transition_days <= 0:
        raise ValueError("transition_days must be positive")
    frac = min(max(day_index / transition_days, 0.0), 1.0)
    return initial_difference + frac * (statutory - initial_difference)


# ------------------------------------------------------------------ rate path
def business_days(start: date, end: date, holidays: Iterable[date] = ()) -> list[date]:
    hol = set(holidays)
    out, d = [], start
    while d < end:
        if d.weekday() < 5 and d not in hol:
            out.append(d)
        d += timedelta(days=1)
    return out


def day_weights(dates: Sequence[date], period_end: date) -> list[int]:
    nxt = list(dates[1:]) + [period_end]
    return [(b - a).days for a, b in zip(dates, nxt)]


def compounded_sofr(path: dict, start: date, end: date, holidays: Iterable[date] = (),
                    basis: float = 360.0) -> float:
    """Compounded SOFR over [start, end): the arithmetic behind Fallback Rate (SOFR) and the
    NY Fed's 30-day and 90-day Averages alike. Only the WINDOW differs between them."""
    days = business_days(start, end, holidays)
    if not days:
        raise ValueError("no fixings in the window")
    w = day_weights(days, end)
    f = 1.0
    for d, wt in zip(days, w):
        f *= 1.0 + path[d] * wt / basis
    return (f - 1.0) * basis / sum(w)


def synthetic_sofr(start: date, end: date, holidays: Iterable[date] = (), seed: int = 0,
                   level: float = 0.0430,
                   steps: Sequence[tuple[date, float]] = ()) -> dict:
    """A seeded overnight path with policy steps, so the observation windows disagree."""
    rng = np.random.default_rng(seed)
    r, out = level, {}
    for d in business_days(start, end, holidays):
        r += 0.02 * (level - r) + rng.normal(0.0, 0.00004)
        bump = sum(s for sd, s in steps if d >= sd)
        out[d] = round(r + bump, 4)
    return out


# ------------------------------------------------------------------ the five fallbacks
def fallback_rate(contract_type: str, tenor: str, path: dict, period_start: date,
                  period_end: date, holidays: Iterable[date] = (),
                  term_sofr: float | None = None, consumer_spread: float | None = None,
                  basis: float = 360.0) -> dict:
    """The all-in rate one LIBOR contract falls back to, by contract type.

    `term_sofr` stands in for CME Term SOFR, which is licensed and not redistributable; pass
    the value you are entitled to use. The statutory SPREAD is the same in every branch.
    """
    if contract_type not in CONTRACT_TYPES:
        raise ValueError(f"unknown contract type {contract_type!r}; 12 CFR 253.4 defines "
                         f"{CONTRACT_TYPES}")
    spread = tenor_spread(tenor)
    if contract_type == "derivative":
        base = compounded_sofr(path, period_start, period_end, holidays, basis)
        window = f"in arrears {period_start} -> {period_end}"
    elif contract_type in ("non_consumer_cash", "consumer_loan"):
        if term_sofr is None:
            raise ValueError("CME Term SOFR is licensed; pass term_sofr explicitly")
        base, window = term_sofr, f"term rate set {period_start}"
    elif contract_type == "fhfa_entity":
        base = compounded_sofr(path, period_start - timedelta(days=30), period_start,
                               holidays, basis)
        window = f"30 days ending {period_start}"
    else:                                           # ffelp_abs, 3-month tenor
        lookback = 90 if tenor == "3M" else 30
        base = compounded_sofr(path, period_start - timedelta(days=lookback), period_start,
                               holidays, basis)
        window = f"{lookback} days ending {period_start}"
    if contract_type == "consumer_loan" and consumer_spread is not None:
        spread = consumer_spread
    return {"contract_type": contract_type, "base": base, "spread": spread,
            "all_in": base + spread, "window": window}


def fallback_comparison(tenor: str, path: dict, period_start: date, period_end: date,
                        holidays: Iterable[date] = (), notional: float = 10_000_000.0,
                        term_sofr: float | None = None, basis: float = 360.0) -> list[dict]:
    """All five Board-selected fallbacks on ONE contract and ONE period, in bp and in cash."""
    days = (period_end - period_start).days
    rows = []
    ref = None
    for ct in CONTRACT_TYPES:
        if ct == "consumer_loan":
            continue                                # identical to non_consumer_cash after 2024
        r = fallback_rate(ct, tenor, path, period_start, period_end, holidays, term_sofr, None,
                          basis)
        ref = r["all_in"] if ref is None else ref
        r["bp_vs_derivative"] = 1e4 * (r["all_in"] - ref)
        r["coupon"] = notional * r["all_in"] * days / basis
        r["cash_vs_derivative"] = notional * (r["all_in"] - ref) * days / basis
        rows.append(r)
    return rows


def quarterly_periods(year: int, holidays: Iterable[date] = ()) -> list[tuple[date, date]]:
    edges = [date(year, m, 1) for m in (1, 4, 7, 10)] + [date(year + 1, 1, 1)]
    return list(zip(edges, edges[1:]))


# ------------------------------------------------------------------ demo
if __name__ == "__main__":
    W = 96
    HOLIDAYS = [date(2026, 1, 1), date(2026, 1, 19), date(2026, 2, 16), date(2026, 4, 3),
                date(2026, 5, 25), date(2026, 6, 19), date(2026, 7, 3), date(2026, 9, 7),
                date(2026, 10, 12), date(2026, 11, 11), date(2026, 11, 26), date(2026, 12, 25),
                date(2025, 11, 11), date(2025, 11, 27), date(2025, 12, 25)]
    STEPS = ((date(2026, 6, 18), 0.0025), (date(2026, 9, 17), -0.0025))
    PATH = synthetic_sofr(date(2025, 9, 1), date(2027, 1, 5), HOLIDAYS, seed=3, steps=STEPS)
    NOTIONAL = 10_000_000.0
    TENOR = "3M"

    print("=" * W)
    print("LIBOR FALLBACKS -- 12 CFR part 253 (Regulation ZZ): one spread, FIVE base rates")
    print("=" * W)

    print("\n1. THE FIVE STATUTORY TENOR SPREAD ADJUSTMENTS, 12 CFR 253.4(c)")
    for t in COVERED_TENORS:
        s = tenor_spread(t)
        print(f"   {t:<10}{s:>12.5%}  = {s * 1e4:>8.3f} bp   "
              f"({s * NOTIONAL * 0.25:>10,.2f} per quarter on {NOTIONAL:,.0f})")
    print(f"   -> and 12 CFR 253.2 covers ONLY {COVERED_TENORS}: the "
          f"{' and '.join(EXCLUDED_TENORS)} tenors are excluded by definition")
    print(f"   -> the LIBOR replacement date is {LIBOR_REPLACEMENT_DATE} -- 'the first London "
          f"banking day after June 30, 2023'")

    print("\n2. THE SAME SPREAD, FIVE DIFFERENT BASE RATES")
    print(f"   {'contract type':<20}{'base rate':<28}{'observation window':<49}{'cite':<18}")
    for ct, base, window, cite in BOARD_SELECTED_BASES:
        print(f"   {ct:<20}{base:<28}{window:<49}{cite:<18}")
    print("   administrators (253.2):")
    for k, v in BENCHMARK_ADMINISTRATORS.items():
        print(f"     {k:<32}{v}")

    print("\n3. WHAT THAT COSTS ON ONE 3-MONTH CONTRACT, MEASURED")
    start, end = date(2026, 7, 1), date(2026, 10, 1)
    # CME Term SOFR is licensed; stand it in with a perfect forward -- the compounded rate the
    # period will actually realise. That is the FRIENDLIEST possible assumption for the cash
    # contract, and the averages still disagree.
    term = compounded_sofr(PATH, start, end, HOLIDAYS)
    print(f"   period {start} -> {end}, {NOTIONAL:,.0f} notional, {TENOR} LIBOR")
    print(f"   (CME Term SOFR is licensed and not redistributable; stood in with a PERFECT "
          f"forward = {term:.6%})")
    print(f"   {'contract type':<20}{'base':>10}{'spread':>10}{'all-in':>10}  "
          f"{'window':<38}{'bp vs deriv':>12}{'cash':>12}")
    for r in fallback_comparison(TENOR, PATH, start, end, HOLIDAYS, NOTIONAL, term):
        print(f"   {r['contract_type']:<20}{r['base']:>10.4%}{r['spread']:>10.4%}"
              f"{r['all_in']:>10.4%}  {r['window']:<38}{r['bp_vs_derivative']:>+12.2f}"
              f"{r['cash_vs_derivative']:>+12,.2f}")

    print("\n4. OVER A FULL YEAR OF QUARTERLY RESETS, WITH TWO POLICY MOVES")
    print(f"   policy path: " + ", ".join(f"{d} {s * 1e4:+.0f} bp" for d, s in STEPS))
    cols = ("derivative", "non_consumer_cash", "fhfa_entity", "ffelp_abs")
    totals = {ct: 0.0 for ct in cols}
    print(f"   {'period':<26}{'derivative':>12}{'cash (term)':>12}{'FHFA 30d':>12}"
          f"{'FFELP 90d':>12}   {'FHFA bp':>9}{'FFELP bp':>10}")
    worst_bp = 0.0
    for ps, pe in quarterly_periods(2026, HOLIDAYS):
        term_q = compounded_sofr(PATH, ps, pe, HOLIDAYS)
        rates = {}
        for r in fallback_comparison(TENOR, PATH, ps, pe, HOLIDAYS, NOTIONAL, term_q):
            rates[r["contract_type"]] = r
            totals[r["contract_type"]] += r["coupon"]
        worst_bp = max(worst_bp, abs(rates["fhfa_entity"]["bp_vs_derivative"]),
                       abs(rates["ffelp_abs"]["bp_vs_derivative"]))
        print(f"   {f'{ps} -> {pe}':<26}"
              + "".join(f"{rates[c]['all_in']:>12.4%}" for c in cols)
              + f"   {rates['fhfa_entity']['bp_vs_derivative']:>+9.2f}"
                f"{rates['ffelp_abs']['bp_vs_derivative']:>+10.2f}")
    ref = totals["derivative"]
    print(f"   {'YEAR TOTAL INTEREST':<26}" + "".join(f"{totals[c]:>12,.0f}" for c in cols))
    print(f"   {'vs the derivative':<26}" + "".join(f"{totals[c] - ref:>+12,.0f}" for c in cols))
    worst = max(abs(totals[c] - ref) for c in totals)
    print(f"   -> largest SINGLE-PERIOD gap {worst_bp:.2f} bp; the lag cuts both ways, so over "
          f"a full year it partly nets to {worst:,.0f} on {NOTIONAL:,.0f}")
    print(f"   -> a {worst_bp:.2f} bp reset error against a statutory adjustment of "
          f"{tenor_spread(TENOR) * 1e4:.3f} bp: the base rate matters more than the spread "
          f"everybody quotes")

    print("\n5. THE CONSUMER TRANSITION IS A RAMP, NOT A STEP -- 12 CFR 253.4(b)(2)(i)")
    statutory = tenor_spread(TENOR)
    initial = 0.0015                     # illustrative day-before difference, not a quoted value
    print(f"   statutory 3M spread {statutory * 1e4:.3f} bp; illustrative day-before difference "
          f"{initial * 1e4:.1f} bp; 252 business days")
    print(f"   {'business day':>14}{'spread (bp)':>14}{'quarterly coupon effect':>26}")
    for k in (0, 63, 126, 189, 252, 300):
        s = consumer_transition_spread(k, 252, initial, statutory)
        print(f"   {k:>14}{s * 1e4:>14.3f}{NOTIONAL * (s - statutory) * 0.25:>26,.2f}")
    print(f"   -> a consumer loan and an otherwise identical business loan carried DIFFERENT "
          f"spreads every day of {LIBOR_REPLACEMENT_DATE.year}-"
          f"{CONSUMER_TRANSITION_END.year}, converging only on {CONSUMER_TRANSITION_END}")

    print("\n" + "=" * W)
    print("RULE: the five tenor spread adjustments in 12 CFR 253.4(c) are the SAME for every")
    print("      contract type; the BASE RATE is not. 'SOFR + 26.161 bp' does not name a rate")
    print("      until you say derivative, cash, consumer, FHFA or FFELP.")
    print("=" * W)
