# GENERATED by scripts/build_package.py from plugins/fin-fixed-income/skills/yield-measures-and-bill-quotes/scripts/yield_measures.py - do not edit here.
# Edit the skill script and rerun the generator; validate.py checks they match.
# Owning skill: yield-measures-and-bill-quotes (fin_skills.load('yield-measures-and-bill-quotes') returns its SKILL.md).

"""Yield to maturity, current yield, yield to worst -- and the money-market quotes that are
not yields at all.

WHY this exists: "5.00%" on a Treasury bill screen is a DISCOUNT RATE. It is not a yield, it
is not comparable to a note's yield to maturity, and converting it wrongly is worth tens of
basis points. Three separate arithmetic conventions collide here and none of them raises:

  * DISCOUNT BASIS. A bill discount rate is (100 - P)/100 * 360/days -- the gain divided by
    the FACE amount, on a 360-day year. A yield divides by the PRICE, on a 365-day year. The
    two disagree by more the longer and the higher the bill.

  * TREASURY'S OWN CONVERSION IS TWO FORMULAS. 31 CFR 356 Appendix B section VI gives a
    simple formula for bills of not more than one half-year and a QUADRATIC for longer ones,
    because a 52-week bill must be made comparable to a security that pays a coupon halfway
    through. Applying the short formula to a 364-day bill overstates the investment rate.

  * CURRENT YIELD AND YIELD TO WORST. Current yield ignores the pull to par entirely. Yield
    to maturity on a callable bond trading above par is not the yield you will earn.

The reference implementation reproduces both worked examples printed in 31 CFR 356 Appendix B
(8.076% and 8.237%), so the formulas are checked against the regulation and not against
themselves. QuantLib, when importable, checks the price/yield side.

Usage:
    from yield_measures import bill_price_from_discount, treasury_investment_rate, ytm
"""
from __future__ import annotations

import math
from typing import Sequence

from scipy.optimize import brentq

# 31 CFR 356 Appendix B, VI.B.2 applies "for bills of more than one half-year to maturity".
DAYS_IN_YEAR = 365.0
DISCOUNT_BASIS_DAYS = 360.0


# ------------------------------------------------------------------ bills
def bill_price_from_discount(discount: float, days: int, basis: float = DISCOUNT_BASIS_DAYS,
                             face: float = 100.0) -> float:
    """P = face * (1 - d * days / 360). The discount is quoted ON THE FACE, not on the price."""
    if days <= 0:
        raise ValueError("days must be positive")
    return face * (1.0 - discount * days / basis)


def bill_discount_from_price(price: float, days: int, basis: float = DISCOUNT_BASIS_DAYS,
                             face: float = 100.0) -> float:
    if price <= 0:
        raise ValueError("price must be positive")
    return (face - price) / face * basis / days


def money_market_yield(price: float, days: int, face: float = 100.0) -> float:
    """The add-on (CD-equivalent) rate: gain over PRICE, still on a 360-day year."""
    return (face - price) / price * DISCOUNT_BASIS_DAYS / days


def bond_equivalent_yield(price: float, days: int, year: float = DAYS_IN_YEAR,
                          face: float = 100.0) -> float:
    """Simple interest on the PRICE over a 365-day year -- the short-bill investment rate."""
    if price <= 0:
        raise ValueError("price must be positive")
    return (face - price) / price * year / days


def treasury_investment_rate(price: float, r: int, y: float = DAYS_IN_YEAR) -> float:
    """The investment rate (coupon-equivalent yield), 31 CFR 356 Appendix B section VI.

    Not more than one half-year (r <= y/2):   i = (100 - P)/P * y/r
    More than one half-year:                  P [1 + (r - y/2)(i/y)] (1 + i/2) = 100,
    solved as a quadratic with b = r/y, a = (r/2y) - .25, c = (P - 100)/P and
    i = (-b + sqrt(b^2 - 4ac)) / (2a).
    """
    if price <= 0:
        raise ValueError("price must be positive")
    if r <= 0:
        raise ValueError("r must be positive")
    if r <= y / 2.0:
        return (100.0 - price) / price * y / r
    b = r / y
    a = r / (2.0 * y) - 0.25
    c = (price - 100.0) / price
    disc = b * b - 4.0 * a * c
    if disc < 0.0:
        raise ValueError("no real investment rate for this price and maturity")
    return (-b + math.sqrt(disc)) / (2.0 * a)


def bill_table(discount: float, day_counts: Sequence[int], face: float = 1_000_000.0) -> list[dict]:
    """One discount rate across several maturities: the four numbers people confuse."""
    rows = []
    for d in day_counts:
        p = bill_price_from_discount(discount, d)
        bey = bond_equivalent_yield(p, d)
        inv = treasury_investment_rate(p, d)
        rows.append({"days": d, "price": p, "discount": discount,
                     "money_market_yield": money_market_yield(p, d),
                     "bond_equivalent_yield": bey, "investment_rate": inv,
                     "bp_discount_to_bey": 1e4 * (bey - discount),
                     "bp_bey_to_investment": 1e4 * (inv - bey),
                     "uses_quadratic": d > DAYS_IN_YEAR / 2.0,
                     "cash_gain": face * (100.0 - p) / 100.0})
    return rows


# ------------------------------------------------------------------ coupon bonds
def bond_price_from_yield(coupon: float, y: float, n: int, w: float = 1.0, freq: int = 2,
                          face: float = 100.0) -> dict:
    """Street-convention price of a coupon bond.

    n = number of remaining coupons, w = fraction of the current coupon period still to run
    (w = 1 on a coupon date). Cash flows land at w, w+1, ..., w+n-1 periods.
    Returns dirty, clean and accrued per `face`.
    """
    if n < 1:
        raise ValueError("n must be at least 1")
    if not 0.0 < w <= 1.0:
        raise ValueError("w must be in (0, 1]")
    c = face * coupon / freq
    v = 1.0 / (1.0 + y / freq)
    dirty = sum(c * v ** (w + k) for k in range(n)) + face * v ** (w + n - 1)
    accrued = c * (1.0 - w)
    return {"dirty": dirty, "accrued": accrued, "clean": dirty - accrued}


def ytm(clean: float, coupon: float, n: int, w: float = 1.0, freq: int = 2,
        face: float = 100.0) -> float:
    """Yield to maturity from a CLEAN price, by the same street convention."""
    def f(y):
        return bond_price_from_yield(coupon, y, n, w, freq, face)["clean"] - clean
    return brentq(f, -0.9, 5.0, xtol=1e-14, rtol=1e-15, maxiter=200)


def current_yield(coupon: float, clean: float, face: float = 100.0) -> float:
    """Annual coupon over the clean price. Ignores the pull to par completely."""
    if clean <= 0:
        raise ValueError("clean price must be positive")
    return face * coupon / clean


def yield_to_worst(clean: float, coupon: float, calls: Sequence[tuple[int, float]],
                   n_maturity: int, freq: int = 2, face: float = 100.0) -> dict:
    """`calls` is [(periods to the call, call price), ...]; maturity is added at `face`.

    Each candidate is repriced as a bullet redeeming at its own call price on its own date.
    The worst of them is the yield to worst.
    """
    cands = list(calls) + [(n_maturity, face)]
    out = []
    for n, redemption in cands:
        def f(y, n=n, redemption=redemption):
            c = face * coupon / freq
            v = 1.0 / (1.0 + y / freq)
            return sum(c * v ** (k + 1) for k in range(n)) + redemption * v ** n - clean
        out.append({"periods": n, "redemption": redemption,
                    "yield": brentq(f, -0.9, 5.0, xtol=1e-14, rtol=1e-15, maxiter=200)})
    worst = min(out, key=lambda r: r["yield"])
    to_maturity = out[-1]
    return {"candidates": out, "yield_to_worst": worst["yield"], "worst_at": worst["periods"],
            "yield_to_maturity": to_maturity["yield"],
            "bp_ytm_over_ytw": 1e4 * (to_maturity["yield"] - worst["yield"])}


# ------------------------------------------------------------------ QuantLib
def quantlib_cross_checks(discount: float, days: Sequence[int], coupon: float, y: float,
                          years: int) -> dict | None:
    """Check the bill arithmetic and the coupon-bond price/yield against QuantLib 1.43."""
    try:
        import QuantLib as ql
    except ImportError:
        return None
    out: dict = {"version": ql.__version__, "bills": []}
    for d in days:
        p = bill_price_from_discount(discount, d)
        bey = bond_equivalent_yield(p, d)
        rate = ql.InterestRate(bey, ql.Actual365Fixed(), ql.Simple, ql.Annual)
        out["bills"].append({"days": d, "price": p, "bey": bey,
                             "ql_compound_factor": rate.compoundFactor(d / 365.0),
                             "direct": 100.0 / p})
    settle = ql.Date(15, 1, 2026)
    ql.Settings.instance().evaluationDate = settle
    sched = ql.Schedule(settle, ql.Date(15, 1, 2026 + years), ql.Period(ql.Semiannual),
                        ql.UnitedStates(ql.UnitedStates.GovernmentBond), ql.Unadjusted,
                        ql.Unadjusted, ql.DateGeneration.Backward, False)
    dc = ql.ActualActual(ql.ActualActual.ISMA, sched)
    # Unadjusted payment dates: the default Following bumps coupons off weekends and adds a
    # few tenths of a basis point of discounting that has nothing to do with the yield formula.
    bond = ql.FixedRateBond(0, 100.0, sched, [coupon], dc, ql.Unadjusted)
    bond_following = ql.FixedRateBond(0, 100.0, sched, [coupon], dc, ql.Following)
    rate = ql.InterestRate(y, dc, ql.Compounded, ql.Semiannual)
    out["bond_clean"] = ql.BondFunctions.cleanPrice(bond, rate, settle)
    out["bond_clean_following"] = ql.BondFunctions.cleanPrice(bond_following, rate, settle)
    out["bond_yield"] = ql.BondFunctions.bondYield(
        bond, ql.BondPrice(out["bond_clean"], ql.BondPrice.Clean), dc, ql.Compounded,
        ql.Semiannual, settle)
    out["periods"] = 2 * years
    return out


# ------------------------------------------------------------------ demo
if __name__ == "__main__":
    W = 92
    DISCOUNT = 0.05
    DAYS = (28, 91, 182, 364)
    FACE = 1_000_000.0

    print("=" * W)
    print("YIELD MEASURES AND BILL QUOTES -- a 5.00% Treasury bill DISCOUNT RATE is not a yield")
    print("=" * W)

    print("\n1. THE SAME 5.00% BILL, FOUR WAYS")
    print(f"   {'days':>5}{'price':>12}{'discount':>11}{'MM yield':>11}{'BEY':>11}"
          f"{'inv. rate':>11}{'d->BEY':>10}{'BEY->IR':>10}")
    for r in bill_table(DISCOUNT, DAYS, FACE):
        print(f"   {r['days']:>5}{r['price']:>12.6f}{r['discount']:>11.4%}"
              f"{r['money_market_yield']:>11.4%}{r['bond_equivalent_yield']:>11.4%}"
              f"{r['investment_rate']:>11.4%}{r['bp_discount_to_bey']:>+10.1f}"
              f"{r['bp_bey_to_investment']:>+10.1f}")
    rows = {r["days"]: r for r in bill_table(DISCOUNT, DAYS, FACE)}
    print(f"   -> a 5.00% discount rate is a {rows[182]['bond_equivalent_yield']:.4%} yield at "
          f"182 days ({rows[182]['bp_discount_to_bey']:+.1f} bp), "
          f"{rows[91]['bond_equivalent_yield']:.4%} at 91 ({rows[91]['bp_discount_to_bey']:+.1f}"
          f" bp), {rows[364]['bond_equivalent_yield']:.4%} at 364 "
          f"({rows[364]['bp_discount_to_bey']:+.1f} bp)")
    print(f"   -> and above one half-year Treasury's own investment rate takes the quadratic: "
          f"{rows[364]['investment_rate']:.4%}, a further "
          f"{rows[364]['bp_bey_to_investment']:.1f} bp")
    print("   -> the gap grows with the LEVEL of rates too, at a fixed 182 days:")
    print(f"      {'discount':>10}{'BEY':>11}{'gap (bp)':>11}")
    for d in (0.01, 0.03, 0.05, 0.08, 0.12):
        p = bill_price_from_discount(d, 182)
        b = bond_equivalent_yield(p, 182)
        print(f"      {d:>10.2%}{b:>11.4%}{1e4 * (b - d):>+11.1f}")

    print("\n2. THE TWO FORMULAS ARE IN THE REGULATION, WITH WORKED EXAMPLES")
    print("   31 CFR 356 Appendix B, VI.B.1 (not more than one half-year):")
    ex1 = treasury_investment_rate(99.559444, 20, 365)
    print(f"     cash management bill 1990-06-01 -> 1990-06-21, P = 99.559444, r = 20, y = 365")
    print(f"     regulation prints i = 8.076%   this file: {ex1:.6%}  -> {ex1 * 100:.3f}%")
    print("   31 CFR 356 Appendix B, VI.B.2 (more than one half-year, the quadratic):")
    ex2 = treasury_investment_rate(92.265000, 364, 365)
    print(f"     52-week bill 1990-06-07 -> 1991-06-06, P = 92.265000, r = 364, y = 365")
    print(f"     regulation prints i = 8.237%   this file: {ex2:.6%}  -> {ex2 * 100:.3f}%")
    naive = bond_equivalent_yield(92.265000, 364, 365)
    print(f"     the short formula on the same bill would give {naive:.6%} "
          f"({1e4 * (naive - ex2):+.1f} bp too high)")

    print("\n3. CURRENT YIELD IGNORES THE PULL TO PAR")
    print(f"   {'coupon':>8}{'clean':>9}{'years':>7}{'current yield':>15}{'YTM':>11}"
          f"{'gap (bp)':>11}")
    for cpn, clean, yrs in ((0.03, 85.0, 5), (0.03, 85.0, 20), (0.08, 118.0, 5),
                            (0.08, 118.0, 20), (0.05, 100.0, 10)):
        cy = current_yield(cpn, clean)
        y = ytm(clean, cpn, 2 * yrs)
        print(f"   {cpn:>8.2%}{clean:>9.2f}{yrs:>7}{cy:>15.4%}{y:>11.4%}"
              f"{1e4 * (y - cy):>+11.1f}")
    print("   -> current yield is right only at par; on a discount bond it understates and on "
          "a premium bond it overstates")

    print("\n4. YIELD TO WORST ON A CALLABLE TRADING ABOVE PAR")
    CLEAN, CPN = 108.0, 0.05
    ytw = yield_to_worst(CLEAN, CPN, [(4, 102.0), (6, 101.0), (10, 100.0)], 20)
    print(f"   5% bond, 10 years to maturity, clean {CLEAN:.2f}, calls at 102 (2y), 101 (3y), "
          f"100 (5y)")
    for c in ytw["candidates"]:
        tag = "MATURITY" if c["redemption"] == 100.0 and c["periods"] == 20 else "call"
        print(f"     redeem {c['redemption']:6.2f} in {c['periods'] / 2:4.1f}y ({tag:8s})  "
              f"yield {c['yield']:.4%}")
    print(f"   -> yield to maturity {ytw['yield_to_maturity']:.4%}, yield to WORST "
          f"{ytw['yield_to_worst']:.4%} at {ytw['worst_at'] / 2:.1f} years")
    print(f"   -> quoting the YTM overstates by {ytw['bp_ytm_over_ytw']:.1f} bp on a bond the "
          f"issuer will almost certainly call")

    print("\n5. CROSS-CHECK AGAINST QUANTLIB")
    live = quantlib_cross_checks(DISCOUNT, DAYS, 0.05, 0.045, 10)
    if live is None:
        print("   QuantLib not installed - the reference implementation above stands alone")
    else:
        print(f"   QuantLib {live['version']}")
        for b in live["bills"]:
            print(f"   {b['days']:>4}d bill: BEY {b['bey']:.6%}; InterestRate(Simple, ACT/365)"
                  f".compoundFactor = {b['ql_compound_factor']:.10f} vs 100/P = "
                  f"{b['direct']:.10f}  |diff| {abs(b['ql_compound_factor'] - b['direct']):.1e}")
        mine = bond_price_from_yield(0.05, 0.045, live["periods"])["clean"]
        print(f"   10y 5% semiannual at y = 4.50%: QuantLib clean {live['bond_clean']:.10f}  "
              f"mine {mine:.10f}  |diff| {abs(live['bond_clean'] - mine):.1e}")
        mine_y = ytm(live["bond_clean"], 0.05, live["periods"])
        print(f"   and back: QuantLib yield {live['bond_yield']:.10f}  mine {mine_y:.10f}  "
              f"|diff| {abs(live['bond_yield'] - mine_y):.1e}")
        gap = live["bond_clean_following"] - live["bond_clean"]
        print(f"   (the same bond with QuantLib's DEFAULT paymentConvention=Following prices "
              f"{live['bond_clean_following']:.10f}, {gap:+.6f} -- weekend-bumped coupons, not "
              f"a different yield)")

    print("\n" + "=" * W)
    print("RULE: a bill DISCOUNT RATE is not a yield -- it divides by face on a 360-day year.")
    print("      Convert with 31 CFR 356 App. B: simple up to one half-year, the QUADRATIC")
    print("      beyond it. Current yield ignores the pull to par; on a callable, quote YTW.")
    print("=" * W)
