# GENERATED by scripts/build_package.py from plugins/fin-credit/skills/corporate-bond-data-and-trace/scripts/trace.py - do not edit here.
# Edit the skill script and rerun the generator; validate.py checks they match.
# Owning skill: corporate-bond-data-and-trace (fin_skills.load('corporate-bond-data-and-trace') returns its SKILL.md).

"""What TRACE gives you and what it HIDES -- the 15-minute reporting window and the
dissemination size caps, measured.

WHY this exists: TRACE looks like a tape, so it gets used like one. Two things about it are not
what a model assumes:

  1. REPORTING IS STILL 15 MINUTES, NOT ONE. The SEC approved a one-minute TRACE reporting rule
     in 2024; FINRA then abandoned it. Regulatory Notice 25-17 keeps the 15-minute outer limit,
     effective 2026-06-08. Anything trained through 2025 will confidently say "one minute".
     `reporting_timeframes()` carries the FINRA table with its source URL and the date it was read.

  2. DISSEMINATED SIZE IS RIGHT-CENSORED. Trades above $5MM par (investment grade) or $1MM par
     (non-investment grade) are disseminated as "5MM+" / "1MM+". So TRACE volume is a LOWER
     BOUND, not a measurement, and every statistic built on it inherits the censoring: total
     volume, average trade size, a volume-weighted average price, and any Amihud-style
     illiquidity ratio with volume in the denominator.

The demo simulates one seeded tape, applies each cap to the SAME trades, and measures what the
cap does. Nothing here needs the internet: the tape is synthetic and the regulatory facts are
quoted with their source.

Usage:
    from trace import simulate_tape, censoring_report, amihud_bias, censored_lognormal_mle
    censoring_report(simulate_tape(), cap=5e6)["hidden_volume_pct"]
"""
from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Sequence

import numpy as np
from scipy.optimize import minimize
from scipy.stats import norm

SEED = 20260909

# Dissemination size caps, FINRA. See `reporting_timeframes()` for the source and date.
CAP_INVESTMENT_GRADE = 5_000_000.0
CAP_HIGH_YIELD = 1_000_000.0

# The synthetic tape: one lognormal size distribution used under BOTH caps, so the only thing
# that differs between the investment-grade and high-yield runs is the cap itself.
LOG_SIZE_MEAN = math.log(250_000.0)
LOG_SIZE_SD = 1.5


def reporting_timeframes() -> list[dict[str, str]]:
    """FINRA TRACE reporting outer limits, read at the source on 2026-09-09.

    Source: finra.org/filing-reporting/trade-reporting-and-compliance-engine-trace/
    trace-reporting-timeframes, and Regulatory Notice 25-17 (published 2025-12-04) for the
    abandonment of the one-minute proposal.
    """
    return [
        {"security": "Corporate and agency bonds", "limit": "within 15 minutes of execution",
         "rule": "FINRA Rule 6730(a)(1)"},
        {"security": "Asset-backed securities", "limit": "within 15 minutes of execution",
         "rule": "FINRA Rule 6730(a)(3)"},
        {"security": "Most other securitized products", "limit": "same day, TRACE business hours",
         "rule": "FINRA Rule 6730(a)(3)(A)"},
        {"security": "US Treasury securities", "limit": "generally within 60 minutes",
         "rule": "FINRA Rule 6730(a)(4)(A)"},
    ]


def dissemination_caps() -> list[dict[str, object]]:
    """The two caps, and what the tape shows above them."""
    return [
        {"grade": "Investment grade", "cap": CAP_INVESTMENT_GRADE, "printed_as": "5MM+"},
        {"grade": "Non-investment grade", "cap": CAP_HIGH_YIELD, "printed_as": "1MM+"},
    ]


# --------------------------------------------------------------------------- staleness
def staleness(annual_vol: float = 0.05, minutes: Sequence[float] = (1.0, 15.0, 60.0),
              minutes_per_year: float = 252 * 6.5 * 60) -> list[dict[str, float]]:
    """Standard deviation of the price move inside a reporting window, in basis points.

    A print you read is at least as old as the reporting limit, so the window is the size of
    the price move you cannot see. Pure sqrt-of-time arithmetic on a stated annual vol.
    """
    if annual_vol <= 0 or minutes_per_year <= 0:
        raise ValueError("annual_vol and minutes_per_year must be positive")
    out = []
    base = annual_vol / math.sqrt(minutes_per_year)
    for m in minutes:
        out.append({"minutes": m, "sd_bp": base * math.sqrt(m) * 1e4,
                    "vs_one_minute": math.sqrt(m / minutes[0])})
    return out


# --------------------------------------------------------------------------- the synthetic tape
@dataclass(frozen=True)
class Tape:
    day: np.ndarray          # trading day index
    size: np.ndarray         # true par amount
    price: np.ndarray        # traded price per 100
    mid: np.ndarray          # the (unobservable) mid at the time of the trade
    side: np.ndarray         # +1 customer buy, -1 customer sell

    def __len__(self) -> int:
        return len(self.size)


def simulate_tape(n_days: int = 250, trades_per_day: int = 12, seed: int = SEED) -> Tape:
    """One bond's tape: lognormal sizes, a random-walk mid, and a half-spread that SHRINKS
    with trade size -- the empirical regularity that makes the size censoring bite the VWAP.
    """
    if n_days < 1 or trades_per_day < 1:
        raise ValueError("n_days and trades_per_day must be at least 1")
    rng = np.random.default_rng(seed)
    n = n_days * trades_per_day
    day = np.repeat(np.arange(n_days), trades_per_day)
    size = np.exp(rng.normal(LOG_SIZE_MEAN, LOG_SIZE_SD, n))
    daily_ret = rng.normal(0.0, 0.05 / math.sqrt(252), n_days)
    mid_by_day = 100.0 * np.exp(np.cumsum(daily_ret))
    mid = mid_by_day[day]
    # half-spread in bp: 60 bp on a 100k trade, decaying as size^-0.35, floored at 5 bp
    half_bp = np.maximum(60.0 * (size / 1e5) ** -0.35, 5.0)
    side = rng.choice([-1.0, 1.0], n)
    price = mid * (1.0 + side * half_bp / 1e4)
    return Tape(day=day, size=size, price=price, mid=mid, side=side)


def apply_cap(size: np.ndarray, cap: float) -> np.ndarray:
    """What TRACE disseminates: the size, or the cap, whichever is smaller."""
    if cap <= 0:
        raise ValueError("cap must be positive")
    return np.minimum(size, cap)


# --------------------------------------------------------------------------- censoring
def censoring_report(tape: Tape, cap: float) -> dict[str, float]:
    """Everything the cap changes about the tape's summary statistics."""
    s, reported = tape.size, apply_cap(tape.size, cap)
    capped = s > cap
    vwap_true = float(np.sum(tape.price * s) / np.sum(s))
    vwap_rep = float(np.sum(tape.price * reported) / np.sum(reported))
    return {
        "cap": cap,
        "n_trades": float(len(s)),
        "capped_trades_pct": float(capped.mean() * 100.0),
        "true_volume": float(s.sum()),
        "reported_volume": float(reported.sum()),
        "hidden_volume_pct": float((1.0 - reported.sum() / s.sum()) * 100.0),
        "true_mean_size": float(s.mean()),
        "reported_mean_size": float(reported.mean()),
        "mean_size_error_pct": float((reported.mean() / s.mean() - 1.0) * 100.0),
        "true_median_size": float(np.median(s)),
        "reported_median_size": float(np.median(reported)),
        "vwap_true": vwap_true,
        "vwap_reported": vwap_rep,
        "vwap_error_bp": (vwap_rep - vwap_true) / vwap_true * 1e4,
    }


# --------------------------------------------------------------------------- Amihud
def amihud(tape: Tape, size: np.ndarray | None = None, scale: float = 1e6) -> float:
    """Amihud-style illiquidity: mean over days of |daily return| / daily dollar volume.

    `size` defaults to the TRUE size; pass the capped size to get what TRACE would give you.
    Dollar volume is size x price / 100, scaled to `scale` dollars so the number is readable.
    """
    q = tape.size if size is None else size
    dollars = q * tape.price / 100.0
    n_days = int(tape.day.max()) + 1
    vol_by_day = np.bincount(tape.day, weights=dollars, minlength=n_days)
    px_by_day = np.bincount(tape.day, weights=tape.mid, minlength=n_days) / np.bincount(
        tape.day, minlength=n_days)
    ret = np.abs(np.diff(px_by_day) / px_by_day[:-1])
    illiq = ret / (vol_by_day[1:] / scale)
    return float(np.mean(illiq))


def amihud_bias(tape: Tape, caps: Sequence[float] = (CAP_INVESTMENT_GRADE, CAP_HIGH_YIELD)
                ) -> list[dict[str, float]]:
    """The same tape under each cap: how much more illiquid the cap alone makes it look."""
    true_illiq = amihud(tape)
    out = []
    for cap in caps:
        rep = amihud(tape, apply_cap(tape.size, cap))
        hidden = 1.0 - apply_cap(tape.size, cap).sum() / tape.size.sum()
        out.append({"cap": cap, "amihud_true": true_illiq, "amihud_reported": rep,
                    "overstatement_pct": (rep / true_illiq - 1.0) * 100.0,
                    "hidden_volume_pct": hidden * 100.0,
                    "naive_guess_pct": (1.0 / (1.0 - hidden) - 1.0) * 100.0})
    return out


def cross_sectional_distortion(tape: Tape) -> dict[str, float]:
    """TWO identical bonds, one investment grade and one high yield, on the SAME tape.

    Their true liquidity is identical by construction, so the ratio of their true Amihud
    measures is exactly 1. What a TRACE-based screen reports is not 1, and the gap is the cap.
    """
    ig = amihud(tape, apply_cap(tape.size, CAP_INVESTMENT_GRADE))
    hy = amihud(tape, apply_cap(tape.size, CAP_HIGH_YIELD))
    return {"amihud_true_ratio": 1.0, "amihud_reported_ratio": hy / ig,
            "hy_looks_more_illiquid_pct": (hy / ig - 1.0) * 100.0}


# --------------------------------------------------------------------------- the fix
def censored_lognormal_mle(reported: np.ndarray, cap: float) -> dict[str, float]:
    """Recover the size distribution from RIGHT-CENSORED data, the way Tobit does.

    Uncensored observations contribute log f(x); every "5MM+" print contributes log(1 - F(cap)),
    which is the information a capped print actually carries. Returns the fitted (mu, sigma) and
    the implied mean size, which is the quantity a naive average of the tape cannot recover.
    """
    x = np.asarray(reported, dtype=float)
    if cap <= 0 or np.any(x <= 0):
        raise ValueError("sizes and cap must be positive")
    obs = x < cap
    lx = np.log(x[obs])
    lc = math.log(cap)
    n_cens = int((~obs).sum())

    def nll(theta: np.ndarray) -> float:
        mu, log_sd = float(theta[0]), float(theta[1])
        sd = math.exp(log_sd)
        ll = float(np.sum(norm.logpdf(lx, mu, sd) - lx))
        if n_cens:
            ll += n_cens * float(norm.logsf((lc - mu) / sd))
        return -ll

    start = np.array([float(lx.mean()), math.log(max(float(lx.std(ddof=1)), 1e-3))])
    res = minimize(nll, start, method="Nelder-Mead",
                   options={"xatol": 1e-10, "fatol": 1e-10, "maxiter": 5000})
    mu, sd = float(res.x[0]), math.exp(float(res.x[1]))
    return {"mu": mu, "sigma": sd, "mean_size": math.exp(mu + 0.5 * sd * sd),
            "n_censored": float(n_cens), "converged": float(bool(res.success))}


def recovery_report(tape: Tape, cap: float) -> dict[str, float]:
    """Naive average vs the censored MLE, against the truth the simulation knows."""
    reported = apply_cap(tape.size, cap)
    fit = censored_lognormal_mle(reported, cap)
    n = len(tape)
    true_total, naive_total = float(tape.size.sum()), float(reported.sum())
    mle_total = fit["mean_size"] * n
    return {"cap": cap, "true_mean": float(tape.size.mean()),
            "naive_mean": float(reported.mean()), "mle_mean": fit["mean_size"],
            "naive_error_pct": (reported.mean() / tape.size.mean() - 1.0) * 100.0,
            "mle_error_pct": (fit["mean_size"] / tape.size.mean() - 1.0) * 100.0,
            "true_total": true_total, "naive_total": naive_total, "mle_total": mle_total,
            "sigma_hat": fit["sigma"], "sigma_true": LOG_SIZE_SD}


# --------------------------------------------------------------------------- demo
if __name__ == "__main__":
    W = 96
    print("=" * W)
    print("CORPORATE BOND DATA AND TRACE -- the 15-minute window and the censored size")
    print("=" * W)

    print("\n1. FINRA REPORTING OUTER LIMITS (read at finra.org on 2026-09-09)")
    print(f"   {'security':<38}{'outer limit':<38}{'rule'}")
    for r in reporting_timeframes():
        print(f"   {r['security']:<38}{r['limit']:<38}{r['rule']}")
    print("   Regulatory Notice 25-17 (published 2025-12-04): FINRA is NOT moving forward with the")
    print("   one-minute proposal; the 15-minute outer limit is retained, effective 2026-06-08.")

    print("\n2. WHAT 15 MINUTES OF STALENESS IS WORTH (5% annualised price vol, 6.5h sessions)")
    print(f"   {'window':>10}{'sd of the unseen move':>26}{'vs 1 minute':>14}")
    for r in staleness():
        print(f"   {r['minutes']:>7.0f} min{r['sd_bp']:>22.2f} bp{r['vs_one_minute']:>13.2f}x")
    print("   A one-minute tape would have shown 3.87x less price uncertainty per print. It does")
    print("   not exist: assuming it does makes every event study around a print too confident.")

    tape = simulate_tape()
    print(f"\n3. THE DISSEMINATION CAPS CENSOR SIZE  (one seeded tape, {len(tape)} trades over 250 "
          f"days,")
    print("   the SAME trades under each cap, so the cap is the only thing that differs)")
    print(f"   {'cap':>12}{'printed':>10}{'trades capped':>16}{'volume hidden':>16}"
          f"{'mean size err':>16}{'VWAP err':>11}")
    reports = {}
    for spec in dissemination_caps():
        rep = censoring_report(tape, float(spec["cap"]))
        reports[spec["printed_as"]] = rep
        print(f"   {rep['cap'] / 1e6:>10.0f}MM{spec['printed_as']:>10}"
              f"{rep['capped_trades_pct']:>15.2f}%{rep['hidden_volume_pct']:>15.2f}%"
              f"{rep['mean_size_error_pct']:>15.2f}%{rep['vwap_error_bp']:>+9.2f} bp")
    ig = reports["5MM+"]
    print(f"   -> {ig['capped_trades_pct']:.2f}% of PRINTS hide {ig['hidden_volume_pct']:.2f}% of "
          f"the VOLUME at the investment-grade cap.")
    print(f"   -> the MEDIAN trade size survives exactly ("
          f"{ig['true_median_size']:,.0f} true vs {ig['reported_median_size']:,.0f} reported); "
          f"the MEAN does not.")

    print("\n4. AN AMIHUD RATIO IS BIASED UP -- BUT NOT BY THE VOLUME FRACTION")
    print(f"   {'cap':>12}{'true':>14}{'from TRACE':>14}{'overstated by':>16}"
          f"{'1/(1-hidden)':>15}")
    for r in amihud_bias(tape):
        print(f"   {r['cap'] / 1e6:>10.0f}MM{r['amihud_true']:>14.6f}{r['amihud_reported']:>14.6f}"
              f"{r['overstatement_pct']:>+15.2f}%{r['naive_guess_pct']:>+14.2f}%")
    print("   The direction is always UP and the size is not what the volume fraction suggests:")
    print("   Amihud averages |r|/V across days and is dominated by LOW-volume days, which are")
    print("   exactly the days with no capped print. Correcting it by 1/(1 - hidden) overshoots.")
    x = cross_sectional_distortion(tape)
    print(f"   Two bonds with IDENTICAL true liquidity, one investment grade and one high yield:")
    print(f"   true Amihud ratio {x['amihud_true_ratio']:.4f}, ratio from TRACE "
          f"{x['amihud_reported_ratio']:.4f} -- the high-yield name looks")
    print(f"   {x['hy_looks_more_illiquid_pct']:.2f}% more illiquid, entirely because its cap is "
          f"$1MM instead of $5MM.")

    print("\n5. THE FIX: TREAT '5MM+' AS A CENSORED OBSERVATION, NOT AS $5MM")
    print(f"   {'cap':>12}{'true mean':>14}{'naive mean':>14}{'MLE mean':>14}"
          f"{'naive err':>12}{'MLE err':>11}")
    for cap in (CAP_INVESTMENT_GRADE, CAP_HIGH_YIELD):
        r = recovery_report(tape, cap)
        print(f"   {cap / 1e6:>10.0f}MM{r['true_mean']:>14,.0f}{r['naive_mean']:>14,.0f}"
              f"{r['mle_mean']:>14,.0f}{r['naive_error_pct']:>+11.2f}%"
              f"{r['mle_error_pct']:>+10.2f}%")
    r = recovery_report(tape, CAP_HIGH_YIELD)
    print(f"   recovered sigma {r['sigma_hat']:.4f} against the true {r['sigma_true']:.4f}; "
          f"total volume {r['mle_total'] / 1e9:.3f}bn")
    print(f"   estimated against {r['true_total'] / 1e9:.3f}bn true and "
          f"{r['naive_total'] / 1e9:.3f}bn straight off the tape.")

    print("\n" + "=" * W)
    print("THE RULE: TRACE reporting is 15 MINUTES, not one, and disseminated size is a LOWER "
          "BOUND --")
    print("'5MM+' is a censored observation, so treat it like one or your volume statistics are "
          "wrong.")
    print("=" * W)
