"""fin-skills - a source-verified knowledge base of the Python quant-finance ecosystem, importable.

Two ways in:

    import fin_skills
    fin_skills.catalog()                          # every skill: name, plugin, description
    fin_skills.load("backtest-validation")        # that skill's SKILL.md text
    fin_skills.references("options-backtesting")  # {filename: text} for its references/
    fin_skills.find("survivorship")               # skills whose description mentions it

    from fin_skills.core.safe_asof import safe_asof             # the executable guards
    from fin_skills.core.assert_causal import assert_causal
    from fin_skills.futures_fx.fx_conventions import pip_size, carry_return

The `fin_skills.<namespace>` modules are generated by scripts/build_package.py from the
skill scripts under plugins/; the skills remain the source of truth. Namespaces follow the
plugins: core, libraries, china, asia, futures_fx, crypto, llm.

Every claim in the skill texts carries a verification date and a marker - see the README.
"""
from __future__ import annotations

import json
from importlib import resources
from typing import Iterable

__version__ = "0.1.0"
__all__ = ["catalog", "load", "references", "find", "names", "__version__"]


def _data():
    return resources.files(__name__) / "_skills"


def _index() -> dict:
    p = _data() / "index.json"
    if not p.is_file():
        raise RuntimeError("fin_skills/_skills/index.json is missing - run scripts/build_package.py")
    return json.loads(p.read_text(encoding="utf-8"))


def names() -> list[str]:
    """All skill names, sorted."""
    return sorted(p.name for p in _data().iterdir() if (p / "SKILL.md").is_file())


def catalog() -> list[dict]:
    """One entry per skill: name, plugin, description, and what it ships (from catalog/index.json)."""
    idx = _index()
    skills = idx.get("skills", idx)
    if isinstance(skills, dict):
        skills = [dict(name=k, **v) if isinstance(v, dict) else {"name": k} for k, v in skills.items()]
    return sorted(skills, key=lambda s: s.get("name", ""))


def load(name: str) -> str:
    """The SKILL.md text for one skill, e.g. fin_skills.load("backtest-validation")."""
    p = _data() / name / "SKILL.md"
    if not p.is_file():
        close = [n for n in names() if name.lower() in n]
        hint = f" - did you mean {close}?" if close else ""
        raise KeyError(f"no skill named {name!r}{hint}")
    return p.read_text(encoding="utf-8")


def references(name: str) -> dict[str, str]:
    """{filename: text} for a skill's references/ directory (empty dict if it has none)."""
    d = _data() / name / "references"
    if not d.is_dir():
        if not (_data() / name).is_dir():
            raise KeyError(f"no skill named {name!r}")
        return {}
    return {p.name: p.read_text(encoding="utf-8") for p in sorted(d.iterdir()) if p.name.endswith(".md")}


def find(*terms: str) -> list[str]:
    """Skill names whose SKILL.md mentions every term (case-insensitive)."""
    wanted: Iterable[str] = [t.lower() for t in terms]
    out = []
    for n in names():
        text = load(n).lower()
        if all(t in text for t in wanted):
            out.append(n)
    return out
