"""A seeded SYNTHETIC panel, generated on demand, so every example here runs with no key.

    from fin_skills.data import sample
    from fin_skills.api import check

    s = sample()                      # Bars + Fundamentals + Macro, one seeded world
    print(check(s.to_bundle()).summary())

**None of this is market data and none of it is any vendor's.** Every number is produced
by the generator below from `numpy.random.default_rng(SEED)`; nothing is downloaded,
nothing is read from disk, and no file ships in the wheel. That is not a stylistic choice.
FRED requires each user to bring their own key and forbids redistributing its
copyright-flagged series, Tiingo's Starter terms forbid retaining its data in "any
persistent or durable storage", akshare's documentation restricts its DATA to academic
research while the code is MIT, and Polygon prohibits non-display use - so a "sample
dataset" cut from any of them would be a redistribution none of those licences permits.
The synthetic panel is what an offline example can legally hold.

It says so on its face, in three places that survive being copied around:

  * every `Provenance.source` is `"synthetic"` and its `library_version` is
    `"synthetic-<SEED>"`, so a manifest row and a result card both read SYNTHETIC;
  * `Provenance.request` records `{"generator": "fin_skills.data.sample", "seed": ...}`,
    which is enough to reproduce the exact arrays;
  * `NOT_MARKET_DATA` is stamped into every `terms_url`, so a card that prints the terms
    prints the warning.

What the world contains, and why each piece is there:

    prices        `n_names` tickers over `years` business days, RAW and tick-aligned
    splits        two on one name, so `adjustment_check` has an event to anchor on
    dividends     quarterly cash on a second name, with the price ratio implied
    delistings    `n_dead` names that STOP - NaN after the last session, never dropped,
                  with a listings table that says when and why, so `survivorship_audit`
                  has both the confirmed shape and the panel to check it against
    fundamentals  quarterly revenue per entity with period_end, filed_at, acceptance_at
                  and available_at, one of which is a post-close filing that rolls to the
                  next session, plus ONE restatement so PIT and naive selection disagree
    macro         a quarterly series with THREE vintages of one observation, so
                  `Macro.as_of` has something to deduplicate

`sample()` returns the schema objects themselves, so `to_bundle()` works on the result
directly and every guard that reads prices, actions, listings or facts can run offline.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd

from fin_skills.data.convert import to_bundle
from fin_skills.data.provenance import Provenance
from fin_skills.data.provenance import make as make_provenance
from fin_skills.data.schema import (Adjustment, Bars, Fundamentals, Macro, stack_fields)

#: the one seed. Change it and every number below changes; it is recorded in Provenance.
SEED = 20260910

#: the source name every Provenance from this module carries
SOURCE = "synthetic"

#: stamped into terms_url so a result card that prints the terms prints the warning
NOT_MARKET_DATA = ("SYNTHETIC - generated by fin_skills.data.sample, not market data, "
                   "not any vendor's data, safe to redistribute")

TZ = "America/New_York"
CALENDAR = "XNYS"
START = "2016-01-04"


def _prov(kind: str, content: Any, seed: int, **request: Any) -> Provenance:
    """One Provenance whose every field says SYNTHETIC out loud."""
    return make_provenance(
        SOURCE, library_version=f"synthetic-{seed}",
        request={"generator": "fin_skills.data.sample", "kind": kind, "seed": int(seed),
                 **request},
        content=content, terms_url=NOT_MARKET_DATA,
        # True because it is this repository's own output, generated from a seed - the one
        # dataset in this layer that CAN be passed on
        redistributable=True)


# ------------------------------------------------------------------------------- prices
def bars(*, n_names: int = 8, years: int = 6, n_dead: int = 2, seed: int = SEED,
         adjustment: Adjustment = Adjustment.RAW) -> Bars:
    """A RAW, tick-aligned panel with splits, dividends and real delistings.

    Prices are rounded to the cent because tick alignment is what
    `adjustment_check.detect_convention` reads: real quotes are struck in cents, and
    dividing one by a split ratio produces a value that is not.
    """
    if n_dead >= n_names:
        raise ValueError("n_dead must leave at least one name alive")
    rng = np.random.default_rng(seed)
    idx = pd.bdate_range(START, periods=252 * int(years), tz=TZ)
    names = [f"SYN{i:02d}" for i in range(int(n_names))]

    value = 40.0 * np.exp(np.cumsum(rng.normal(0.0003, 0.015, (len(idx), len(names))),
                                    axis=0))

    # --- two splits on SYN00, so a convention check has an event to anchor on
    split_dates = [idx[int(len(idx) * 0.20)], idx[int(len(idx) * 0.55)]]
    acts = [{"date": d, "ratio": r, "kind": "split", "ticker": names[0]}
            for d, r in zip(split_dates, (4.0, 2.0))]
    factor = np.ones(len(idx))
    for d, r in zip(split_dates, (4.0, 2.0)):
        factor *= np.where(idx >= d, r, 1.0)
    value[:, 0] = value[:, 0] / factor            # the RAW quote takes the drop

    # --- quarterly cash dividends on SYN01, with the implied multiplicative price factor
    if len(names) > 1:
        div_dates = [t for t in idx[::63]][1:]
        col = 1
        for d in div_dates:
            pos = int(np.searchsorted(idx, d))
            if pos <= 0 or pos >= len(idx):
                continue
            prev = float(value[pos - 1, col])
            cash = round(prev * 0.004, 2)
            if cash <= 0:
                continue
            value[pos:, col] -= cash              # the raw quote drops on the ex-date
            acts.append({"date": d, "ratio": prev / (prev - cash), "kind": "dividend",
                         "ticker": names[col]})

    close = pd.DataFrame(np.round(value, 2), index=idx, columns=names)
    volume = pd.DataFrame(rng.integers(400_000, 9_000_000, close.shape).astype("int64"),
                          index=idx, columns=names)

    # --- the dead names STOP. NaN after the last session, never dropped, never filled.
    dead_at: dict[str, pd.Timestamp] = {}
    for i, t in enumerate(names[len(names) - int(n_dead):] if n_dead else []):
        pos = int(len(idx) * (0.35 + 0.45 * (i + 0.5) / max(int(n_dead), 1)))
        dead_at[t] = idx[pos]
        close.loc[close.index > idx[pos], t] = np.nan
        volume.loc[volume.index > idx[pos], t] = 0

    listings = pd.DataFrame([
        {"ticker": t, "start_date": idx[0].tz_localize(None),
         "end_date": dead_at[t].tz_localize(None) if t in dead_at else pd.NaT,
         "reason": "delisted" if t in dead_at else ""}
        for t in names])

    frame = stack_fields({"open": np.round(close * 0.996, 2),
                          "high": np.round(close * 1.009, 2),
                          "low": np.round(close * 0.991, 2),
                          "close": close,
                          "volume": volume.astype("int64")})
    actions = pd.DataFrame(acts).sort_values("date").reset_index(drop=True)
    raw = Bars(frame=frame, adjustment=Adjustment.RAW, calendar=CALENDAR, tz=TZ,
               interval="1d", bar_label="close", currency="USD",
               provenance=_prov("bars", frame, seed, n_names=int(n_names),
                                years=int(years), n_dead=int(n_dead),
                                adjustment=Adjustment.RAW.value),
               actions=actions, listings=listings, half_open=True)
    return raw if adjustment is Adjustment.RAW else raw.readjust(adjustment)


# ------------------------------------------------------------------------- fundamentals
#: the one period whose value is later restated, and the decision date that separates the
#: point-in-time answer from the naive one
RESTATED_PERIOD_END = pd.Timestamp("2021-09-30")
RESTATEMENT_AS_OF = pd.Timestamp("2021-12-31")


def fundamentals(*, n_entities: int = 3, quarters: int = 16,
                 seed: int = SEED) -> Fundamentals:
    """Quarterly revenue with all four dates, and exactly one restatement.

    `available_at` is the only date a guard is allowed to use, and it is not `filed_at`:
    the first filing of every entity is accepted after the 16:00 close, so it was first
    tradeable on the NEXT session. Keeping all four dates is what lets a test show that
    using the wrong one leaks.
    """
    rng = np.random.default_rng(seed + 1)
    entities = [f"000000{i}" for i in range(int(n_entities))]
    ends = pd.date_range("2019-03-31", periods=int(quarters), freq="QE")

    rows: list[dict] = []
    for e_i, eid in enumerate(entities):
        level = 5.0e8 * (1.0 + e_i)
        for q_i, pe in enumerate(ends):
            value = float(np.round(level * (1.0 + 0.02 * q_i)
                                   * (1.0 + rng.normal(0.0, 0.03)), 0))
            filed = pe + pd.Timedelta(days=34)
            # the first quarter of every entity is accepted after the close, so it is
            # knowable on the NEXT business day - the one-day gap that a filed_at join
            # silently swallows
            post_close = q_i == 0
            acceptance = filed + pd.Timedelta(hours=21 if post_close else 14,
                                              minutes=5 if post_close else 30)
            available = (filed + pd.offsets.BDay(1)) if post_close else filed
            rows.append(dict(entity_id=eid, entity_scheme="cik",
                             period_start=(pe - pd.offsets.QuarterBegin(startingMonth=1)),
                             period_end=pe, filed_at=filed,
                             acceptance_at=acceptance.tz_localize("UTC"),
                             available_at=available, form="10-Q",
                             accn=f"{eid}-{pe.year % 100:02d}-{q_i:03d}",
                             tag="Revenues", value=value, unit="USD",
                             is_amendment=False))
            # ...and ONE of them is restated downward in an amendment, months later, so a
            # PIT selection and drop_duplicates(keep="last") pick different numbers
            if eid == entities[0] and pe == RESTATED_PERIOD_END:
                amended = filed + pd.Timedelta(days=120)
                rows.append(dict(entity_id=eid, entity_scheme="cik",
                                 period_start=(pe
                                               - pd.offsets.QuarterBegin(startingMonth=1)),
                                 period_end=pe, filed_at=amended,
                                 acceptance_at=(amended
                                                + pd.Timedelta(hours=14)).tz_localize("UTC"),
                                 available_at=amended, form="10-Q/A",
                                 accn=f"{eid}-{amended.year % 100:02d}-900",
                                 tag="Revenues", value=float(np.round(value * 0.94, 0)),
                                 unit="USD", is_amendment=True))

    frame = pd.DataFrame(rows)
    return Fundamentals(frame=frame, tz_of_record="UTC",
                        provenance=_prov("fundamentals", frame, seed,
                                         n_entities=int(n_entities),
                                         quarters=int(quarters)))


# -------------------------------------------------------------------------------- macro
#: the observation that carries three vintages, so `Macro.as_of` has a real dedupe to do
VINTAGE_OBS_DATE = pd.Timestamp("2019-10-01")


def macro(*, series_id: str = "SYNGDP", quarters: int = 20,
          seed: int = SEED) -> Macro:
    """One quarterly series where the published number is revised after the fact.

    Every observation is published with a lag and then revised once; one observation is
    revised twice, which is the shape FRED's own documented GDP example has and the shape
    that makes backtesting the CURRENT series a look-ahead.
    """
    rng = np.random.default_rng(seed + 2)
    obs = pd.date_range("2019-01-01", periods=int(quarters), freq="QS")
    rows: list[dict] = []
    level = 17_000.0
    for d in obs:
        level *= 1.0 + rng.normal(0.005, 0.004)
        first = float(np.round(level, 1))
        publish = d + pd.Timedelta(days=120)
        rows.append(dict(series_id=series_id, obs_date=d, value=first,
                         realtime_start=publish, realtime_end=pd.NaT, sa_flag="SAAR"))
        rows.append(dict(series_id=series_id, obs_date=d,
                         value=float(np.round(first * (1.0 + rng.normal(0.0, 0.0015)), 1)),
                         realtime_start=publish + pd.Timedelta(days=29),
                         realtime_end=pd.NaT, sa_flag="SAAR"))
        if d == VINTAGE_OBS_DATE:
            rows.append(dict(series_id=series_id, obs_date=d,
                             value=float(np.round(first * 0.999, 1)),
                             realtime_start=publish + pd.Timedelta(days=57),
                             realtime_end=pd.NaT, sa_flag="SAAR"))
    frame = pd.DataFrame(rows)
    return Macro(frame=frame, provenance=_prov("macro", frame, seed,
                                               series_id=series_id,
                                               quarters=int(quarters)))


# ------------------------------------------------------------------------------- the set
@dataclass(frozen=True)
class Sample:
    """One seeded world: the three schema objects, plus the seed that produced them."""

    bars: Bars
    fundamentals: Fundamentals
    macro: Macro
    seed: int

    def to_bundle(self, *, ticker: str | None = None, as_of: Any = None, **extra: Any):
        """The `api.Bundle` every data-only guard reads - offline, from the whole set."""
        return to_bundle(self.bars, self.fundamentals, self.macro,
                         ticker=ticker, as_of=as_of, **extra)

    @property
    def split_ticker(self) -> str:
        """The name that has SPLITS - the anchor `adjustment_check` reads."""
        acts = self.bars.actions
        splits = acts[acts["kind"] == "split"]
        return str((splits if len(splits) else acts)["ticker"].iloc[0])

    @property
    def dividend_ticker(self) -> str:
        """The name that pays cash dividends, whose ratio is implied, not quoted."""
        acts = self.bars.actions
        divs = acts[acts["kind"] == "dividend"]
        return str((divs if len(divs) else acts)["ticker"].iloc[0])

    @property
    def dead_tickers(self) -> list[str]:
        """The names that stop trading inside the sample."""
        lt = self.bars.listings
        return sorted(lt.loc[lt["end_date"].notna(), "ticker"].astype(str))

    def describe(self) -> str:
        b, f, m = self.bars, self.fundamentals, self.macro
        return "\n".join([
            f"SYNTHETIC sample, seed {self.seed} - {NOT_MARKET_DATA}",
            f"  bars         : {b.frame.shape[0]} sessions x {len(b.tickers)} names, "
            f"{b.adjustment.value}, {b.calendar}, {len(b.actions)} corporate action(s), "
            f"{len(self.dead_tickers)} delisting(s)",
            f"  fundamentals : {len(f.frame)} rows, {f.frame['entity_id'].nunique()} "
            f"entities, {len(f.restatements())} restatement(s)",
            f"  macro        : {len(m.frame)} rows, {m.frame['obs_date'].nunique()} "
            f"observation dates, up to "
            f"{int(m.frame.groupby('obs_date').size().max())} vintages of one observation",
        ]).encode("ascii", "replace").decode("ascii")

    def __repr__(self) -> str:
        return (f"Sample(seed={self.seed}, bars={self.bars!r}, "
                f"fundamentals={len(self.fundamentals.frame)} rows, "
                f"macro={len(self.macro.frame)} rows)")


def sample(*, seed: int = SEED, n_names: int = 8, years: int = 6, n_dead: int = 2,
           adjustment: Adjustment | str = Adjustment.ANCHORED_START,
           n_entities: int = 3, quarters: int = 16) -> Sample:
    """Generate the whole seeded world. Deterministic: same seed, same bytes.

    The default convention is ANCHORED_START - anchored at the start, so history is never
    rewritten - because that is the one on which the data-only guards run GREEN, and an
    example is supposed to start from a clean run. `sample(adjustment=Adjustment.RAW)`
    hands back the same world with the split still a jump in the series, which is what
    `adjustment_check` exists to catch: use that when the example is about the trap.
    """
    adj = adjustment if isinstance(adjustment, Adjustment) else Adjustment(adjustment)
    return Sample(bars=bars(n_names=n_names, years=years, n_dead=n_dead, seed=seed,
                            adjustment=adj),
                  fundamentals=fundamentals(n_entities=n_entities, quarters=quarters,
                                            seed=seed),
                  macro=macro(quarters=quarters + 4, seed=seed),
                  seed=int(seed))


__all__ = ["CALENDAR", "NOT_MARKET_DATA", "RESTATED_PERIOD_END", "RESTATEMENT_AS_OF",
           "SEED", "SOURCE", "START", "Sample", "TZ", "VINTAGE_OBS_DATE", "bars",
           "fundamentals", "macro", "sample"]
