# GENERATED by scripts/build_package.py from plugins/fin-data/skills/choosing-a-data-vendor/scripts/vendor_decision.py - do not edit here.
# Edit the skill script and rerun the generator; validate.py checks they match.
# Owning skill: choosing-a-data-vendor (fin_skills.load('choosing-a-data-vendor') returns its SKILL.md).

#!/usr/bin/env python3
"""Which of the eight adapters can serve a request - and how often the answer is none.

Every number in this skill's SKILL.md is printed by this script. It is deliberately
self-contained: it carries a dated SNAPSHOT of the three decisive flags per source, so it
runs on a bare install with no network and no vendor library, and it CROSS-CHECKS that
snapshot against `fin_skills.data.declare` when the generated package is importable, so
the copy cannot drift from the declarations it was taken from.

    python vendor_decision.py

The three flags, and why these three:

    includes_delisted   decides whether a result is an estimate or an UPPER BOUND. A
                        universe with no dead names in it cannot produce anything else.
    point_in_time       decides whether the source can answer "what was known at t?" - the
                        difference between a backtest and a demonstration that the past
                        was knowable in advance.
    redistribution      decides what you may do with what you fetched. It is a property of
                        the vendor's TERMS, not of the client library's SPDX licence, and
                        the two disagree for every free price source below.

Everything else - price, breadth, convenience, which Python client is nicest - is a
tiebreak between sources that have already survived those three.

No network, no vendor import, ASCII output, fixed data.
"""
from __future__ import annotations

from typing import Any

SEP = "=" * 78

#: One row per adapter in fin_skills.data, snapshotted 2026-09-10 from each Declaration.
#: `sources` names where the DECISIVE half of the row was verified. Kept here rather than
#: imported so the script runs standalone; `cross_check()` proves it still matches.
SNAPSHOT: dict[str, dict[str, Any]] = {
    "yfinance": dict(
        delisted=False, pit=False, redistribution="prohibited", key=False,
        cache="persist-ok", reachable=True, history=None,
        classes=("equity", "etf", "index", "fx", "futures"), markets=("US", "GLOBAL"),
        serves=("bars", "actions"),
        free="no key; no numeric rate limit published anywhere",
        source="legal.yahoo.com product-atos/apiforydn, 2026-09-09"),
    "akshare": dict(
        delisted=False, pit=False, redistribution="prohibited", key=False,
        cache="persist-ok", reachable=True, history=None,
        classes=("equity", "index", "macro"), markets=("CN",), serves=("bars",),
        free="no key; no published rate limit of any kind",
        source="akshare.akfamily.xyz/introduction.html, 2026-09-09"),
    "ccxt": dict(
        delisted=False, pit=False, redistribution="prohibited", key=False,
        cache="persist-ok", reachable=True, history=None,
        classes=("crypto",), markets=("CRYPTO",), serves=("bars",),
        free="per venue; rateLimit ms x endpoint cost, PER EXCHANGE INSTANCE",
        source="github.com/ccxt/ccxt#licence, 2026-09-09"),
    "fred": dict(
        delisted=False, pit=True, redistribution="attribution", key=True,
        cache="persist-ok", reachable=True, history=None,
        classes=("macro",), markets=("US", "GLOBAL"), serves=("macro",),
        free="free, own key required; two published shapes, 120/min and 2/s",
        source="fred.stlouisfed.org/docs/api/terms_of_use.html, 2026-09-09"),
    "edgar": dict(
        delisted=True, pit=True, redistribution="public-domain", key=False,
        cache="persist-ok", reachable=True, history=None,
        classes=("fundamentals",), markets=("US",), serves=("fundamentals",),
        free="free, no key; 10 requests/second regardless of machine count",
        source="sec.gov/about/privacy-information#security, 2026-09-09"),
    "tiingo": dict(
        delisted=False, pit=False, redistribution="prohibited", key=True,
        cache="no-persist", reachable=True, history=60.0,
        classes=("equity", "etf"), markets=("US", "CN"), serves=("bars", "actions"),
        free="Starter $0: 50/hr, 1,000/day, 500 unique SYMBOLS/mo, 1 GB/mo",
        source="tiingo.com/about/pricing and app.tiingo.com/tos, 2026-09-10"),
    "alphavantage": dict(
        delisted=False, pit=False, redistribution="prohibited", key=True,
        cache="persist-ok", reachable=True, history=0.4,
        classes=("equity", "etf"), markets=("US", "GLOBAL"),
        serves=("bars", "universe"),
        free="free key: 25 requests/DAY, and outputsize=compact is 100 data points",
        source="alphavantage.co/support and /documentation, 2026-09-10"),
    "stooq": dict(
        delisted=False, pit=False, redistribution="prohibited", key=False,
        cache="persist-ok", reachable=False, history=40.0,
        classes=("equity", "etf", "index", "fx", "futures", "macro"),
        markets=("US", "PL", "UK", "JP", "HK", "HU", "GLOBAL"), serves=("bars",),
        free="no key and no account - and blocked to scripts by a JS proof-of-work page",
        source="stooq.com/terms.html and stooq.com/db/h/, 2026-09-10"),
}

#: The requests a person actually arrives with. (label, filter kwargs)
REQUESTS: tuple[tuple[str, dict], ...] = (
    ("US equity daily bars, 10 years, free",
     dict(cls="equity", market="US", method="bars", years=10.0)),
    ("...and DELISTED names required",
     dict(cls="equity", market="US", method="bars", years=10.0, delisted=True)),
    ("...and POINT-IN-TIME required",
     dict(cls="equity", market="US", method="bars", years=10.0, pit=True)),
    ("...and the result will be REDISTRIBUTED",
     dict(cls="equity", market="US", method="bars", years=10.0, redistribute=True)),
    ("US equity daily bars, no API key at all",
     dict(cls="equity", market="US", method="bars", years=10.0, key_ok=False)),
    ("Crypto OHLCV, no key",
     dict(cls="crypto", market="CRYPTO", method="bars", years=1.0, key_ok=False)),
    ("US macro, point-in-time vintages",
     dict(cls="macro", market="US", method="macro", years=10.0, pit=True)),
    ("US filings, point-in-time and delisted",
     dict(cls="fundamentals", market="US", method="fundamentals", years=10.0,
          pit=True, delisted=True)),
)


def serves(row: dict, *, cls: str, market: str, method: str, years: float = 1.0,
           delisted: bool = False, pit: bool = False, redistribute: bool = False,
           store: bool = False, key_ok: bool = True) -> str:
    """"" if the source serves the request, else the flag that refuses it."""
    if method not in row["serves"]:
        return "method"
    if cls not in row["classes"]:
        return "asset_class"
    if market not in row["markets"]:
        return "market"
    if delisted and not row["delisted"]:
        return "delisted"
    if pit and not row["pit"]:
        return "point_in_time"
    if redistribute and row["redistribution"] == "prohibited":
        return "redistribution"
    if store and row["cache"] == "no-persist":
        return "cache"
    if not key_ok and row["key"]:
        return "key"
    if not row["reachable"]:
        return "unreachable"
    if row["history"] is not None and years > row["history"]:
        return "history"
    return ""


def answer(**kw) -> tuple[list[str], dict[str, str]]:
    """(sources that serve it, {source: refusing flag})."""
    ok, refused = [], {}
    for name, row in sorted(SNAPSHOT.items()):
        flag = serves(row, **kw)
        if flag:
            refused[name] = flag
        else:
            ok.append(name)
    return ok, refused


def cross_check() -> dict | None:
    """Compare the snapshot above against the live Declarations, field by field.

    Returns None when the generated package is not importable, so this script still runs
    on a bare install; returns {"checked": n, "drift": [...]} otherwise.
    """
    try:
        from fin_skills.data import declare                            # noqa: PLC0415
        from fin_skills.data.advise import COVERAGE                    # noqa: PLC0415
    except ImportError:
        return None
    drift: list[str] = []
    live = {d.name: d for d in declare.declarations()}
    if set(live) != set(SNAPSHOT):
        drift.append(f"registry has {sorted(set(live) ^ set(SNAPSHOT))} that the "
                     f"snapshot does not, or the reverse")
    for name, row in sorted(SNAPSHOT.items()):
        d = live.get(name)
        if d is None:
            continue
        for label, mine, theirs in (
                ("delisted", row["delisted"], d.includes_delisted),
                ("pit", row["pit"], d.point_in_time),
                ("redistribution", row["redistribution"], d.redistribution),
                ("key", row["key"], d.requires_key),
                ("cache", row["cache"], d.cache_policy)):
            if mine != theirs:
                drift.append(f"{name}.{label}: snapshot {mine!r} != declaration {theirs!r}")
        cov = COVERAGE.get(name)
        if cov is None:
            continue
        for label, mine, theirs in (
                ("classes", set(row["classes"]), set(cov.asset_classes)),
                ("markets", set(row["markets"]), set(cov.markets)),
                ("serves", set(row["serves"]), set(cov.serves)),
                ("history", row["history"], cov.max_history_years),
                ("reachable", row["reachable"], cov.reachable)):
            if mine != theirs:
                drift.append(f"{name}.{label}: snapshot {mine!r} != coverage {theirs!r}")
    return {"checked": len(SNAPSHOT), "drift": drift}


def rule(title: str) -> None:
    print("\n" + title)
    print(SEP)


def main() -> None:
    print("WHICH SOURCE CAN SERVE THIS? - eight adapters, snapshotted 2026-09-10")
    print(SEP)

    rule("1. THE THREE FLAGS, PER SOURCE")
    print(f"  {'source':<14}{'delisted':>9}{'PIT':>6}{'redistribution':>16}"
          f"{'key':>6}{'cache':>12}{'reachable':>11}")
    print("  " + "-" * 74)
    for name, row in sorted(SNAPSHOT.items()):
        print(f"  {name:<14}{str(row['delisted']):>9}{str(row['pit']):>6}"
              f"{row['redistribution']:>16}{('yes' if row['key'] else 'no'):>6}"
              f"{row['cache']:>12}{str(row['reachable']):>11}")
    n = len(SNAPSHOT)
    n_delisted = sum(1 for r in SNAPSHOT.values() if r["delisted"])
    n_pit = sum(1 for r in SNAPSHOT.values() if r["pit"])
    n_redis = sum(1 for r in SNAPSHOT.values() if r["redistribution"] != "prohibited")
    n_bars = sum(1 for r in SNAPSHOT.values() if "bars" in r["serves"])
    bars_delisted = sum(1 for r in SNAPSHOT.values()
                        if "bars" in r["serves"] and r["delisted"])
    print(f"\n  of {n} sources: {n_delisted} include delisted names, {n_pit} are "
          f"point-in-time,")
    print(f"  {n_redis} allow any redistribution at all.")
    print(f"  of the {n_bars} that serve PRICE BARS, {bars_delisted} include delisted "
          f"names.")

    rule("2. WHAT EACH REQUEST RESOLVES TO")
    for label, kw in REQUESTS:
        ok, refused = answer(**kw)
        verdict = ", ".join(ok) if ok else "NOTHING"
        print(f"  {label:<44} -> {verdict}")
        if not ok:
            flags: dict[str, int] = {}
            for f in refused.values():
                flags[f] = flags.get(f, 0) + 1
            named = ", ".join(f"{k} x{v}" for k, v in sorted(flags.items(),
                                                            key=lambda kv: -kv[1]))
            print(f"  {'':<44}    refused on: {named}")

    rule("3. THE ONE THAT MATTERS: DELISTED US EQUITY BARS")
    ok, refused = answer(cls="equity", market="US", method="bars", years=10.0,
                         delisted=True)
    on_flag = sorted(k for k, v in refused.items() if v == "delisted")
    print(f"  sources that serve it : {len(ok)}")
    print(f"  refused on includes_delisted=False: {len(on_flag)} - {', '.join(on_flag)}")
    print("  Every one of those returns TODAY's names. A universe built from any of them")
    print("  has no dead companies in it, so every backtest on it is an UPPER BOUND.")
    print("\n  What IS free, and what it does not fix:")
    print("    alphavantage LISTING_STATUS names active OR delisted US stocks and ETFs as")
    print("    of any date after 2010-01-01 - the MEMBERSHIP half. It does not price them.")
    print("    edgar keeps the filings of companies that died, so a FUNDAMENTALS study can")
    print("    be survivorship-free even when the price panel cannot be.")
    print("\n  What costs money (checked at each vendor's own page on 2026-09-10):")
    print("    EODHD ALL-IN-ONE, $99.99/month - the first tier carrying 'Delisted Data'")
    print("    Norgate US Stocks Platinum/Diamond - 'Delisted securities' plus 'Historical")
    print("      index constituents', the only tiers the page labels 'Suitable for")
    print("      backtesting'; Silver and Gold are current-listed only")

    rule("4. SNAPSHOT vs THE LIVE DECLARATIONS")
    xc = cross_check()
    if xc is None:
        print("  (fin_skills is not importable here, so the cross-check is skipped and")
        print("   the table above is the dated snapshot only.)")
    else:
        print(f"  {xc['checked']} source(s) compared against fin_skills.data.declare")
        if xc["drift"]:
            for d in xc["drift"]:
                print(f"    DRIFT: {d}")
        else:
            print("  no drift: every flag above still matches the declaration it came from")

    rule("TAKEAWAY")
    print("  Three flags decide it, and two of them are decided by a licence rather than")
    print("  by an API. Run the filters BEFORE choosing a library, because no amount of")
    print("  code fixes a source that does not contain the dead names, cannot say what was")
    print("  known at t, or may not be passed on. When the answer is NOTHING, the honest")
    print("  next step is to buy the data or to label the result an upper bound - never to")
    print("  quietly accept the closest thing that returns a DataFrame.")


if __name__ == "__main__":
    main()
