# GENERATED by scripts/build_package.py from plugins/fin-china/skills/china-trading-stack/scripts/kol_credibility_registry.py - do not edit here.
# Edit the skill script and rerun the generator; validate.py checks they match.
# Owning skill: china-trading-stack (fin_skills.load('china-trading-stack') returns its SKILL.md).

"""KOL (Big V) Credibility Registry & Bayesian Track-Record Weighting Engine.

Why this exists:
1. Follower count != Predictive accuracy. Empirical audit of 1,445 active Xueqiu authors across
   182 core equities (2018-2026) proves the overall social media 5-day win rate is 48.79% (coin flip).
2. Several mega-influencers with 100,000 to 425,000+ followers exhibit <40% win rates and negative
   alpha because they systematically chase FOMO tops and capitulate at panic bottoms.
3. Conversely, a small cohort of deep-research KOLs consistently achieves >68% 5-day directional win
   rates and positive payoff ratios.
4. Financial media accounts (e.g. 财联社, 每日经济新闻, 7X24快讯) average 46.98% directional win rate
   because news reports backward-looking facts; they must be used for event heat, never directional alpha.

This module provides:
- Point-in-Time KOL Credibility Lookup across 6 empirical tiers.
- Automatic loading of full `XUEQIU_KOL_ALPHA_PROFILES.csv` (1,445 profiles) with standalone embedded fallback.
- Dynamic Signal Weighting & Contrarian Inversion:
  * TIER_0_ELITE_KOL:          Weight = +3.0x (Core Alpha Amplifier)
  * TIER_1_CORE_ALPHA:         Weight = +2.5x (High-Conviction Researcher)
  * TIER_2_SOLID_RESEARCHER:   Weight = +1.5x (Solid Fundamental Analyst)
  * TIER_MEDIA_AGGREGATOR:     Weight =  0.0x directional (Heat/Catalyst only)
  * TIER_NEUTRAL_RETAIL:       Weight = +0.2x (Low-weight baseline)
  * TIER_CONTRARIAN_INDICATOR: Weight = -1.5x (Inverted Contrarian Signal - FOMO top / panic bottom indicator)
"""
from __future__ import annotations

import csv
import logging
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger("kol_credibility_registry")

# Tier Directional Multipliers
TIER_WEIGHT_MAP = {
    "TIER_0_ELITE_KOL": 3.0,
    "TIER_1_CORE_ALPHA": 2.5,
    "TIER_2_SOLID_RESEARCHER": 1.5,
    "TIER_MEDIA_AGGREGATOR": 0.0,       # Zero directional weight (heat/volume only)
    "TIER_NEUTRAL_RETAIL": 0.2,         # Baseline retail noise discount
    "TIER_CONTRARIAN_INDICATOR": -1.5,  # Negative weight: flips bullish FOMO into bearish warning!
}

# Embedded Standalone Snapshot (Top verified profiles from empirical 2018-2026 audit)
EMBEDDED_KOL_PROFILES = {
    # Top Elite & Core Alpha Whitelist (Win rate > 68%, Bayesian > 65%)
    "阿尔法工场": {"tier": "TIER_0_ELITE_KOL", "fans": 47707, "calls": 12, "win_rate_5d": 0.917, "bayesian_wr": 0.794, "mean_ret_5d": 0.0639, "payoff": 5.56},
    "冰冻三尺一": {"tier": "TIER_0_ELITE_KOL", "fans": 90341, "calls": 15, "win_rate_5d": 0.867, "bayesian_wr": 0.775, "mean_ret_5d": 0.0382, "payoff": 0.61},
    "雪球调研团": {"tier": "TIER_0_ELITE_KOL", "fans": 273671, "calls": 11, "win_rate_5d": 0.818, "bayesian_wr": 0.719, "mean_ret_5d": 0.0676, "payoff": 3.71},
    "宗哥投资": {"tier": "TIER_0_ELITE_KOL", "fans": 55645, "calls": 9, "win_rate_5d": 0.778, "bayesian_wr": 0.679, "mean_ret_5d": 0.0161, "payoff": 3.81},
    "马毛": {"tier": "TIER_0_ELITE_KOL", "fans": 80450, "calls": 8, "win_rate_5d": 0.750, "bayesian_wr": 0.654, "mean_ret_5d": 0.0343, "payoff": 1.77},
    "价投傻鱼": {"tier": "TIER_1_CORE_ALPHA", "fans": 10808, "calls": 24, "win_rate_5d": 0.708, "bayesian_wr": 0.672, "mean_ret_5d": 0.0565, "payoff": 4.35},
    "半瓶子老酒": {"tier": "TIER_1_CORE_ALPHA", "fans": 13907, "calls": 35, "win_rate_5d": 0.686, "bayesian_wr": 0.662, "mean_ret_5d": 0.0287, "payoff": 1.58},
    "浪里掌帆人": {"tier": "TIER_1_CORE_ALPHA", "fans": 17383, "calls": 26, "win_rate_5d": 0.692, "bayesian_wr": 0.661, "mean_ret_5d": 0.0257, "payoff": 2.08},
    "必有一得": {"tier": "TIER_1_CORE_ALPHA", "fans": 11203, "calls": 18, "win_rate_5d": 0.778, "bayesian_wr": 0.717, "mean_ret_5d": 0.0148, "payoff": 1.40},
    "知德说": {"tier": "TIER_1_CORE_ALPHA", "fans": 46605, "calls": 9, "win_rate_5d": 0.778, "bayesian_wr": 0.679, "mean_ret_5d": 0.0300, "payoff": 9.51},
    "拥抱大时代": {"tier": "TIER_1_CORE_ALPHA", "fans": 23699, "calls": 9, "win_rate_5d": 0.778, "bayesian_wr": 0.679, "mean_ret_5d": 0.0417, "payoff": 2.07},

    # Financial Media Aggregators (High follower count, ~47% coin-flip directional win rate)
    "每日经济新闻": {"tier": "TIER_MEDIA_AGGREGATOR", "fans": 129789, "calls": 354, "win_rate_5d": 0.517, "bayesian_wr": 0.517, "mean_ret_5d": 0.0034, "payoff": 1.02},
    "证券之星财经": {"tier": "TIER_MEDIA_AGGREGATOR", "fans": 97548, "calls": 261, "win_rate_5d": 0.548, "bayesian_wr": 0.546, "mean_ret_5d": 0.0065, "payoff": 1.05},
    "7X24快讯": {"tier": "TIER_MEDIA_AGGREGATOR", "fans": 574163, "calls": 151, "win_rate_5d": 0.470, "bayesian_wr": 0.471, "mean_ret_5d": -0.0050, "payoff": 0.92},
    "财联社": {"tier": "TIER_MEDIA_AGGREGATOR", "fans": 155620, "calls": 108, "win_rate_5d": 0.426, "bayesian_wr": 0.430, "mean_ret_5d": -0.0066, "payoff": 0.88},
    "新浪财经": {"tier": "TIER_MEDIA_AGGREGATOR", "fans": 24478, "calls": 95, "win_rate_5d": 0.484, "bayesian_wr": 0.485, "mean_ret_5d": -0.0021, "payoff": 0.95},

    # Verified Contrarian Indicators / 反向明灯 (High followers, chronic FOMO top buyers <=40% win rate)
    "钟华守正出奇": {"tier": "TIER_CONTRARIAN_INDICATOR", "fans": 425254, "calls": 20, "win_rate_5d": 0.400, "bayesian_wr": 0.420, "mean_ret_5d": -0.0133, "payoff": 0.64},
    "朱酒": {"tier": "TIER_CONTRARIAN_INDICATOR", "fans": 404287, "calls": 17, "win_rate_5d": 0.353, "bayesian_wr": 0.388, "mean_ret_5d": -0.0150, "payoff": 0.43},
    "青侨阳光": {"tier": "TIER_CONTRARIAN_INDICATOR", "fans": 378862, "calls": 15, "win_rate_5d": 0.133, "bayesian_wr": 0.256, "mean_ret_5d": -0.0314, "payoff": 0.69},
    "二马由之": {"tier": "TIER_CONTRARIAN_INDICATOR", "fans": 278202, "calls": 14, "win_rate_5d": 0.286, "bayesian_wr": 0.358, "mean_ret_5d": -0.0181, "payoff": 0.39},
    "ericwarn丁宁": {"tier": "TIER_CONTRARIAN_INDICATOR", "fans": 256643, "calls": 13, "win_rate_5d": 0.308, "bayesian_wr": 0.375, "mean_ret_5d": -0.0184, "payoff": 0.61},
    "鑫鑫-投资": {"tier": "TIER_CONTRARIAN_INDICATOR", "fans": 222823, "calls": 40, "win_rate_5d": 0.200, "bayesian_wr": 0.250, "mean_ret_5d": -0.0308, "payoff": 0.47},
    "价值事务所": {"tier": "TIER_CONTRARIAN_INDICATOR", "fans": 198687, "calls": 18, "win_rate_5d": 0.389, "bayesian_wr": 0.415, "mean_ret_5d": -0.0046, "payoff": 0.99},
    "东先生": {"tier": "TIER_CONTRARIAN_INDICATOR", "fans": 150267, "calls": 10, "win_rate_5d": 0.400, "bayesian_wr": 0.433, "mean_ret_5d": -0.0284, "payoff": 0.52},
    "冷小二": {"tier": "TIER_CONTRARIAN_INDICATOR", "fans": 105725, "calls": 8, "win_rate_5d": 0.375, "bayesian_wr": 0.423, "mean_ret_5d": -0.0191, "payoff": 0.58},
    "做个IT价投人": {"tier": "TIER_CONTRARIAN_INDICATOR", "fans": 97352, "calls": 20, "win_rate_5d": 0.400, "bayesian_wr": 0.420, "mean_ret_5d": -0.0033, "payoff": 0.79},
    "王增森": {"tier": "TIER_CONTRARIAN_INDICATOR", "fans": 47021, "calls": 8, "win_rate_5d": 0.375, "bayesian_wr": 0.423, "mean_ret_5d": -0.0796, "payoff": 0.31},

    # Overseas / Global Verified Alpha KOLs (StockTwits / US Equities / FinTwit)
    "THE_TRADE": {"tier": "TIER_0_ELITE_KOL", "fans": 1144, "calls": 128, "win_rate_5d": 0.898, "bayesian_wr": 0.875, "mean_ret_5d": 0.0245, "payoff": 1.95},
    "TheProfitPhantom": {"tier": "TIER_0_ELITE_KOL", "fans": 5150, "calls": 30, "win_rate_5d": 1.000, "bayesian_wr": 0.895, "mean_ret_5d": 0.0347, "payoff": 3.47},
    "StockMaster617": {"tier": "TIER_0_ELITE_KOL", "fans": 201, "calls": 45, "win_rate_5d": 0.978, "bayesian_wr": 0.906, "mean_ret_5d": 0.1479, "payoff": 1.33},
    "HindenburgResearch": {"tier": "TIER_0_ELITE_KOL", "fans": 1200000, "calls": 25, "win_rate_5d": 0.840, "bayesian_wr": 0.760, "mean_ret_5d": 0.1250, "payoff": 4.20},
    "CitronResearch": {"tier": "TIER_1_CORE_ALPHA", "fans": 850000, "calls": 30, "win_rate_5d": 0.700, "bayesian_wr": 0.658, "mean_ret_5d": 0.0480, "payoff": 2.15},

    # Overseas Breaking News & Media Aggregators (Direction stripped, heat only)
    "DeItaone": {"tier": "TIER_MEDIA_AGGREGATOR", "fans": 890000, "calls": 500, "win_rate_5d": 0.502, "bayesian_wr": 0.502, "mean_ret_5d": 0.0010, "payoff": 1.01},
    "UnusualWhales": {"tier": "TIER_MEDIA_AGGREGATOR", "fans": 1950000, "calls": 420, "win_rate_5d": 0.510, "bayesian_wr": 0.510, "mean_ret_5d": 0.0015, "payoff": 1.03},
    "ZeroHedge": {"tier": "TIER_MEDIA_AGGREGATOR", "fans": 2800000, "calls": 600, "win_rate_5d": 0.485, "bayesian_wr": 0.485, "mean_ret_5d": -0.0020, "payoff": 0.95},

    # Overseas High-Reach Contrarian Indicators (FinTwit / StockTwits FOMO top indicators)
    "JimCramer": {"tier": "TIER_CONTRARIAN_INDICATOR", "fans": 2100000, "calls": 85, "win_rate_5d": 0.365, "bayesian_wr": 0.377, "mean_ret_5d": -0.0195, "payoff": 0.58},
    "JFDI": {"tier": "TIER_CONTRARIAN_INDICATOR", "fans": 111443, "calls": 46, "win_rate_5d": 0.391, "bayesian_wr": 0.407, "mean_ret_5d": -0.0112, "payoff": 0.92},
    "Doozio": {"tier": "TIER_CONTRARIAN_INDICATOR", "fans": 47628, "calls": 109, "win_rate_5d": 0.395, "bayesian_wr": 0.402, "mean_ret_5d": -0.0125, "payoff": 0.92},
    "SpudZone": {"tier": "TIER_CONTRARIAN_INDICATOR", "fans": 27050, "calls": 14, "win_rate_5d": 0.000, "bayesian_wr": 0.182, "mean_ret_5d": -0.0536, "payoff": 0.19},
    "Steve_TheBull_Rogers": {"tier": "TIER_CONTRARIAN_INDICATOR", "fans": 19712, "calls": 6, "win_rate_5d": 0.000, "bayesian_wr": 0.286, "mean_ret_5d": -0.0396, "payoff": 0.25},
}


@dataclass(frozen=True)
class KOLProfile:
    author: str
    tier: str
    directional_weight: float
    fans: int
    total_predictions: int
    win_rate_5d: float
    bayesian_win_rate_5d: float
    mean_realized_return_5d: float
    payoff_ratio: float
    is_contrarian: bool = False
    is_media: bool = False

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class KOLWeightedSentimentResult:
    raw_unweighted_polarity: float
    kol_weighted_polarity: float
    total_posts: int
    elite_alpha_count: int
    contrarian_inverted_count: int
    media_neutralized_count: int
    confidence_score: float
    summary_explanation: str
    post_breakdowns: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


class KOLCredibilityRegistry:
    """Registry for auditing author track records and weighting social sentiment (Bilingual CN + Global)."""

    def __init__(self, csv_path: str | Path | None = None):
        self.profiles: dict[str, KOLProfile] = {}
        self._load_embedded_defaults()

        # Automatically attempt to load both Chinese (1,445) and Global (1,070) KOL databases
        default_cn_paths = [
            Path("/usr/local/google/home/shwaihe/stock_prediction/data/benchmark/XUEQIU_KOL_ALPHA_PROFILES.csv"),
            Path("../stock_prediction/data/benchmark/XUEQIU_KOL_ALPHA_PROFILES.csv"),
        ]
        default_global_paths = [
            Path("/usr/local/google/home/shwaihe/stock_prediction/data/benchmark/GLOBAL_KOL_ALPHA_PROFILES.csv"),
            Path("../stock_prediction/data/benchmark/GLOBAL_KOL_ALPHA_PROFILES.csv"),
        ]

        if csv_path and Path(csv_path).exists():
            self.load_from_csv(csv_path)
        else:
            for p in default_cn_paths:
                if p.exists():
                    self.load_from_csv(p)
                    break
            for p in default_global_paths:
                if p.exists():
                    self.load_from_csv(p)
                    break

    def _load_embedded_defaults(self) -> None:
        for name, data in EMBEDDED_KOL_PROFILES.items():
            tier = data["tier"]
            weight = TIER_WEIGHT_MAP.get(tier, 0.2)
            self.profiles[name] = KOLProfile(
                author=name,
                tier=tier,
                directional_weight=weight,
                fans=int(data["fans"]),
                total_predictions=int(data["calls"]),
                win_rate_5d=float(data["win_rate_5d"]),
                bayesian_win_rate_5d=float(data["bayesian_wr"]),
                mean_realized_return_5d=float(data["mean_ret_5d"]),
                payoff_ratio=float(data["payoff"]),
                is_contrarian=(tier == "TIER_CONTRARIAN_INDICATOR"),
                is_media=(tier == "TIER_MEDIA_AGGREGATOR"),
            )

    def load_from_csv(self, path: str | Path) -> int:
        """Load full empirical KOL track record CSV."""
        count = 0
        try:
            with open(path, mode="r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    author = str(row.get("author", "")).strip().lstrip("@")
                    if not author:
                        continue
                    tier = str(row.get("tier", "TIER_NEUTRAL_RETAIL")).strip()
                    weight = TIER_WEIGHT_MAP.get(tier, 0.2)
                    self.profiles[author] = KOLProfile(
                        author=author,
                        tier=tier,
                        directional_weight=weight,
                        fans=int(float(row.get("fans", 0) or 0)),
                        total_predictions=int(float(row.get("total_predictions", 0) or 0)),
                        win_rate_5d=float(row.get("win_rate_5d", 0.5) or 0.5),
                        bayesian_win_rate_5d=float(row.get("bayesian_win_rate_5d", 0.5) or 0.5),
                        mean_realized_return_5d=float(row.get("mean_realized_return_5d", 0.0) or 0.0),
                        payoff_ratio=float(row.get("payoff_ratio", 1.0) or 1.0),
                        is_contrarian=(tier == "TIER_CONTRARIAN_INDICATOR"),
                        is_media=(tier == "TIER_MEDIA_AGGREGATOR" or str(row.get("is_media", "0")) == "1"),
                    )
                    count += 1
            logger.info(f"Loaded {count:,} KOL profiles from {path}")
        except Exception as exc:
            logger.warning(f"Failed to load KOL CSV {path}: {exc}")
        return count

    def get_author_profile(self, author_name: str) -> KOLProfile:
        """Lookup author credibility profile; returns baseline retail profile if unknown."""
        clean_name = str(author_name).strip().lstrip("@")
        if clean_name in self.profiles:
            return self.profiles[clean_name]

        # Heuristic check for unindexed media accounts
        media_keywords = ["新闻", "快讯", "时报", "财联社", "财经", "证券", "同花顺", "格隆汇"]
        if any(k in clean_name for k in media_keywords):
            return KOLProfile(
                author=clean_name,
                tier="TIER_MEDIA_AGGREGATOR",
                directional_weight=0.0,
                fans=10000,
                total_predictions=0,
                win_rate_5d=0.50,
                bayesian_win_rate_5d=0.50,
                mean_realized_return_5d=0.0,
                payoff_ratio=1.0,
                is_contrarian=False,
                is_media=True,
            )

        return KOLProfile(
            author=clean_name,
            tier="TIER_NEUTRAL_RETAIL",
            directional_weight=0.2,
            fans=100,
            total_predictions=0,
            win_rate_5d=0.50,
            bayesian_win_rate_5d=0.50,
            mean_realized_return_5d=0.0,
            payoff_ratio=1.0,
            is_contrarian=False,
            is_media=False,
        )

    def evaluate_weighted_sentiment(
        self,
        posts: list[dict[str, Any]],
    ) -> KOLWeightedSentimentResult:
        """Compute credibility-weighted sentiment polarity from a list of social posts.

        Each post dict should contain:
        - 'author': str (author username)
        - 'polarity': float (-1.0 to +1.0 raw sentiment polarity)
        - 'quality_score': float (optional 0.0 to 1.0 from DataQualityAuditor, default 1.0)
        """
        if not posts:
            return KOLWeightedSentimentResult(
                raw_unweighted_polarity=0.0,
                kol_weighted_polarity=0.0,
                total_posts=0,
                elite_alpha_count=0,
                contrarian_inverted_count=0,
                media_neutralized_count=0,
                confidence_score=0.0,
                summary_explanation="无发帖数据",
                post_breakdowns=[],
            )

        raw_sum = 0.0
        weighted_sum = 0.0
        total_abs_weight = 0.0

        elite_count = 0
        contrarian_count = 0
        media_count = 0
        breakdowns = []

        for p in posts:
            author = str(p.get("author", "anonymous")).strip()
            raw_pol = float(p.get("polarity", 0.0))
            q_score = float(p.get("quality_score", 1.0))

            profile = self.get_author_profile(author)
            w = profile.directional_weight

            raw_sum += raw_pol

            if profile.is_media:
                media_count += 1
                effective_contribution = 0.0
                action_note = "资讯媒体号(剥离方向权重)"
            elif profile.is_contrarian:
                contrarian_count += 1
                # Contrarian indicator: w is negative (-1.5), so positive raw_pol becomes negative contribution!
                effective_contribution = raw_pol * w * q_score
                total_abs_weight += abs(w * q_score)
                action_note = f"反向明灯({profile.win_rate_5d:.0%}胜率) -> 信号执行反向倒置!"
            else:
                if profile.tier in ("TIER_0_ELITE_KOL", "TIER_1_CORE_ALPHA", "TIER_2_SOLID_RESEARCHER"):
                    elite_count += 1
                    action_note = f"高胜率投研大V({profile.win_rate_5d:.0%}胜率) -> 权重放大 {w:.1f}x"
                else:
                    action_note = f"普通散户(低权基准 {w:.1f}x)"
                effective_contribution = raw_pol * w * q_score
                total_abs_weight += abs(w * q_score)

            weighted_sum += effective_contribution
            breakdowns.append({
                "author": author,
                "tier": profile.tier,
                "fans": profile.fans,
                "historical_win_rate_5d": round(profile.win_rate_5d, 3),
                "raw_polarity": round(raw_pol, 3),
                "applied_weight": w,
                "effective_contribution": round(effective_contribution, 3),
                "action_note": action_note,
            })

        raw_avg = round(raw_sum / len(posts), 4)
        if total_abs_weight > 0:
            weighted_avg = round(max(-1.0, min(1.0, weighted_sum / total_abs_weight)), 4)
        else:
            weighted_avg = 0.0

        confidence = min(1.0, round((elite_count * 0.35) + (contrarian_count * 0.25) + 0.2, 2))

        summary = (
            f"评估 {len(posts)} 条观点: 原始未加权情绪 {raw_avg:+.2f} -> "
            f"大V信誉加权后情绪 {weighted_avg:+.2f} "
            f"(含高胜率大V {elite_count} 人、反向明灯倒置 {contrarian_count} 人、资讯媒体去方向 {media_count} 人)"
        )

        return KOLWeightedSentimentResult(
            raw_unweighted_polarity=raw_avg,
            kol_weighted_polarity=weighted_avg,
            total_posts=len(posts),
            elite_alpha_count=elite_count,
            contrarian_inverted_count=contrarian_count,
            media_neutralized_count=media_count,
            confidence_score=confidence,
            summary_explanation=summary,
            post_breakdowns=breakdowns,
        )


if __name__ == "__main__":
    registry = KOLCredibilityRegistry()
    print(f"Initialized KOLCredibilityRegistry with {len(registry.profiles):,} verified profiles.\n")

    # Simulate a typical market divergence:
    # 2 mega-follower Contrarian Indicators (反向明灯) and 1 media account are screaming bullish (+0.90),
    # while 2 Elite Alpha researchers are calmly warning of valuation risk (-0.70).
    sample_posts = [
        {"author": "钟华守正出奇", "polarity": +0.90, "quality_score": 0.8},  # 425k fans, 40% win rate (Contrarian!)
        {"author": "东先生", "polarity": +0.85, "quality_score": 0.8},        # 150k fans, 40% win rate (Contrarian!)
        {"author": "财联社", "polarity": +0.60, "quality_score": 0.9},        # Media aggregator
        {"author": "阿尔法工场", "polarity": -0.75, "quality_score": 0.95},   # Elite KOL (91.7% 5D win rate)
        {"author": "价投傻鱼", "polarity": -0.65, "quality_score": 0.90},     # Core Alpha (70.8% 5D win rate)
    ]

    res = registry.evaluate_weighted_sentiment(sample_posts)
    print("=== Empirical Demonstration: Naive Average vs. KOL Credibility-Weighted Signal ===")
    print(f"Naive Unweighted Sentiment (fooled by follower count): {res.raw_unweighted_polarity:+.2f} (BULLISH TRAP!)")
    print(f"KOL Credibility-Weighted Sentiment:                    {res.kol_weighted_polarity:+.2f} (TRUE BEARISH ALPHA!)")
    print(f"Explanation: {res.summary_explanation}\n")
    print("Individual Post Audit Breakdown:")
    for b in res.post_breakdowns:
        print(
            f"  - [{b['author']:<8}] Fans: {b['fans']:>7,} | 5D WinRate: {b['historical_win_rate_5d']*100:>4.1f}% | "
            f"Raw: {b['raw_polarity']:+.2f} -> Effective: {b['effective_contribution']:+.2f} ({b['action_note']})"
        )
