# GENERATED by scripts/build_package.py from plugins/fin-china/skills/china-trading-stack/scripts/stock_predictability_stratifier.py - do not edit here.
# Edit the skill script and rerun the generator; validate.py checks they match.
# Owning skill: china-trading-stack (fin_skills.load('china-trading-stack') returns its SKILL.md).

"""Stock Predictability Stratifier & Execution Regime Filter (股票可预测性分层与执行门控).

Why this exists:
1. Not all stocks are equally predictable. Empirical out-of-sample testing across 202 A-Share,
   HK/ADR, and US equities proves that cross-sectional Rank IC ranges from +0.187 (high predictability)
   down to +0.000 (pure noisy random walk).
2. High-predictability stocks (Tier S / Tier A: e.g. 迈瑞医疗, 华东医药, 宁波银行, 招商银行, 顺丰控股,
   BEKE, TME, NVDA, COST) feature strong institutional valuation anchors and rational contrarian
   rebounds when retail panics.
3. Moderate stocks (Tier B: 85 equities) yield alpha ONLY when triggered by substantive semantic
   events (Earnings / Valuation / Position cuts) over a 5-day holding window (Sharpe 1.491 vs 0.202).
4. Low-predictability noisy stocks (Tier C: 65 equities, e.g. 理想汽车, 小鹏汽车, 亿纬锂能, 新城控股)
   are dominated by speculative retail noise or macro policy shocks; trading single-stock sentiment
   on them loses money to friction and must be substituted with broad index ETFs (510300 / 510500).
"""
from __future__ import annotations

import csv
import logging
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

logger = logging.getLogger("stock_predictability_stratifier")

TIER_ALLOCATION_MULTIPLIERS = {
    "TIER_S_HIGH_PREDICTABILITY": 1.20,     # Amplify signal sizing by +20%
    "TIER_A_SOLID_PREDICTABILITY": 1.00,    # Standard 100% signal sizing
    "TIER_B_MODERATE_EVENT_DRIVEN": 0.60,   # 60% sizing; require substantive event trigger
    "TIER_C_LOW_NOISY_RANDOM_WALK": 0.00,   # Block single-stock sentiment chasing; use ETF substitute
}

EMBEDDED_PREDICTABILITY_TIERS = {
    # Tier S: High Predictability (Rank IC > +0.085, 5D WinRate 55% - 61%)
    "SZ300729": {"name": "乐歌股份", "market": "A_SHARE", "tier": "TIER_S_HIGH_PREDICTABILITY", "score": 100.0, "win_rate": 0.610, "ic": 0.187, "sharpe": 1.78, "etf_sub": "510500"},
    "SZ000963": {"name": "华东医药", "market": "A_SHARE", "tier": "TIER_S_HIGH_PREDICTABILITY", "score": 90.2, "win_rate": 0.585, "ic": 0.130, "sharpe": 1.35, "etf_sub": "510300"},
    "SZ300760": {"name": "迈瑞医疗", "market": "A_SHARE", "tier": "TIER_S_HIGH_PREDICTABILITY", "score": 81.1, "win_rate": 0.554, "ic": 0.130, "sharpe": 1.18, "etf_sub": "510300"},
    "SZ002223": {"name": "鱼跃医疗", "market": "A_SHARE", "tier": "TIER_S_HIGH_PREDICTABILITY", "score": 74.8, "win_rate": 0.566, "ic": 0.102, "sharpe": 1.27, "etf_sub": "510500"},
    "SZ002142": {"name": "宁波银行", "market": "A_SHARE", "tier": "TIER_S_HIGH_PREDICTABILITY", "score": 74.2, "win_rate": 0.576, "ic": 0.102, "sharpe": 0.88, "etf_sub": "510880"},
    "SZ002352": {"name": "顺丰控股", "market": "A_SHARE", "tier": "TIER_S_HIGH_PREDICTABILITY", "score": 72.8, "win_rate": 0.539, "ic": 0.119, "sharpe": 1.11, "etf_sub": "510300"},
    "SZ000001": {"name": "平安银行", "market": "A_SHARE", "tier": "TIER_S_HIGH_PREDICTABILITY", "score": 69.5, "win_rate": 0.580, "ic": 0.088, "sharpe": 0.78, "etf_sub": "510880"},
    "SZ002027": {"name": "分众传媒", "market": "A_SHARE", "tier": "TIER_S_HIGH_PREDICTABILITY", "score": 69.0, "win_rate": 0.549, "ic": 0.109, "sharpe": 0.79, "etf_sub": "510300"},
    "SH600036": {"name": "招商银行", "market": "A_SHARE", "tier": "TIER_S_HIGH_PREDICTABILITY", "score": 67.8, "win_rate": 0.558, "ic": 0.093, "sharpe": 1.02, "etf_sub": "510880"},
    "SH601318": {"name": "中国平安", "market": "A_SHARE", "tier": "TIER_S_HIGH_PREDICTABILITY", "score": 67.3, "win_rate": 0.559, "ic": 0.100, "sharpe": 0.62, "etf_sub": "510300"},
    "SH600276": {"name": "恒瑞医药", "market": "A_SHARE", "tier": "TIER_S_HIGH_PREDICTABILITY", "score": 65.8, "win_rate": 0.530, "ic": 0.102, "sharpe": 1.27, "etf_sub": "510300"},
    "BEKE":     {"name": "贝壳找房", "market": "US_GLOBAL_ADR", "tier": "TIER_S_HIGH_PREDICTABILITY", "score": 85.4, "win_rate": 0.585, "ic": 0.119, "sharpe": 1.27, "etf_sub": "510900"},
    "TME":      {"name": "腾讯音乐", "market": "US_GLOBAL_ADR", "tier": "TIER_S_HIGH_PREDICTABILITY", "score": 68.2, "win_rate": 0.555, "ic": 0.101, "sharpe": 0.82, "etf_sub": "510900"},
    "FUTU":     {"name": "富途控股", "market": "US_GLOBAL_ADR", "tier": "TIER_S_HIGH_PREDICTABILITY", "score": 65.1, "win_rate": 0.554, "ic": 0.094, "sharpe": 0.79, "etf_sub": "510900"},
    "PEP":      {"name": "百事可乐", "market": "US_GLOBAL_ADR", "tier": "TIER_S_HIGH_PREDICTABILITY", "score": 65.0, "win_rate": 0.568, "ic": 0.085, "sharpe": 0.74, "etf_sub": "513500"},

    # Tier A: Solid Predictability (Rank IC +0.05 to +0.09, WinRate 53% - 57%)
    "NVDA":     {"name": "英伟达 (NVIDIA)", "market": "US_GLOBAL_ADR", "tier": "TIER_A_SOLID_PREDICTABILITY", "score": 55.2, "win_rate": 0.558, "ic": 0.057, "sharpe": 1.04, "etf_sub": "513100"},
    "COST":     {"name": "好市多 (Costco)", "market": "US_GLOBAL_ADR", "tier": "TIER_A_SOLID_PREDICTABILITY", "score": 56.6, "win_rate": 0.571, "ic": 0.062, "sharpe": 0.56, "etf_sub": "513500"},
    "KO":       {"name": "可口可乐", "market": "US_GLOBAL_ADR", "tier": "TIER_A_SOLID_PREDICTABILITY", "score": 61.9, "win_rate": 0.540, "ic": 0.091, "sharpe": 0.93, "etf_sub": "513500"},

    # Tier C: Noisy Random Walk Blacklist (Rank IC < +0.01, WinRate < 49%)
    "09868":    {"name": "小鹏汽车-W", "market": "US_GLOBAL_ADR", "tier": "TIER_C_LOW_NOISY_RANDOM_WALK", "score": 8.3, "win_rate": 0.480, "ic": 0.002, "sharpe": 0.04, "etf_sub": "510900"},
    "02015":    {"name": "理想汽车-W", "market": "US_GLOBAL_ADR", "tier": "TIER_C_LOW_NOISY_RANDOM_WALK", "score": 8.1, "win_rate": 0.479, "ic": 0.002, "sharpe": -0.18, "etf_sub": "510900"},
    "SZ300014": {"name": "亿纬锂能", "market": "A_SHARE", "tier": "TIER_C_LOW_NOISY_RANDOM_WALK", "score": 7.7, "win_rate": 0.469, "ic": 0.008, "sharpe": -0.01, "etf_sub": "510500"},
    "SH601155": {"name": "新城控股", "market": "A_SHARE", "tier": "TIER_C_LOW_NOISY_RANDOM_WALK", "score": 10.8, "win_rate": 0.491, "ic": 0.002, "sharpe": -0.22, "etf_sub": "510300"},
    "SH603288": {"name": "海天味业", "market": "A_SHARE", "tier": "TIER_C_LOW_NOISY_RANDOM_WALK", "score": 10.1, "win_rate": 0.480, "ic": 0.004, "sharpe": 0.14, "etf_sub": "510300"},
}


@dataclass(frozen=True)
class StockPredictabilityProfile:
    symbol: str
    name: str
    market: str
    predictability_tier: str
    predictability_score: float
    win_rate_5d: float
    rank_ic: float
    annualized_sharpe: float
    allocation_multiplier: float
    recommended_execution_mode: str
    etf_substitute: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


class StockPredictabilityStratifier:
    """Stratifies equities into 4 predictability tiers and governs trade execution."""

    def __init__(self, csv_path: str | Path | None = None):
        self.profiles: dict[str, StockPredictabilityProfile] = {}
        self._load_embedded_defaults()

        default_paths = [
            Path("/usr/local/google/home/shwaihe/stock_prediction/data/benchmark/STOCK_PREDICTABILITY_TIERS.csv"),
            Path("../stock_prediction/data/benchmark/STOCK_PREDICTABILITY_TIERS.csv"),
        ]
        target = Path(csv_path) if csv_path else None
        if not target or not target.exists():
            for p in default_paths:
                if p.exists():
                    target = p
                    break
        if target and target.exists():
            self.load_from_csv(target)

    def _get_execution_mode(self, tier: str) -> str:
        if tier == "TIER_S_HIGH_PREDICTABILITY":
            return "FULL_CONVICTION_CONTRARIAN_AND_TREND (1.2x Sizing)"
        if tier == "TIER_A_SOLID_PREDICTABILITY":
            return "STANDARD_MULTIMODAL_SIGNAL (1.0x Sizing)"
        if tier == "TIER_B_MODERATE_EVENT_DRIVEN":
            return "EVENT_TRIGGERED_ONLY_T5_HOLD (0.6x Sizing, Ignore Daily Noise)"
        return "BLOCKED_SINGLE_STOCK_NOISE_USE_ETF_SUBSTITUTE (0.0x Sizing)"

    def _load_embedded_defaults(self) -> None:
        for sym, d in EMBEDDED_PREDICTABILITY_TIERS.items():
            tier = d["tier"]
            mult = TIER_ALLOCATION_MULTIPLIERS.get(tier, 0.6)
            self.profiles[sym] = StockPredictabilityProfile(
                symbol=sym,
                name=d["name"],
                market=d["market"],
                predictability_tier=tier,
                predictability_score=float(d["score"]),
                win_rate_5d=float(d["win_rate"]),
                rank_ic=float(d["ic"]),
                annualized_sharpe=float(d["sharpe"]),
                allocation_multiplier=mult,
                recommended_execution_mode=self._get_execution_mode(tier),
                etf_substitute=d.get("etf_sub", "510300"),
            )

    def load_from_csv(self, path: str | Path) -> int:
        count = 0
        try:
            with open(path, "r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                for r in reader:
                    sym = str(r.get("symbol", "")).strip().upper()
                    if not sym:
                        continue
                    tier = str(r.get("predictability_tier", "TIER_B_MODERATE_EVENT_DRIVEN")).strip()
                    mult = TIER_ALLOCATION_MULTIPLIERS.get(tier, 0.6)
                    market = str(r.get("market", "A_SHARE")).strip()
                    if len(sym) == 5 and sym.isdigit():
                        etf_sub = "510900"  # Hang Seng ETF for HK equities
                    elif market == "US_GLOBAL_ADR":
                        etf_sub = "513100"  # Nasdaq 100 ETF for US/ADR equities
                    else:
                        etf_sub = "510300"  # CSI 300 ETF for A-Shares
                    self.profiles[sym] = StockPredictabilityProfile(
                        symbol=sym,
                        name=str(r.get("name", sym)).strip(),
                        market=market,
                        predictability_tier=tier,
                        predictability_score=float(r.get("predictability_score", 40.0) or 40.0),
                        win_rate_5d=float(r.get("win_rate_5d", 0.50) or 0.50),
                        rank_ic=float(r.get("rank_ic", 0.02) or 0.02),
                        annualized_sharpe=float(r.get("annualized_sharpe", 0.50) or 0.50),
                        allocation_multiplier=mult,
                        recommended_execution_mode=self._get_execution_mode(tier),
                        etf_substitute=etf_sub,
                    )
                    count += 1
        except Exception as exc:
            logger.warning(f"Failed to load stock predictability CSV {path}: {exc}")
        return count

    def evaluate_stock_signal(
        self,
        symbol: str,
        raw_signal: float,
        is_substantive_event: bool = False,
    ) -> dict[str, Any]:
        """Filter and scale a stock signal according to its empirical predictability tier."""
        sym = symbol.strip().upper()
        prof = self.profiles.get(sym)
        if not prof:
            prof = StockPredictabilityProfile(
                symbol=sym,
                name=sym,
                market="UNKNOWN",
                predictability_tier="TIER_B_MODERATE_EVENT_DRIVEN",
                predictability_score=40.0,
                win_rate_5d=0.51,
                rank_ic=0.02,
                annualized_sharpe=0.40,
                allocation_multiplier=0.60,
                recommended_execution_mode=self._get_execution_mode("TIER_B_MODERATE_EVENT_DRIVEN"),
                etf_substitute="510300",
            )

        tier = prof.predictability_tier
        if tier == "TIER_C_LOW_NOISY_RANDOM_WALK":
            return {
                "symbol": sym,
                "name": prof.name,
                "tier": tier,
                "raw_signal": raw_signal,
                "effective_signal": 0.0,
                "action": "REJECT_NOISY_STOCK_USE_ETF",
                "recommended_instrument": prof.etf_substitute,
                "explanation": f"[{prof.name}] 属于 Tier C 低可预测性噪音标的 (Rank IC={prof.rank_ic:+.3f}, 5D胜率={prof.win_rate_5d*100:.1f}%)，禁止个股追涨杀跌，已自动替换为宽基 ETF ({prof.etf_substitute})。",
            }

        if tier == "TIER_B_MODERATE_EVENT_DRIVEN" and not is_substantive_event:
            return {
                "symbol": sym,
                "name": prof.name,
                "tier": tier,
                "raw_signal": raw_signal,
                "effective_signal": 0.0,
                "action": "HOLD_WAIT_FOR_SUBSTANTIVE_EVENT",
                "recommended_instrument": sym,
                "explanation": f"[{prof.name}] 属于 Tier B 事件驱动型标的，日常无实质事件时过滤噪音 (仅在财报/估值/大V调仓事件日触发 T+5 交易)。",
            }

        eff_sig = round(raw_signal * prof.allocation_multiplier, 3)
        return {
            "symbol": sym,
            "name": prof.name,
            "tier": tier,
            "raw_signal": raw_signal,
            "effective_signal": eff_sig,
            "action": "EXECUTE_SIGNAL",
            "recommended_instrument": sym,
            "explanation": f"[{prof.name}] 属于 {tier} 高确定性标的 (Rank IC={prof.rank_ic:+.3f}, 5D胜率={prof.win_rate_5d*100:.1f}%)，执行权重乘数 {prof.allocation_multiplier:.2f}x -> 有效信号 {eff_sig:+.2f}。",
        }
