"""Fixture-free helpers shared by the fin_skills tests.

tests/ is on sys.path during collection (pytest's default prepend import mode), so test
modules import this as `from _helpers import ...`. Nothing here touches the network or
writes files.
"""
from __future__ import annotations

import importlib
import math
from pathlib import Path

import fin_skills

TESTS_DIR = Path(__file__).resolve().parent
REPO_ROOT = TESTS_DIR.parent
PACKAGE_ROOT = Path(fin_skills.__file__).resolve().parent

# Every generated namespace __init__ carries this phrase in its docstring (see
# scripts/build_package.py). The hand-written `api/` package and `_skills/` data do not.
GENERATED_MARKER = "generated from the"
GENERATED_HEADER = "# GENERATED by scripts/build_package.py"


def generated_namespaces() -> list[str]:
    """Namespaces produced by build_package.py: core, libraries, china, futures_fx, ..."""
    out = []
    for init in sorted(PACKAGE_ROOT.glob("*/__init__.py")):
        text = init.read_text(encoding="utf-8")
        if GENERATED_MARKER in text and "__all__" in text:
            out.append(init.parent.name)
    return out


def generated_modules() -> list[str]:
    """Fully qualified names of every generated module, from each namespace's __all__."""
    mods: list[str] = []
    for ns in generated_namespaces():
        pkg = importlib.import_module(f"fin_skills.{ns}")
        mods.extend(f"fin_skills.{ns}.{m}" for m in pkg.__all__)
    return mods


def module_source_path(qualname: str) -> Path:
    ns, mod = qualname.split(".")[-2:]
    return PACKAGE_ROOT / ns / f"{mod}.py"


def test_file_for(qualname: str) -> Path:
    ns, mod = qualname.split(".")[-2:]
    return TESTS_DIR / f"test_{ns}_{mod}.py"


def is_ascii(text: str) -> bool:
    return all(ord(ch) < 128 for ch in text)


# --------------------------------------------------------------------------- Black-Scholes
def _norm_cdf(x: float) -> float:
    return 0.5 * (1.0 + math.erf(x / math.sqrt(2.0)))


def bs_call(S: float, K: float, r: float, q: float, sigma: float, T: float) -> float:
    """Independent closed-form European call (math.erf only), the reference for the trees."""
    d1 = (math.log(S / K) + (r - q + 0.5 * sigma * sigma) * T) / (sigma * math.sqrt(T))
    d2 = d1 - sigma * math.sqrt(T)
    return S * math.exp(-q * T) * _norm_cdf(d1) - K * math.exp(-r * T) * _norm_cdf(d2)


def bs_put(S: float, K: float, r: float, q: float, sigma: float, T: float) -> float:
    d1 = (math.log(S / K) + (r - q + 0.5 * sigma * sigma) * T) / (sigma * math.sqrt(T))
    d2 = d1 - sigma * math.sqrt(T)
    return K * math.exp(-r * T) * _norm_cdf(-d2) - S * math.exp(-q * T) * _norm_cdf(-d1)


# Published reference greeks for S=K=100, T=1y, r=5%, q=0, sigma=20% (the numbers quoted in
# greeks_convention.py and lib-vollib's SKILL.md). QuantLib reports absolute units; vollib
# reports vega/100, theta/365, rho/100.
QUANTLIB_CALL = {
    "price": 10.45058357, "delta": 0.63683065, "gamma": 0.01876202,
    "vega": 37.52403469, "theta": -6.41402755, "rho": 53.23248155,
}
VOLLIB_CALL = {
    "price": 10.45058357, "delta": 0.63683065, "gamma": 0.01876202,
    "vega": 0.37524035, "theta": -0.01757268, "rho": 0.53232482,
}
