# GENERATED by scripts/build_package.py from plugins/fin-strategies/skills/position-sizing-kelly/scripts/position_sizing.py - do not edit here.
# Edit the skill script and rerun the generator; validate.py checks they match.
# Owning skill: position-sizing-kelly (fin_skills.load('position-sizing-kelly') returns its SKILL.md).

#!/usr/bin/env python3
"""Kelly sizing, the drawdown it implies, and what estimating the mean does to it.

The discrete and continuous Kelly fractions, the growth curve and the half-Kelly argument,
Thorp's closed form for the probability of ever being reduced to a fraction of the starting
bankroll - each checked by simulation - and then the two ways the formula is misapplied:

  1. computing f* from an ESTIMATED mean and betting it in full. There is an exact penalty
     for this, derived below and confirmed by simulation, and it makes fractional Kelly a
     consequence of the estimate's t-statistic rather than a matter of taste;
  2. treating a Sharpe ratio as if it were a Kelly fraction. f* = SR/sigma, so the error is
     a factor of 1/sigma: a large under-bet at equity volatility, and at sigma = 2 with
     SR = 0.5 it is exactly DOUBLE Kelly, whose growth rate is exactly zero.

Sources, all read in the primary text:

  KELLY (1956), "A New Interpretation of Information Rate", Bell System Technical Journal
  35, 917-926. His p is the probability of ERROR and his q of correct transmission - the
  OPPOSITE of the modern convention. In his letters, all displays UNNUMBERED, pp. 919-920:
      G = q log(1+l) + p log(1-l)          -> modern  G = p log(1+f) + q log(1-f)
      (1 + l) = 2q  and  (1 - l) = 2p      -> l = q - p, which he never displays
      G_max = 1 + p log p + q log q = R    (log base 2)
  The b-to-1 form f* = (b*p - q)/b is NOT in Kelly. Thorp (2006) p. 391 attributes it to
  his own Thorp (1984). Kelly's general-odds result, pp. 924-925, is a(s) = p(s) - b/alpha_s
  with HIS b the fraction not bet and alpha_s the GROSS return per dollar.

  THORP (2006), "The Kelly Criterion in Blackjack Sports Betting, and the Stock Market",
  Handbook of Asset and Liability Management vol. 1, ch. 9, 385-428. Title page: "Corrections
  added April 20, 2005" - and section 7.4 says why: "In earlier versions of this chapter the
  exponent in Equations (3.2), (7.8) and (7.9) were off by a factor of 2". Use the corrected
  text. Equation numbers as printed:
      (7.2) g_inf(f) = r + f*(m - r) - s^2*f^2/2
      (7.3) f* = (m - r)/s^2 ,  Var(G_inf(f)) = s^2*f^2 ,  Sdev(G_inf(f)) = s*f
      (7.4) r = 0:  f* = m/s^2 ,  g_inf(f*) = m^2/(2*s^2)
      p. 407: "The slope of this line is the Sharpe ratio S = (m0 - r0)/s0", and
              g_inf(f*) = S^2/2 + r
      p. 409: g_inf(c*f*) / g_inf(f*) = c*(2 - c)  and  Sdev ratio = c
      (7.8) Prob(V(t)/V0 <= x for some t) = x^(2*g_inf / Var(G_inf))
      (7.9) = x, for r = 0 and f = f*. For 0 < r < m the exponent becomes
              1 + 2*r*s^2/(m - r)^2.
      (7.11) Prob(V(t, c f*) reaches y*V0 before x*V0)
               = [1 - x^(2/c - 1)] / [1 - (x/y)^(2/c - 1)]     (credited to Schlesinger)
      (7.13) Prob(V(t, c f*)/V0 <= x for some t) = x^(2/c - 1)
      p. 415: "'half Kelly' has 3/4 the growth rate but much less chance of a big loss";
              "The chance of ever losing half the starting capital is 1/2 for f = f* but
              only 1/8 for f = f*/2"; Prob(doubles before halving) = 2/3 at f*, 8/9 at f*/2.
      section 7.3, p. 411, on estimating m: "A disaster occurs when m_t = .5 m_e but we
              choose f = 1.5 f*_e ... Then g = -.75 and we will be ruined. It is still bad
              to choose f = f*_e when m_t = .5 m_e for then g = 0".

  MERTON (1969), "Lifetime Portfolio Selection under Uncertainty", Rev. Econ. Stat. 51(3),
  eq. (25)/(29)/(43): w* = (a - r)/(sigma^2 * delta) with delta Pratt's relative risk
  aversion; log utility is delta = 1, giving w* = (a - r)/sigma^2.

🚨 x^(2/c - 1) is about the fraction of the INITIAL wealth, not a drawdown from the running
maximum. The running-maximum version is false over an unbounded horizon - a drawdown of any
fixed fraction from the running peak happens with probability 1 - and the demo measures both.

Run:  python position_sizing.py     (numpy + scipy, fixed seed, about 20 s)
"""
from __future__ import annotations

import numpy as np
from scipy import optimize

SEED = 20260909


# ------------------------------------------------------------------------- discrete Kelly
def growth_binary(f, p: float, b: float = 1.0):
    """Expected log growth of a b-to-1 bet won with probability p: p*ln(1+b f) + q*ln(1-f).

    Kelly (1956) p. 919 gives the even-money case (b = 1) in his own reversed p/q letters.
    """
    if not 0.0 <= p <= 1.0 or b <= 0:
        raise ValueError("need 0 <= p <= 1 and b > 0")
    f = np.asarray(f, dtype=float)
    with np.errstate(divide="ignore", invalid="ignore"):
        g = p * np.log1p(b * f) + (1.0 - p) * np.log1p(-f)
    return np.where((f >= 1.0) | (f <= -1.0 / b), -np.inf, g)


def kelly_binary(p: float, b: float = 1.0) -> float:
    """f* = (b*p - q)/b, floored at 0.

    ! This closed form is Thorp (1984), not Kelly (1956) - Thorp (2006) p. 391 says so
    explicitly. Kelly's own even-money result is l = q - p in his reversed notation, and he
    never displays it. b = 1 recovers f* = 2p - 1.
    """
    if not 0.0 <= p <= 1.0 or b <= 0:
        raise ValueError("need 0 <= p <= 1 and b > 0")
    return max((b * p - (1.0 - p)) / b, 0.0)


def kelly_discrete(payoffs, probs, bracket=(1e-9, 0.999999)) -> float:
    """Numerically maximise E[ln(1 + f*X)] for any discrete payoff distribution.

    The independent check on `kelly_binary`, and the tool for a bet that is not binary.
    Returns 0 when the bet has no positive-growth fraction.
    """
    x = np.asarray(payoffs, dtype=float)
    w = np.asarray(probs, dtype=float)
    if x.shape != w.shape or x.ndim != 1 or w.size < 2:
        raise ValueError("payoffs and probs must be 1-D arrays of the same length >= 2")
    if abs(w.sum() - 1.0) > 1e-9 or np.any(w < 0):
        raise ValueError("probs must be non-negative and sum to 1")
    if float(w @ x) <= 0:
        return 0.0
    worst = x.min()
    hi = bracket[1] if worst >= 0 else min(bracket[1], -0.999999 / worst)

    def neg(f):
        return -float(w @ np.log1p(f * x))

    res = optimize.minimize_scalar(neg, bounds=(bracket[0], hi), method="bounded")
    return float(res.x) if res.success and -res.fun > 0 else 0.0


def kelly_max_growth_binary(p: float) -> float:
    """Kelly (1956) p. 920, in BITS: G_max = 1 + p*log2(p) + q*log2(q), for even money.

    Kelly's identification of this with the Shannon transmission rate R is the whole point
    of his paper's title, and it is why the base is 2.
    """
    if not 0.0 < p < 1.0:
        raise ValueError("need 0 < p < 1")
    q = 1.0 - p
    return 1.0 + p * np.log2(p) + q * np.log2(q)


# ----------------------------------------------------------------------- continuous Kelly
def kelly_fraction(mu: float, sigma: float, r: float = 0.0) -> float:
    """Thorp (2006) eq. (7.3): f* = (m - r)/s^2. Merton (1969) eq. (29) with log utility."""
    if sigma <= 0:
        raise ValueError("sigma must be positive")
    return (mu - r) / sigma ** 2


def growth_rate(f, mu: float, sigma: float, r: float = 0.0):
    """Thorp (2006) eq. (7.2): g_inf(f) = r + f*(m - r) - s^2*f^2/2."""
    if sigma <= 0:
        raise ValueError("sigma must be positive")
    f = np.asarray(f, dtype=float)
    return r + f * (mu - r) - sigma ** 2 * f ** 2 / 2.0


def growth_ratio(c):
    """Thorp (2006) p. 409: g_inf(c f*)/g_inf(f*) = c(2 - c). c = 1/2 gives 3/4; c = 2 gives 0."""
    c = np.asarray(c, dtype=float)
    return c * (2.0 - c)


def sharpe_ratio(mu: float, sigma: float, r: float = 0.0) -> float:
    """Thorp (2006) p. 407: S = (m0 - r0)/s0, and g_inf(f*) = S^2/2 + r."""
    if sigma <= 0:
        raise ValueError("sigma must be positive")
    return (mu - r) / sigma


def vol_target_fraction(target_vol: float, sigma: float) -> float:
    """The everyday sizing rule: hold f = target_vol / sigma of the asset.

    f_kelly = mu/sigma^2 = SR/sigma and f_voltarget = target/sigma, so the two coincide
    EXACTLY when the volatility target equals the Sharpe ratio - and at no other target.
    That identity is what makes "size to 10% vol" a Kelly bet only if your Sharpe is 0.10.
    """
    if sigma <= 0 or target_vol < 0:
        raise ValueError("sigma must be positive and target_vol non-negative")
    return target_vol / sigma


# ---------------------------------------------------------------------------- drawdown
def ruin_prob(x: float, c: float = 1.0) -> float:
    """Thorp (2006) eq. (7.13): Prob(V(t, c f*)/V0 <= x for some t) = x^(2/c - 1).

    Requires r = 0 and 0 < c < 2. It is about the INITIAL wealth. The running-maximum
    version of this statement is false - see `max_drawdown_paths`.
    """
    if not 0.0 < x < 1.0:
        raise ValueError("x must be strictly between 0 and 1")
    if not 0.0 < c < 2.0:
        raise ValueError("c must be in (0, 2); at c = 2 the growth rate is zero")
    return float(x ** (2.0 / c - 1.0))


def double_before_halve(c: float = 1.0) -> float:
    """Thorp (2006) eq. (7.11) at x = 1/2, y = 2: 2/3 at full Kelly, 8/9 at half."""
    if not 0.0 < c < 2.0:
        raise ValueError("c must be in (0, 2)")
    a = 2.0 / c - 1.0
    return float((1.0 - 0.5 ** a) / (1.0 - 0.25 ** a))


def simulate_ruin(c: float, mu: float, sigma: float, x: float, years: float = 200.0,
                  dt: float = 1.0 / 12.0, n_paths: int = 20_000, seed: int = SEED) -> dict:
    """Empirical Prob(wealth ever <= x * W0) under fractional Kelly, two ways.

    'naive' looks only at the sampled points and therefore MISSES crossings that happen
    inside a step. 'bridge' corrects for that exactly: given the log-wealth at the two ends
    of a step, the probability the Brownian bridge between them stayed above the level m is
    1 - exp(-2*(a - m)*(b - m)/(s^2*dt)). Both are reported because the gap between them is
    the size of an error every discretely sampled drawdown study contains.

    Also returns the distribution of the maximum drawdown FROM THE RUNNING PEAK, which is a
    different quantity from eq. (7.13) and does not obey it.
    """
    if not 0.0 < c < 2.0 or sigma <= 0 or not 0.0 < x < 1.0:
        raise ValueError("need 0 < c < 2, sigma > 0 and 0 < x < 1")
    f = c * kelly_fraction(mu, sigma)
    nu = growth_rate(f, mu, sigma)                    # log-wealth drift
    s = f * sigma                                     # log-wealth diffusion, eq. (7.3)
    n_steps = int(round(years / dt))
    rng = np.random.default_rng(seed)
    m = np.log(x)
    y = np.zeros(n_paths)
    run_min = np.zeros(n_paths)
    run_max = np.zeros(n_paths)
    max_dd = np.zeros(n_paths)
    log_survive = np.zeros(n_paths)
    s2dt = s * s * dt
    for _ in range(n_steps):
        y_new = y + nu * dt + s * np.sqrt(dt) * rng.standard_normal(n_paths)
        above = (y > m) & (y_new > m)
        with np.errstate(over="ignore"):
            cross = np.exp(-2.0 * (y - m) * (y_new - m) / s2dt)
        step = np.where(above, np.log1p(-np.clip(cross, 0.0, 1 - 1e-15)), -np.inf)
        log_survive += step
        y = y_new
        run_min = np.minimum(run_min, y)
        run_max = np.maximum(run_max, y)
        max_dd = np.maximum(max_dd, run_max - y)
    return {"c": c, "f": f, "nu": nu, "s": s, "x": x,
            "p_naive": float(np.mean(run_min <= m)),
            "p_bridge": float(1.0 - np.mean(np.exp(log_survive))),
            "p_formula": ruin_prob(x, c),
            "median_max_dd": float(1.0 - np.exp(-np.median(max_dd))),
            "p_dd_from_peak": float(np.mean(max_dd >= -np.log(x))),
            "terminal_growth": float(np.mean(y) / years)}


def max_drawdown_paths(logw) -> np.ndarray:
    """Maximum drawdown from the running peak, as a fraction, for each column of a path set."""
    logw = np.asarray(logw, dtype=float)
    peak = np.maximum.accumulate(logw, axis=0)
    return 1.0 - np.exp(np.min(logw - peak, axis=0))


# ------------------------------------------------------------------- estimating the mean
def expected_growth_estimated(c: float, mu: float, sigma: float, n_years: float) -> float:
    """Expected growth when f is c times the Kelly fraction of an ESTIMATED mean.

    Model: mu_hat ~ N(mu, sigma^2 / n_years) - the standard error of a mean return from
    n_years of data - sigma known, and f = c*mu_hat/sigma^2 held fixed thereafter. Then

        E[g] = E[f*mu - f^2*sigma^2/2]
             = c*mu^2/sigma^2 - (sigma^2/2) * c^2 * (mu^2/sigma^4 + 1/(n_years*sigma^2))
             = g(f*) * c*(2 - c)  -  c^2 / (2*n_years)

    The first term is Thorp's exact c(2-c); the second is the price of not knowing mu, and
    it does not depend on mu or sigma at all - only on how many years you measured.
    """
    if n_years <= 0:
        raise ValueError("n_years must be positive")
    return float(growth_rate(kelly_fraction(mu, sigma), mu, sigma) * growth_ratio(c)
                 - c ** 2 / (2.0 * n_years))


def optimal_c_estimated(mu: float, sigma: float, n_years: float) -> float:
    """The c that maximises `expected_growth_estimated`: c* = t^2 / (1 + t^2).

    Setting d/dc of g(f*)*c*(2-c) - c^2/(2n) to zero gives c = SR^2*n / (1 + SR^2*n), and
    SR^2*n is exactly the SQUARED t-STATISTIC of the mean estimate, t = SR*sqrt(n).

    So fractional Kelly is not a taste: t = 1 gives exactly HALF Kelly, and t = 2 - an edge
    most people would call significant - gives four-fifths. Derived here under the model
    above (normal error, sigma known, one estimate held fixed) and checked by simulation in
    the demo; it is not quoted from a source.
    """
    t2 = sharpe_ratio(mu, sigma) ** 2 * n_years
    return float(t2 / (1.0 + t2))


def simulate_estimated_kelly(c: float, mu: float, sigma: float, est_years: float,
                             trade_years: float = 30.0, dt: float = 1.0 / 12.0,
                             n_paths: int = 20_000, seed: int = SEED) -> dict:
    """Estimate mu from est_years of data, bet c*f_hat, then live with the TRUE process."""
    if c < 0 or est_years <= 0 or trade_years <= 0:
        raise ValueError("c >= 0, est_years > 0 and trade_years > 0")
    rng = np.random.default_rng(seed)
    mu_hat = mu + sigma / np.sqrt(est_years) * rng.standard_normal(n_paths)
    f = np.maximum(c * mu_hat / sigma ** 2, 0.0)              # no shorting on a bad estimate
    n_steps = int(round(trade_years / dt))
    nu = f * mu - f ** 2 * sigma ** 2 / 2.0
    s = f * sigma
    y = np.zeros(n_paths)
    run_max = np.zeros(n_paths)
    max_dd = np.zeros(n_paths)
    for _ in range(n_steps):
        y = y + nu * dt + s * np.sqrt(dt) * rng.standard_normal(n_paths)
        run_max = np.maximum(run_max, y)
        max_dd = np.maximum(max_dd, run_max - y)
    growth = y / trade_years
    return {"c": c, "f_mean": float(f.mean()), "f_p95": float(np.quantile(f, 0.95)),
            "growth_mean": float(growth.mean()), "growth_median": float(np.median(growth)),
            "p_growth_negative": float(np.mean(growth < 0)),
            "median_max_dd": float(1.0 - np.exp(-np.median(max_dd))),
            "p95_max_dd": float(1.0 - np.exp(-np.quantile(max_dd, 0.95))),
            "theory_growth": expected_growth_estimated(c, mu, sigma, est_years)}


# ---------------------------------------------------------------------------------- demo
if __name__ == "__main__":
    print("=" * 86)
    print("POSITION SIZING AND KELLY  --  the formulas, the drawdown, and the estimated mean")
    print("=" * 86)

    # ---- 1. the discrete case, and what is actually Kelly's
    print("\n1. Discrete Kelly, and an honest attribution")
    print(f"   {'p':>6}{'b':>6}{'f* = (bp-q)/b':>16}{'numeric argmax':>17}{'diff':>10}")
    for p, b in ((0.60, 1.0), (0.55, 1.0), (0.52, 1.0), (0.40, 2.0), (0.25, 5.0)):
        cf = kelly_binary(p, b)
        nm = kelly_discrete(np.array([b, -1.0]), np.array([p, 1.0 - p]))
        print(f"   {p:>6.2f}{b:>6.1f}{cf:>16.6f}{nm:>17.6f}{abs(cf - nm):>10.1e}")
    print("   The closed form is Thorp (1984) - Thorp (2006) p. 391 says so. Kelly (1956)")
    print("   gives the even-money case only, unnumbered, in letters where his p is the")
    print("   probability of ERROR. His G_max = 1 + p log2 p + q log2 q, in BITS:")
    for p in (0.55, 0.60, 0.75):
        print(f"     p = {p:.2f}  ->  G_max = {kelly_max_growth_binary(p):.6f} bits per bet"
              f"   (= {kelly_max_growth_binary(p) * np.log(2):.6f} in nats)")
    print("   A three-outcome bet, which no closed form covers, needs the numeric version:")
    pay, pr = np.array([2.0, 0.0, -1.0]), np.array([0.35, 0.30, 0.35])
    fd = kelly_discrete(pay, pr)
    print(f"     payoffs {pay.tolist()} with probs {pr.tolist()}  ->  f* = {fd:.4f}, "
          f"E[ln] = {float(pr @ np.log1p(fd * pay)):.6f}")
    print(f"     a bet with a non-positive mean gets f* = "
          f"{kelly_discrete(np.array([1.0, -1.0]), np.array([0.5, 0.5])):.1f} exactly")

    # ---- 2. the continuous case and the half-Kelly argument
    MU, SIG = 0.08, 0.20
    fstar = kelly_fraction(MU, SIG)
    gstar = growth_rate(fstar, MU, SIG)
    print(f"\n2. Continuous Kelly at mu = {MU:.0%}, sigma = {SIG:.0%} (excess, r = 0)")
    print(f"   f* = mu/sigma^2 = {fstar:.2f}   SR = {sharpe_ratio(MU, SIG):.2f}   "
          f"g(f*) = mu^2/(2 sigma^2) = {gstar:.4f} = SR^2/2 = "
          f"{sharpe_ratio(MU, SIG) ** 2 / 2:.4f}")
    print(f"   {'c':>6}{'f = c f*':>10}{'g(c f*)':>10}{'g ratio':>10}{'c(2-c)':>10}"
          f"{'Sdev(G)':>10}{'Sdev ratio':>12}{'P(ever <= 1/2)':>16}{'P(2x before 1/2)':>18}")
    sdev_star = SIG * fstar                                       # eq. (7.3): Sdev = s*f
    for c in (0.25, 0.5, 0.75, 1.0, 1.5, 1.99):
        g = growth_rate(c * fstar, MU, SIG)
        sdev = SIG * (c * fstar)
        print(f"   {c:>6.2f}{c * fstar:>10.2f}{g:>10.4f}{g / gstar:>10.4f}"
              f"{float(growth_ratio(c)):>10.4f}{sdev:>10.4f}{sdev / sdev_star:>12.2f}"
              f"{ruin_prob(0.5, c):>16.4f}{double_before_halve(c):>18.4f}")
    print("   g ratio matches c(2-c) and the Sdev ratio is c, both exactly - Thorp p. 409.")
    print("   Growth is CONCAVE in c and dispersion is LINEAR, which is the whole argument:")
    print("   half Kelly gives up a quarter of the growth for half the dispersion.")
    print(f"   g(2 f*) = {growth_rate(2 * fstar, MU, SIG):.2e} - exactly zero, and it is zero")
    print("   for every mu and sigma. Thorp p. 415, verbatim: \"'half Kelly' has 3/4 the")
    print("   growth rate but much less chance of a big loss. The chance of ever losing half")
    print("   the starting capital is 1/2 for f = f* but only 1/8 for f = f*/2.\"")
    print(f"   Reproduced above: {ruin_prob(0.5, 1.0):.3f} and {ruin_prob(0.5, 0.5):.3f}; and "
          f"P(doubles before halving) {double_before_halve(1.0):.4f} and "
          f"{double_before_halve(0.5):.4f}")
    print("   (Thorp gives 2/3 and 8/9.)")

    # ---- 3. eq. (7.13) checked by simulation, and the quantity it is NOT about
    print("\n3. Thorp eq. (7.13) Prob(V(t)/V0 <= x ever) = x^(2/c - 1), checked by simulation")
    print("   200 years, monthly steps, 20000 paths, with a Brownian-bridge correction for")
    print("   crossings that happen inside a step")
    print(f"   {'c':>6}{'x':>6}{'formula':>10}{'simulated':>12}{'naive (no bridge)':>20}"
          f"{'bridge error':>14}")
    for c, x in ((1.0, 0.5), (0.5, 0.5), (0.25, 0.5), (1.0, 0.25), (0.5, 0.25)):
        r = simulate_ruin(c, MU, SIG, x)
        print(f"   {c:>6.2f}{x:>6.2f}{r['p_formula']:>10.4f}{r['p_bridge']:>12.4f}"
              f"{r['p_naive']:>20.4f}{r['p_bridge'] - r['p_formula']:>+14.4f}")
    print("   The formula holds. Two things it is easy to get wrong about it:")
    print("   ! Sampling monthly and taking min(wealth) MISSES crossings between samples -")
    print("     the naive column is materially below the truth. Any drawdown study on")
    print("     discretely sampled data has this bias, in this direction.")
    r1 = simulate_ruin(1.0, MU, SIG, 0.5)
    r5 = simulate_ruin(0.5, MU, SIG, 0.5)
    print(f"   ! eq. (7.13) is about the INITIAL wealth. A 50% drawdown FROM THE RUNNING PEAK")
    print(f"     happens on {r1['p_dd_from_peak']:.1%} of full-Kelly paths and "
          f"{r5['p_dd_from_peak']:.1%} of half-Kelly paths over 200 years,")
    print(f"     against the formula's {r1['p_formula']:.1%} and {r5['p_formula']:.1%}. Over an "
          f"unbounded horizon the peak-relative")
    print("     probability tends to 1 for ANY c, because log wealth minus its running")
    print("     maximum is positive-recurrent. Do not quote x^(2/c-1) as a drawdown number.")
    print(f"     Median maximum drawdown over 200 years: full Kelly "
          f"{r1['median_max_dd']:.1%}, half Kelly {r5['median_max_dd']:.1%}.")

    # ---- 4. TRAP 1 - full Kelly on an estimated mean
    print("\n4. TRAP 1 - f* computed from an ESTIMATED mean, and bet in full")
    print(f"   true mu = {MU:.0%}, sigma = {SIG:.0%}, mu estimated from N years, then held")
    print("   fixed and traded for 30 years. Exact expected growth under this model:")
    print("       E[g] = g(f*) * c(2 - c) - c^2 / (2N)")
    print("   the second term is the price of not knowing mu, and it depends on NOTHING but N.")
    for est_years in (10.0, 30.0):
        t = sharpe_ratio(MU, SIG) * np.sqrt(est_years)
        print(f"\n   N = {est_years:.0f} years   t-stat of the mean estimate = {t:.2f}")
        print(f"   {'c':>6}{'mean f':>9}{'growth mean':>13}{'theory':>10}{'median':>9}"
              f"{'P(g<0)':>9}{'median maxDD':>14}{'95th maxDD':>12}")
        for c in (1.0, 0.5, 0.25):
            r = simulate_estimated_kelly(c, MU, SIG, est_years)
            print(f"   {c:>6.2f}{r['f_mean']:>9.2f}{r['growth_mean']:>13.4f}"
                  f"{r['theory_growth']:>10.4f}{r['growth_median']:>9.4f}"
                  f"{r['p_growth_negative']:>9.1%}{r['median_max_dd']:>14.1%}"
                  f"{r['p95_max_dd']:>12.1%}")
        c_opt = optimal_c_estimated(MU, SIG, est_years)
        print(f"   optimal c = t^2/(1 + t^2) = {c_opt:.3f}   "
              f"E[g] there = {expected_growth_estimated(c_opt, MU, SIG, est_years):.4f} "
              f"vs {expected_growth_estimated(1.0, MU, SIG, est_years):.4f} at full Kelly")
    print("\n   ! 'growth mean' sits above 'theory' because the simulation floors f at zero -")
    print("     it refuses to short on a negative estimate, and the closed form does not.")
    print("     The floor helps most exactly where the estimate is worst, which is why the")
    print("     gap is widest at c = 1 and N = 10. It does not rescue the drawdowns.")
    print("\n   The shrinkage is not a preference. c* = t^2/(1 + t^2), where t is the")
    print("   t-statistic of your own mean estimate: t = 1 gives EXACTLY half Kelly, t = 2")
    print("   gives 0.8, and t -> infinity gives full Kelly. Derived here under a stated")
    print("   model - normal estimation error, sigma known, one estimate held fixed - and")
    print("   matched by the simulation column above. It is not quoted from a source.")
    print("   Thorp p. 411 arrives at the same practical place from Figure 5: 'A disaster")
    print("   occurs when m_t = .5 m_e but we choose f = 1.5 f*_e ... we will be ruined.'")

    # ---- 5. TRAP 2 - a Sharpe ratio is not a Kelly fraction
    print("\n5. TRAP 2 - betting f = SR because 'the Sharpe ratio is 0.5'")
    print("   f* = mu/sigma^2 = SR/sigma, so f = SR is wrong by a factor of 1/sigma.")
    SR = 0.5
    print(f"   at SR = {SR}:")
    print(f"   {'sigma':>8}{'mu':>8}{'f* = SR/sigma':>16}{'f = SR':>9}{'f/f*':>8}"
          f"{'g(f*)':>10}{'g(SR)':>10}{'kept':>8}")
    for sig in (0.10, 0.20, 0.50, 1.00, 2.00):
        mu = SR * sig
        fs = kelly_fraction(mu, sig)
        gs, gg = growth_rate(fs, mu, sig), growth_rate(SR, mu, sig)
        print(f"   {sig:>8.0%}{mu:>8.1%}{fs:>16.2f}{SR:>9.2f}{SR / fs:>8.2f}"
              f"{gs:>10.4f}{gg:>10.4f}{gg / gs:>8.0%}")
    print("   At equity volatility it is a large UNDER-bet - 10% vol keeps 19% of the")
    print("   available growth. It is only right at sigma = 1 (100% annual volatility), where")
    print("   f* = SR/1 = SR by coincidence. And at sigma = 2 it is EXACTLY double Kelly, so")
    print("   the growth rate is exactly zero - the same wealth forever, with unbounded")
    print("   oscillation. That is the number to carry: the error is a factor of 1/sigma.")
    print("   The same identity read the other way: volatility targeting is a Kelly bet when,")
    print("   and only when, the volatility target equals the Sharpe ratio.")
    print(f"   {'vol target':>12}{'f = v/sigma at sigma=20%':>27}{'f* at SR=0.5':>15}"
          f"{'equal?':>9}")
    for v in (0.10, 0.30, 0.50, 0.70):
        f_v = vol_target_fraction(v, 0.20)
        f_k = kelly_fraction(SR * 0.20, 0.20)
        print(f"   {v:>12.0%}{f_v:>27.2f}{f_k:>15.2f}{'yes' if abs(f_v - f_k) < 1e-9 else 'no':>9}")

    print("\nRule: f* = SR/sigma, not SR; shrink it by t^2/(1+t^2) for the t-stat of your own"
          " mean estimate; and x^(2/c-1) is the chance of ever halving your STARTING stake,"
          " not a drawdown.")
