# GENERATED by scripts/build_package.py from plugins/fin-models/skills/factor-models/scripts/factor_regression.py - do not edit here.
# Edit the skill script and rerun the generator; validate.py checks they match.
# Owning skill: factor-models (fin_skills.load('factor-models') returns its SKILL.md).

"""Form factor portfolios in calendar order, then test the alpha with standard errors that
admit serial correlation.

WHY this exists: the most common factor-research bug is not a wrong formula, it is a wrong
subscript. A long-short "value" portfolio sorted on book-to-market measured at the END of the
month whose return it earns is not a value strategy; it is the list of the stocks that fell
this month, and its alpha t-statistic is enormous and meaningless. The rule is one line:

    characteristic known at t  ->  portfolio formed at t  ->  return measured over t -> t+1

Everything here is numpy / pandas with a fixed seed. statsmodels is optional: when it is
importable, the Newey-West covariance below is checked against
`OLS(...).fit(cov_type="HAC", cov_kwds={"maxlags": L})` and the comparison is printed.

What the module provides:

    simulate_panel        a 500-stock, 240-month panel in which the TRUTH is alpha = 0 and
                          there is no value premium: r_it = beta_i * m_t + e_it, and
                          book-to-market is a slow book value over a market cap that moves
                          with the stock's own returns
    sort_portfolio        quantile long-short on a characteristic. lag=0 (the leak) is refused
                          unless allow_lookahead=True, so a guard can wrap it
    momentum              cumulative return over the window ENDING at t, the characteristic
                          whose contemporaneous version is the classic momentum bug
    fama_french_2x3       SMB and HML from six value-weight size x book-to-market portfolios,
                          using the two averaging formulas on Ken French's factor page,
                          with rebalance=12 for his once-a-year end-of-June re-form
    newey_west            OLS with the Bartlett / Newey-West HAC covariance in statsmodels'
                          convention: weights 1 - j/(L+1) for j = 0..L, no small-sample
                          correction unless asked
    ts_alpha              time-series regression of a strategy on factors: alpha, betas, HAC t
    fama_macbeth          cross-sectional slopes every period, Newey-West t on the slope series
    french_period_index   the Data Library's YYYYMM / YYYYMMDD dates as a monthly PeriodIndex /
                          DatetimeIndex, so a month-end strategy series joins on the month and
                          not on a first-of-month timestamp that matches nothing
    align_monthly         the join itself, on calendar months

Run:  python factor_regression.py    (fixed seed, no network, about 3 s)
"""
from __future__ import annotations

import time
import warnings

import numpy as np
import pandas as pd

PERIODS = 12          # monthly panel
SEED = 0
N_STOCKS = 500
N_MONTHS = 240


# ------------------------------------------------------------------ synthetic panel ----------
def simulate_panel(n_stocks: int = N_STOCKS, n_months: int = N_MONTHS, seed: int = SEED,
                   market_premium: float = 0.005, market_vol: float = 0.045) -> dict:
    """A monthly panel in which nothing but market beta is priced.

    ret[t, i] is stock i's return over month t (end of t-1 to end of t). mcap[t, i] and
    bm[t, i] are market cap and book-to-market at the END of month t, i.e. after ret[t] has
    happened. A characteristic "known at t" for a portfolio earning ret[t + 1] is row t.
    Book equity is a slow random walk, so book-to-market moves almost entirely with the
    stock's own price and carries no information about future returns by construction.
    """
    rng = np.random.default_rng(seed)
    beta = rng.normal(1.0, 0.3, n_stocks)
    log_size0 = rng.normal(0.0, 1.5, n_stocks)
    small = 1.0 / (1.0 + np.exp(log_size0))
    idio_vol = 0.05 + 0.07 * small                    # 5 %/month for giants, 12 % for minnows
    market = rng.normal(market_premium, market_vol, n_months)
    resid = rng.normal(size=(n_months, n_stocks)) * idio_vol
    ret = beta[None, :] * market[:, None] + resid
    mcap0 = 1000.0 * np.exp(log_size0)
    mcap = mcap0[None, :] * np.cumprod(1.0 + ret, axis=0)
    book0 = mcap0 * np.exp(rng.normal(np.log(0.7), 0.5, n_stocks))
    book = book0[None, :] * np.exp(np.cumsum(rng.normal(0.0, 0.01, (n_months, n_stocks)), axis=0))
    return {"ret": ret, "mcap": mcap, "bm": book / mcap, "beta": beta, "market": market,
            "idio_vol": idio_vol}


def market_return(ret: np.ndarray, mcap: np.ndarray) -> pd.Series:
    """Value-weight market return over month t using caps at the end of t-1 (index 1..T-1)."""
    w = mcap[:-1]
    r = (w * ret[1:]).sum(axis=1) / w.sum(axis=1)
    return pd.Series(r, index=np.arange(1, ret.shape[0]), name="mkt")


# ------------------------------------------------------------------ portfolio formation ------
def _lookahead_guard(lag: int, allow_lookahead: bool) -> None:
    if lag < 1 and not allow_lookahead:
        raise ValueError(
            f"lag={lag}: the sorting characteristic would be measured at the end of the return "
            "period it is supposed to predict (a one-period look-ahead). Characteristic known "
            "at t, portfolio formed at t, return measured t->t+1 means lag >= 1. Pass "
            "allow_lookahead=True only to MEASURE the leak.")


def _weighted_mean(mask: np.ndarray, weights: np.ndarray, ret: np.ndarray) -> np.ndarray:
    """Weighted mean of ret over the masked names; NaN for a period with an empty side."""
    num = (mask * weights * ret).sum(axis=1)
    den = (mask * weights).sum(axis=1)
    return np.divide(num, den, out=np.full_like(num, np.nan), where=den != 0.0)


def sort_portfolio(char: np.ndarray, ret: np.ndarray, mcap: np.ndarray | None = None,
                   lag: int = 1, quantiles: tuple[float, float] = (0.3, 0.7),
                   weighting: str = "value", allow_lookahead: bool = False) -> pd.DataFrame:
    """Long the top quantile of `char`, short the bottom quantile, re-sorted every period.

    ret[t] is the return over period t; the portfolio earning it is sorted on char[t - lag]
    and (for value weighting) weighted by mcap[t - lag]. lag=1 is the honest construction:
    the characteristic and the weights are known when the position is put on. lag=0 sorts
    on a characteristic that already contains the return being measured.
    Returns columns long, short, ls indexed by the return period t.
    """
    char, ret = np.asarray(char, float), np.asarray(ret, float)
    if char.shape != ret.shape:
        raise ValueError("char and ret must both be (n_periods, n_stocks)")
    _lookahead_guard(lag, allow_lookahead)
    if weighting == "value":
        if mcap is None:
            raise ValueError("weighting='value' needs mcap with the same shape as ret")
        w_all = np.asarray(mcap, float)
    elif weighting == "equal":
        w_all = np.ones_like(ret)
    else:
        raise ValueError("weighting must be 'value' or 'equal'")
    n = ret.shape[0]
    c, w, r = char[:n - lag], w_all[:n - lag], ret[lag:]
    with warnings.catch_warnings():
        # a period with no observed characteristic (a signal's warm-up) is an all-NaN slice;
        # its breakpoints are NaN, every mask is False, and _weighted_mean returns NaN.
        warnings.simplefilter("ignore", RuntimeWarning)
        lo = np.nanquantile(c, quantiles[0], axis=1)
        hi = np.nanquantile(c, quantiles[1], axis=1)
    long = _weighted_mean(c >= hi[:, None], w, r)
    short = _weighted_mean(c <= lo[:, None], w, r)
    out = pd.DataFrame({"long": long, "short": short, "ls": long - short},
                       index=pd.Index(np.arange(lag, n), name="t"))
    out.attrs.update(lag=lag, weighting=weighting, quantiles=tuple(quantiles))
    return out


def fama_french_2x3(size: np.ndarray, bm: np.ndarray, ret: np.ndarray, mcap: np.ndarray,
                    lag: int = 1, rebalance: int = 1,
                    allow_lookahead: bool = False) -> pd.DataFrame:
    """Six value-weight portfolios (2 size groups x 3 book-to-market groups) and the factors.

    Size splits at the cross-sectional median, book-to-market at the 30th and 70th
    percentiles, both of the characteristic observed `lag` periods before the return.
    SMB = 1/3 (SV + SN + SG) - 1/3 (BV + BN + BG);  HML = 1/2 (SV + BV) - 1/2 (SG + BG).
    `rebalance=k` holds the group assignment for k return periods (k=12 is Ken French's
    once-a-year end-of-June re-form); the value weights still come from period t - lag.
    French uses NYSE-only breakpoints on a CRSP universe; this uses full-universe
    breakpoints, so it reproduces the construction, not the sample.
    """
    _lookahead_guard(lag, allow_lookahead)
    if rebalance < 1:
        raise ValueError("rebalance must be >= 1 periods")
    size, bm, ret, mcap = (np.asarray(a, float) for a in (size, bm, ret, mcap))
    n = ret.shape[0]
    s, b, w, r = size[:n - lag], bm[:n - lag], mcap[:n - lag], ret[lag:]
    form = (np.arange(n - lag) // rebalance) * rebalance     # most recent formation row <= i
    s, b = s[form], b[form]
    med = np.nanmedian(s, axis=1)[:, None]
    b30 = np.nanquantile(b, 0.3, axis=1)[:, None]
    b70 = np.nanquantile(b, 0.7, axis=1)[:, None]
    small, big = s <= med, s > med
    growth, value = b <= b30, b >= b70
    neutral = ~growth & ~value
    ports = {"SG": small & growth, "SN": small & neutral, "SV": small & value,
             "BG": big & growth, "BN": big & neutral, "BV": big & value}
    df = pd.DataFrame({k: _weighted_mean(m, w, r) for k, m in ports.items()},
                      index=pd.Index(np.arange(lag, n), name="t"))
    df["SMB"] = (df.SV + df.SN + df.SG) / 3.0 - (df.BV + df.BN + df.BG) / 3.0
    df["HML"] = (df.SV + df.BV) / 2.0 - (df.SG + df.BG) / 2.0
    df.attrs.update(lag=lag, rebalance=rebalance)
    return df


def momentum(ret: np.ndarray, lookback: int = 11) -> np.ndarray:
    """Cumulative return over the `lookback` periods ENDING at t, as a characteristic at t.

    Row t is (1 + r[t-lookback+1]) ... (1 + r[t]) - 1, so it contains r[t]. Combined with
    `sort_portfolio(..., lag=1)` the signal is months t-11..t-1 for a return earned in month
    t, which is the honest 11-1 momentum; `lag=0` is the classic bug where the formation
    window's last month IS the month being predicted.
    """
    ret = np.asarray(ret, float)
    if lookback < 1:
        raise ValueError("lookback must be >= 1 period")
    cum = np.cumsum(np.log1p(ret), axis=0)
    lagged = np.vstack([np.zeros((lookback, ret.shape[1])), cum[:-lookback]])
    out = np.expm1(cum - lagged)
    out[:lookback - 1] = np.nan                      # not enough history to form the signal
    return out


# ------------------------------------------------------------------ regressions --------------
def nw_lags(nobs: int) -> int:
    """floor(4 (T/100)^(2/9)): the rule statsmodels applies when nlags is None (which
    `fit(cov_type="HAC")` never passes - there `maxlags` is required)."""
    return int(np.floor(4.0 * (nobs / 100.0) ** (2.0 / 9.0)))


def newey_west(y: np.ndarray, X: np.ndarray, lags: int | None = None,
               use_correction: bool = False) -> dict:
    """OLS with the Newey-West (Bartlett kernel) HAC covariance.

    S = sum_j w_j (G_j + G_j'), G_j = sum_t x_t u_t u_{t-j} x_{t-j}', w_j = 1 - j/(L+1),
    cov = (X'X)^-1 S (X'X)^-1, optionally scaled by T/(T-k). This is what statsmodels'
    `cov_hac_simple` computes; `fit(cov_type="HAC", cov_kwds={"maxlags": L})` calls it with
    use_correction=False, while calling `cov_hac_simple` directly defaults to True.
    """
    y = np.asarray(y, float).ravel()
    X = np.asarray(X, float)
    if X.ndim == 1:
        X = X[:, None]
    nobs, k = X.shape
    if lags is None:
        lags = nw_lags(nobs)
    beta = np.linalg.lstsq(X, y, rcond=None)[0]
    u = y - X @ beta
    xu = X * u[:, None]
    S = xu.T @ xu
    for j in range(1, lags + 1):
        g = xu[j:].T @ xu[:-j]
        S += (1.0 - j / (lags + 1.0)) * (g + g.T)
    xtx_inv = np.linalg.inv(X.T @ X)
    cov = xtx_inv @ S @ xtx_inv
    if use_correction:
        cov *= nobs / float(nobs - k)
    se = np.sqrt(np.diag(cov))
    return {"beta": beta, "se": se, "t": beta / se, "cov": cov, "lags": lags, "nobs": nobs,
            "resid": u}


def ts_alpha(strategy: np.ndarray, factors: np.ndarray, lags: int | None = None) -> dict:
    """Regress a strategy's (excess) return on factor returns; alpha and its HAC t-stat."""
    f = np.asarray(factors, float)
    if f.ndim == 1:
        f = f[:, None]
    X = np.column_stack([np.ones(len(f)), f])
    res = newey_west(strategy, X, lags)
    return {"alpha": float(res["beta"][0]), "alpha_se": float(res["se"][0]),
            "alpha_t": float(res["t"][0]), "betas": res["beta"][1:], "beta_t": res["t"][1:],
            "lags": res["lags"], "nobs": res["nobs"]}


def statsmodels_hac_check(y: np.ndarray, X: np.ndarray, lags: int) -> dict | None:
    """Compare newey_west with statsmodels' HAC fit. None when statsmodels is not installed."""
    try:
        import statsmodels.api as sm
    except ImportError:
        return None
    res = sm.OLS(y, X).fit(cov_type="HAC", cov_kwds={"maxlags": lags})
    mine = newey_west(y, X, lags)
    try:
        sm.OLS(y, X).fit(cov_type="HAC")
        no_maxlags = "accepted"
    except KeyError as e:
        no_maxlags = f"KeyError: {e}"
    import statsmodels.stats.sandwich_covariance as sw
    direct = np.sqrt(np.diag(sw.cov_hac_simple(sm.OLS(y, X).fit(), nlags=lags)))
    return {"max_abs_se_diff": float(np.max(np.abs(np.asarray(res.bse) - mine["se"]))),
            "max_abs_beta_diff": float(np.max(np.abs(np.asarray(res.params) - mine["beta"]))),
            "description": str(res.cov_kwds.get("description", "")),
            "fit_without_maxlags": no_maxlags,
            "direct_over_fit_se_ratio": float(np.mean(direct / np.asarray(res.bse))),
            "sqrt_T_over_T_minus_k": float(np.sqrt(len(y) / (len(y) - X.shape[1])))}


def fama_macbeth(ret: np.ndarray, chars: dict[str, np.ndarray], lag: int = 1,
                 lags: int | None = None, allow_lookahead: bool = False) -> pd.DataFrame:
    """Cross-sectional regression of ret[t] on chars[t - lag] every period; the average
    slope, its naive standard error, and the Newey-West standard error of the slope series."""
    _lookahead_guard(lag, allow_lookahead)
    ret = np.asarray(ret, float)
    names = list(chars)
    n = ret.shape[0]
    r = ret[lag:]
    xs = [np.asarray(chars[k], float)[:n - lag] for k in names]
    gam = np.full((n - lag, len(names) + 1), np.nan)
    for i in range(n - lag):
        X = np.column_stack([np.ones(r.shape[1])] + [x[i] for x in xs])
        y = r[i]
        ok = np.isfinite(y) & np.all(np.isfinite(X), axis=1)
        gam[i] = np.linalg.lstsq(X[ok], y[ok], rcond=None)[0]
    nper = len(gam)
    if lags is None:
        lags = nw_lags(nper)
    mean = gam.mean(axis=0)
    se_plain = gam.std(axis=0, ddof=1) / np.sqrt(nper)
    se_nw = np.array([newey_west(gam[:, j], np.ones((nper, 1)), lags)["se"][0]
                      for j in range(gam.shape[1])])
    out = pd.DataFrame({"mean": mean, "se_plain": se_plain, "t_plain": mean / se_plain,
                        "se_nw": se_nw, "t_nw": mean / se_nw}, index=["const"] + names)
    out.attrs.update(n_periods=nper, lags=lags, lag=lag)
    return out


# ------------------------------------------------------------------ Ken French dates ---------
def french_period_index(values, frequency: str = "monthly"):
    """Parse the Data Library's date column: YYYYMM (monthly files) or YYYYMMDD (daily).

    The monthly stamp names a MONTH. `pd.to_datetime("202607", format="%Y%m")` returns
    2026-07-01, a first-of-month timestamp that never equals a month-end strategy date, so
    monthly factors come back as a PeriodIndex(freq="M") and are joined on the period.
    """
    s = pd.Index(np.asarray(values)).astype(str).str.strip()
    if frequency == "monthly":
        return pd.PeriodIndex(pd.to_datetime(s, format="%Y%m"), freq="M")
    if frequency == "daily":
        return pd.DatetimeIndex(pd.to_datetime(s, format="%Y%m%d"))
    raise ValueError("frequency must be 'monthly' or 'daily'")


def align_monthly(strategy: pd.Series, factors: pd.DataFrame) -> pd.DataFrame:
    """Inner-join a month-end strategy series to monthly factors on the calendar month."""
    s = strategy.copy()
    s.index = pd.DatetimeIndex(s.index).to_period("M")
    f = factors.copy()
    if not isinstance(f.index, pd.PeriodIndex):
        f.index = pd.DatetimeIndex(f.index).to_period("M")
    return pd.concat([s.rename("strategy"), f], axis=1, join="inner")


# ------------------------------------------------------------------ demo ---------------------
HDR = (f"{'formation':<47} {'mean %/mo':>9} {'NW t':>7} {'CAPM a %':>9} {'HAC t':>7} {'beta':>6}")


def _row(label: str, ls: pd.Series, mkt: pd.Series, lags: int) -> str:
    both = pd.concat([ls, mkt], axis=1, join="inner").dropna().to_numpy()
    y, m = both[:, 0], both[:, 1]
    mean_t = newey_west(y, np.ones((len(y), 1)), lags)["t"][0]
    capm = ts_alpha(y, m, lags)
    return (f"{label:<47} {100 * y.mean():>+9.3f} {mean_t:>7.2f} {100 * capm['alpha']:>+9.3f} "
            f"{capm['alpha_t']:>7.2f} {capm['betas'][0]:>6.2f}")


if __name__ == "__main__":
    t0 = time.time()
    panel = simulate_panel()
    ret, mcap, bm = panel["ret"], panel["mcap"], panel["bm"]
    n_months, n_stocks = ret.shape
    mkt = market_return(ret, mcap)
    lags = nw_lags(n_months - 1)
    print("=" * 100)
    print(f"PANEL: {n_stocks} stocks x {n_months} months, seed {SEED}. TRUTH: r_it = beta_i m_t + e_it,"
          f" alpha = 0, no value premium.")
    print(f"       book-to-market = book / market cap, so it moves with the stock's own price;"
          f" Newey-West lags = floor(4(T/100)^(2/9)) = {lags}")
    print("=" * 100)

    # ---------------------------------------------------------------- 1. the look-ahead sort
    print("\n1. LONG-SHORT ON BOOK-TO-MARKET: top 30 % minus bottom 30 %, re-sorted monthly")
    print(HDR)
    print("-" * 100)
    rows = [("lag 1, value-weight  (characteristic at t-1)", 1, "value", False),
            ("lag 1, equal-weight", 1, "equal", False),
            ("lag 6, value-weight  (Fama-French style delay)", 6, "value", False),
            ("LEAK lag 0, value-weight (characteristic at t)", 0, "value", True),
            ("LEAK lag 0, equal-weight", 0, "equal", True)]
    results = {}
    for label, lag, wt, allow in rows:
        ls = sort_portfolio(bm, ret, mcap, lag=lag, weighting=wt, allow_lookahead=allow)["ls"]
        results[label] = ls
        print(_row(label, ls, mkt, lags))
    print("-" * 100)
    y_leak = pd.concat([results[rows[3][0]], mkt], axis=1, join="inner").to_numpy()
    y_ok = pd.concat([results[rows[0][0]], mkt], axis=1, join="inner").to_numpy()
    a_leak = ts_alpha(y_leak[:, 0], y_leak[:, 1], lags)
    a_ok = ts_alpha(y_ok[:, 0], y_ok[:, 1], lags)
    print(f"With the leak the value-weight 'value' portfolio shows CAPM alpha"
          f" {100 * a_leak['alpha']:+.3f} %/month (t = {a_leak['alpha_t']:.2f}); formed honestly,"
          f" {100 * a_ok['alpha']:+.3f} % (t = {a_ok['alpha_t']:.2f}). The truth is 0.")
    print("The sign is negative because a stock that fell this month has a HIGHER book-to-market at the")
    print("end of the month: the leaked 'value' sort is a list of this month's losers. Sort the same")
    print("panel on a signal whose leak points the other way and it reads as a huge premium:")
    mom = momentum(ret, 11)
    mom_ok = sort_portfolio(mom, ret, mcap, lag=1)["ls"]
    mom_leak = sort_portfolio(mom, ret, mcap, lag=0, allow_lookahead=True)["ls"]
    print(_row("11-month momentum, lag 1 (months t-11..t-1)", mom_ok, mkt, lags))
    print(_row("LEAK 11-month momentum, lag 0 (t-10..t)", mom_leak, mkt, lags))
    try:
        sort_portfolio(bm, ret, mcap, lag=0)
    except ValueError as e:
        print(f"\nthe guard: sort_portfolio(..., lag=0) -> ValueError: {str(e)[:96]}...")

    # ---------------------------------------------------------------- 2. the 2x3 sort
    print("\n2. FAMA-FRENCH 2x3: six value-weight portfolios, SMB and HML by the Data Library formulas")
    print(HDR)
    print("-" * 100)
    ff_ok = fama_french_2x3(mcap, bm, ret, mcap, lag=1)
    ff_ann = fama_french_2x3(mcap, bm, ret, mcap, lag=1, rebalance=12)
    ff_leak = fama_french_2x3(mcap, bm, ret, mcap, lag=0, allow_lookahead=True)
    for name in ("SMB", "HML"):
        print(_row(f"{name}, lag 1, re-sorted every month", ff_ok[name], mkt, lags))
        print(_row(f"{name}, lag 1, re-sorted every 12 months", ff_ann[name], mkt, lags))
        print(_row(f"{name}, LEAK lag 0", ff_leak[name], mkt, lags))
    print("-" * 100)
    print("SMB leaks too, through the size sort: a stock that fell is 'small' at the end of the month.")
    print("Ken French re-forms the six portfolios once a year at the end of June, so a monthly re-sort")
    print("is a different portfolio from the published one even when the formulas match.")

    # ---------------------------------------------------------------- 3. HAC conventions
    print("\n3. NEWEY-WEST STANDARD ERRORS: this module vs statsmodels")
    y = y_ok[:, 0]
    X = np.column_stack([np.ones(len(y)), y_ok[:, 1]])
    chk = statsmodels_hac_check(y, X, lags)
    if chk is None:
        print("statsmodels is not installed here; the numpy Newey-West above is the reference and"
              " the cross-check is skipped.")
    else:
        print(f"max |SE difference| vs OLS(...).fit(cov_type='HAC', cov_kwds={{'maxlags': {lags}}}):"
              f" {chk['max_abs_se_diff']:.2e}   (coefficients: {chk['max_abs_beta_diff']:.2e})")
        print(f"statsmodels describes it as: '{chk['description']}'")
        print(f"fit(cov_type='HAC') with no maxlags -> {chk['fit_without_maxlags']} (it is required,"
              f" the floor(4(T/100)^(2/9)) default only applies to cov_hac_simple(nlags=None))")
        print(f"cov_hac_simple(res, nlags={lags}) SE / fit() SE = {chk['direct_over_fit_se_ratio']:.8f}"
              f" = sqrt(T/(T-k)) = {chk['sqrt_T_over_T_minus_k']:.8f}: the direct call applies the"
              f" small-sample correction by default, fit() does not")
    mine0 = newey_west(y, X, 0)
    mine_ols = np.sqrt(np.diag(np.linalg.inv(X.T @ X)) * (mine0["resid"] @ mine0["resid"]) / (len(y) - 2))
    print(f"lags=0 is White's HC0 (SE {mine0['se'][0]:.6f} for alpha); plain OLS SE {mine_ols[0]:.6f};"
          f" HAC({lags}) SE {newey_west(y, X, lags)['se'][0]:.6f}")

    # ---------------------------------------------------------------- 4. Fama-MacBeth
    print("\n4. FAMA-MACBETH: monthly cross-sections of r_it on log(B/M) and log(cap), average slope")
    chars = {"log_bm": np.log(bm), "log_cap": np.log(mcap)}
    fm_ok = fama_macbeth(ret, chars, lag=1)
    fm_leak = fama_macbeth(ret, chars, lag=0, allow_lookahead=True)
    cols = f"{'slope x100':>10} {'t plain':>8} {'t NW':>8}"
    print(f"{'':<14} {cols}    {cols}")
    print(f"{'':<14} {'--- characteristic at t-1 ---':>28}    {'--- LEAK: characteristic at t ---':>28}")
    for k in ("log_bm", "log_cap"):
        a, b = fm_ok.loc[k], fm_leak.loc[k]
        print(f"{k:<14} {100 * a['mean']:>+10.3f} {a['t_plain']:>8.2f} {a['t_nw']:>8.2f}    "
              f"{100 * b['mean']:>+10.3f} {b['t_plain']:>8.2f} {b['t_nw']:>8.2f}")
    print(f"({fm_ok.attrs['n_periods']} cross-sections, Newey-West lags"
          f" {fm_ok.attrs['lags']} on the slope series)")

    # ---------------------------------------------------------------- 5. Ken French dates
    print("\n5. KEN FRENCH MONTHLY FILE DATES ARE 'YYYYMM': join on the month, not on a timestamp")
    stamps = [202601, 202602, 202603, 202604, 202605, 202606]
    fac = pd.DataFrame({"Mkt-RF": [1.5, -0.7, 2.1, 0.3, -1.2, 0.8]}, index=stamps)
    naive = fac.copy()
    naive.index = pd.to_datetime(pd.Index(stamps).astype(str), format="%Y%m")
    strat = pd.Series(np.arange(6) / 100.0, index=pd.date_range("2026-01-31", periods=6, freq="ME"))
    joined_naive = pd.concat([strat.rename("strategy"), naive], axis=1, join="inner")
    fac_p = fac.copy()
    fac_p.index = french_period_index(stamps, "monthly")
    joined = align_monthly(strat, fac_p)
    print(f"pd.to_datetime('202607', format='%Y%m') = {pd.to_datetime('202607', format='%Y%m').date()}"
          f" -> inner join with month-end strategy dates keeps {len(joined_naive)} of 6 rows;")
    print(f"french_period_index + align_monthly keeps {len(joined)} of 6. A daily file's YYYYMMDD stamp"
          f" joins on the day.")
    y5 = joined["strategy"].to_numpy()
    x5 = np.column_stack([np.ones(len(joined)), joined["Mkt-RF"].to_numpy()])
    b_pct = newey_west(y5, x5, 0)["beta"][1]
    x5d = np.column_stack([np.ones(len(joined)), joined["Mkt-RF"].to_numpy() / 100.0])
    b_dec = newey_west(y5, x5d, 0)["beta"][1]
    print(f"UNITS: regressing the same decimal strategy on the same column read as percent gives beta"
          f" {b_pct:.6f}, read as a decimal {b_dec:.4f} - a factor of {b_dec / b_pct:.0f}. Check the"
          f" scale of your own download; do not assume it.")

    print("\n" + "=" * 100)
    print("THE RULE:  characteristic at t, portfolio at t, return t->t+1 (lag >= 1); value-weight unless")
    print("           you mean to bet on microcaps; HAC standard errors with maxlags stated; and monthly")
    print("           factors with monthly returns, daily with daily, joined on the period.")
    print("=" * 100)
    print(f"total runtime {time.time() - t0:.1f}s")
