# GENERATED by scripts/build_package.py from plugins/fin-market-data/skills/corporate-actions-processing/scripts/corporate_actions.py - do not edit here.
# Edit the skill script and rerun the generator; validate.py checks they match.
# Owning skill: corporate-actions-processing (fin_skills.load('corporate-actions-processing') returns its SKILL.md).

#!/usr/bin/env python3
"""Corporate actions: adjusted returns versus the actual position ledger.

WHY: a correctly adjusted or total-return series CAN account for the value of a
spin-off or rights issue. It still does not specify what instruments and cash the holder
owns after the event. The examples below deliberately use a parent-only series whose
feed OMITTED the event, not a claim that every vendor does so.

The three measured omitted-event gaps have closed forms:

    spin-off      gap = (spin ratio x SpinCo first close) / parent's last cum price
    rights issue  gap = (rights per share x (TERP - subscription price)) / cum price
    reverse split gap = -(ratio - 1)          when the feed missed it

`market-data-sourcing/scripts/adjustment_check.py` owns the split-and-dividend ratio and
raw-vs-back-vs-forward-adjusted detection. This module starts where one ratio stops being
enough.

Pure numpy / pandas, fixed seed, no network, no file writes.

Usage:
    from corporate_actions import gap_table, merger_treatments, unexplained_jumps

    print(gap_table())                       # the three numbers
    print(merger_treatments()["spread_pp"])  # what a cash merger costs the wrong convention
"""
from __future__ import annotations

from typing import Sequence

import numpy as np
import pandas as pd

SEED = 20260910
ANNUAL_VOL = 0.28

# (name, a single-security price ratio suffices for a simple position update,
# additional position/event information). This is NOT a vendor coverage classification.
ACTION_TAXONOMY: tuple[tuple[str, bool, str], ...] = (
    ("forward split", True, "one ratio"),
    ("reverse split", True, "one ratio, plus a new share count and cash-in-lieu"),
    ("cash dividend", True, "one ratio (and a choice of gross or net of withholding)"),
    ("special dividend", True, "cash entitlement and the vendor adjustment policy"),
    ("stock dividend", True, "one ratio"),
    ("spin-off", False, "a SECOND instrument and its first close"),
    ("rights issue", False, "the subscription price, the ratio and the take-up decision"),
    ("merger - cash", False, "a terminal cash value and a date the instrument stops"),
    ("merger - stock", False, "an exchange ratio into a DIFFERENT instrument"),
    ("ticker change", False, "a permanent identifier; the price series is continuous"),
    ("delisting", False, "a terminal value, which is not the last quoted price"),
)


# --------------------------------------------------------------------------------------
# price paths
# --------------------------------------------------------------------------------------
def _gbm(n: int, s0: float, rng: np.random.Generator, annual_vol: float = ANNUAL_VOL,
         drift: float = 0.0) -> np.ndarray:
    sig = annual_vol / np.sqrt(252.0)
    return s0 * np.exp(np.cumsum(rng.normal(drift / 252.0 - 0.5 * sig ** 2, sig, n)))


def _gbm_from(anchor: float, n: int, rng: np.random.Generator,
              annual_vol: float = ANNUAL_VOL, drift: float = 0.0) -> np.ndarray:
    """A path of length n whose FIRST value is exactly `anchor` (the ex-date print)."""
    return np.concatenate([[anchor], _gbm(n - 1, anchor, rng, annual_vol, drift)])


def _sessions(n: int, start: str = "2024-01-02") -> pd.DatetimeIndex:
    return pd.DatetimeIndex(pd.bdate_range(start, periods=n))


# --------------------------------------------------------------------------------------
# 1. spin-off
# --------------------------------------------------------------------------------------
def spin_off_panel(pre: int = 60, post: int = 60, p0: float = 100.0,
                   value_fraction: float = 0.30, spin_ratio: float = 0.5,
                   seed: int = SEED) -> dict:
    """Parent + SpinCo around an ex-distribution date, with value conserved at the instant.

    `value_fraction` is the share of the parent's market value that leaves. The holder of
    one parent share receives `spin_ratio` SpinCo shares, priced so that
    spin_ratio * spinco_first_close == value_fraction * parent_last_cum_close.
    """
    if pre < 1 or post < 1 or p0 <= 0 or spin_ratio <= 0 or not 0 < value_fraction < 1:
        raise ValueError("need pre/post >= 1, positive prices/ratio, and 0 < fraction < 1")
    rng = np.random.default_rng(seed)
    idx = _sessions(pre + post)
    ex = idx[pre]
    cum = _gbm(pre, p0, rng)
    p_last = float(cum[-1])
    spinco_first = value_fraction * p_last / spin_ratio
    parent_ex = p_last * (1.0 - value_fraction)
    parent_post = _gbm_from(parent_ex, post, rng, drift=0.04)
    spin_post = _gbm_from(spinco_first, post, rng, annual_vol=0.45, drift=-0.02)
    parent = pd.Series(np.concatenate([cum, parent_post]), index=idx, name="parent")
    spinco = pd.Series(np.concatenate([np.full(pre, np.nan), spin_post]), index=idx,
                       name="spinco")
    return {"parent": parent, "spinco": spinco, "ex_date": ex,
            "parent_last_cum": p_last, "parent_ex_open": float(parent_post[0]),
            "spinco_first_close": float(spin_post[0]),
            "spin_ratio": spin_ratio, "value_fraction": value_fraction}


def spin_off_gap(panel: dict | None = None) -> dict:
    """Holder's return minus the event-omitting series' return, on the ex-date and over the window.

    This deliberately event-omitting series books the distribution as a loss.
    A vendor that adjusts this event can remove the ex-date discontinuity.
    """
    p = panel or spin_off_panel()
    parent, spinco, ex = p["parent"], p["spinco"], p["ex_date"]
    i = parent.index.get_loc(ex)
    p_cum, p_ex = float(parent.iloc[i - 1]), float(parent.iloc[i])
    s0 = float(spinco.iloc[i])
    distributed = p["spin_ratio"] * s0

    series_exdate = p_ex / p_cum - 1.0
    holder_exdate = (p_ex + distributed) / p_cum - 1.0

    p_end, s_end = float(parent.iloc[-1]), float(spinco.iloc[-1])
    # An explicit factor removes the ex-date drop but models proceeds reinvested in
    # Parent, not continued ownership of SpinCo. Keep both policies visible.
    factor = p_ex / p_cum
    adjusted = parent.copy()
    adjusted.iloc[:i] *= factor
    adjusted_exdate = float(adjusted.iloc[i] / adjusted.iloc[i - 1] - 1)
    adjusted_window = float(adjusted.iloc[-1] / adjusted.iloc[0] - 1)
    series_window = p_end / float(parent.iloc[0]) - 1.0
    holder_window = (p_end + p["spin_ratio"] * s_end) / float(parent.iloc[0]) - 1.0
    return {
        "event": "spin-off", "ex_date": str(ex.date()),
        "adjusted_return_exdate_pct": round(100 * adjusted_exdate, 4),
        "adjusted_return_window_pct": round(100 * adjusted_window, 4),
        "parent_last_cum": round(p_cum, 4), "parent_ex": round(p_ex, 4),
        "spinco_first_close": round(s0, 4), "distributed_per_share": round(distributed, 4),
        "series_return_exdate_pct": round(100 * series_exdate, 4),
        "holder_return_exdate_pct": round(100 * holder_exdate, 4),
        "gap_pp": round(100 * (holder_exdate - series_exdate), 4),
        "closed_form_pp": round(100 * distributed / p_cum, 4),
        "series_return_window_pct": round(100 * series_window, 4),
        "holder_return_window_pct": round(100 * holder_window, 4),
        "gap_window_pp": round(100 * (holder_window - series_window), 4),
    }


# --------------------------------------------------------------------------------------
# 2. rights issue
# --------------------------------------------------------------------------------------
def terp(cum_price: float, subscription_price: float, rights_per_share: float) -> float:
    """Theoretical ex-rights price: the weighted average of old and new shares."""
    if not all(np.isfinite(v) for v in (cum_price, subscription_price, rights_per_share)):
        raise ValueError("rights terms must be finite")
    if cum_price <= 0 or subscription_price < 0 or rights_per_share < 0:
        raise ValueError("need positive cum price and nonnegative subscription/rights")
    return ((cum_price + rights_per_share * subscription_price)
            / (1.0 + rights_per_share))


def rights_issue_gap(cum_price: float = 100.0, subscription_price: float = 60.0,
                     rights_per_share: float = 0.5) -> dict:
    """The ex-rights drop is real; the loss is not, because the rights have value."""
    t = terp(cum_price, subscription_price, rights_per_share)
    if subscription_price > cum_price:
        raise ValueError("this fully subscribed discounted-rights model requires K <= cum price")
    rights_value = rights_per_share * (t - subscription_price)
    series = t / cum_price - 1.0
    holder = (t + rights_value) / cum_price - 1.0            # sells the rights at TERP - K
    subscriber = ((1.0 + rights_per_share) * t
                  - rights_per_share * subscription_price) / cum_price - 1.0
    return {
        "event": "rights issue", "cum_price": cum_price,
        "subscription_price": subscription_price, "rights_per_share": rights_per_share,
        "terp": round(t, 4), "rights_value_per_share": round(rights_value, 4),
        "series_return_exdate_pct": round(100 * series, 4),
        "holder_return_exdate_pct": round(100 * holder, 4),
        "gap_pp": round(100 * (holder - series), 4),
        "closed_form_pp": round(100 * rights_value / cum_price, 4),
        "subscriber_return_pct": round(100 * subscriber, 4),
        "discount_to_cum_pct": round(100 * (1 - subscription_price / cum_price), 2),
    }


# --------------------------------------------------------------------------------------
# 3. reverse split
# --------------------------------------------------------------------------------------
def reverse_split_gap(ratio: float = 10.0, price: float = 0.80,
                      shares: int = 1237) -> dict:
    """1-for-`ratio`: price x ratio, share count / ratio, the remainder paid in cash."""
    if not np.isfinite(ratio) or ratio < 1 or not np.isfinite(price) or price <= 0:
        raise ValueError("need finite ratio >= 1 and positive price")
    if not isinstance(shares, (int, np.integer)) or isinstance(shares, bool) or shares < 1:
        raise ValueError("shares must be a positive integer")
    new_price = price * ratio
    new_shares = int(shares // ratio)
    fractional = shares / ratio - new_shares
    cash_in_lieu = fractional * new_price
    series = new_price / price - 1.0                          # feed missed it
    holder = ((new_shares * new_price + cash_in_lieu) / (shares * price)) - 1.0
    return {
        "event": "reverse split", "ratio": ratio, "price_before": price,
        "price_after": round(new_price, 4), "shares_before": shares,
        "shares_after": new_shares, "cash_in_lieu": round(cash_in_lieu, 4),
        "series_return_exdate_pct": round(100 * series, 4),
        "holder_return_exdate_pct": round(100 * holder, 6),
        "gap_pp": round(100 * (holder - series), 4),
        "closed_form_pp": round(-100 * (ratio - 1.0), 4),
    }


def gap_table() -> pd.DataFrame:
    """The three numbers: what the holder earned minus what the event-omitting series says."""
    rows = [spin_off_gap(), rights_issue_gap(), reverse_split_gap()]
    return pd.DataFrame([{"event": r["event"],
                          "series_pct": r["series_return_exdate_pct"],
                          "holder_pct": r["holder_return_exdate_pct"],
                          "gap_pp": r["gap_pp"],
                          "closed_form_pp": r["closed_form_pp"]} for r in rows])


# --------------------------------------------------------------------------------------
# 4. the screen: is the feed carrying these events at all?
# --------------------------------------------------------------------------------------
def unexplained_jumps(close: pd.Series, actions: pd.DataFrame | Sequence[tuple] | None,
                      tol: float = 0.20) -> pd.DataFrame:
    """Absolute simple returns past `tol`, with whether an action date is present.

    A feed that reports NO action on a date the price moved 30 % is either missing the
    event or the move was real; you cannot tell from the price alone, which is the point.
    """
    if isinstance(actions, pd.DataFrame):
        dates = set(pd.to_datetime(actions["date"]))
    elif actions:
        dates = set(pd.to_datetime([a[0] for a in actions]))
    else:
        dates = set()
    if not np.isfinite(tol) or tol <= 0:
        raise ValueError("tol must be finite and positive")
    prices = close.astype(float)
    prices = prices.where(np.isfinite(prices) & (prices > 0))
    lr = np.log(prices).diff()
    hits = lr[prices.pct_change(fill_method=None).abs() > tol]
    return pd.DataFrame({
        "date": hits.index,
        "log_move": hits.to_numpy().round(6),
        "pct_move": (100 * (np.exp(hits.to_numpy()) - 1)).round(3),
        "explained_by_feed": [d in dates for d in hits.index],
    }).reset_index(drop=True)


def feed_coverage_demo(seed: int = SEED) -> dict:
    """One instrument, three events, two feeds: an empty one and a splits-only one."""
    p = spin_off_panel(pre=40, post=40, seed=seed)
    parent = p["parent"].copy()
    idx = parent.index
    # graft a rights issue and a reverse split onto the same series
    rights_ex, rsplit_ex = idx[55], idx[70]
    r = rights_issue_gap()
    parent.loc[rights_ex:] *= (r["terp"] / r["cum_price"])
    parent.loc[rsplit_ex:] *= 10.0
    events = {"spin-off": p["ex_date"], "rights issue": rights_ex,
              "reverse split": rsplit_ex}
    empty = unexplained_jumps(parent, None)
    splits_only = unexplained_jumps(parent, [(rsplit_ex, 0.1, "split")])
    caught = set(pd.DatetimeIndex(empty["date"]))
    return {
        "events": {k: str(v.date()) for k, v in events.items()},
        "n_events": len(events), "tol_pct": 20.0,
        "jumps_found": int(len(empty)),
        "events_missed_by_the_screen": [k for k, v in events.items() if v not in caught],
        "unexplained_empty_feed": int((~empty["explained_by_feed"]).sum()),
        "unexplained_splits_only_feed": int((~splits_only["explained_by_feed"]).sum()),
        "table": empty,
    }


def screen_false_positives(n_names: int = 500, n_days: int = 252, df: float = 3.0,
                           annual_vol: float = ANNUAL_VOL,
                           tols: Sequence[float] = (0.20, 0.1333, 0.10),
                           seed: int = SEED) -> pd.DataFrame:
    """"Just lower the threshold" - what that costs on an event-free fat-tailed panel.

    Student-t returns scaled to `annual_vol` are an illustrative heavy-tailed model,
    not a fitted claim about any market. No corporate events were inserted; flags are
    false positives only if interpreted as proof of an event.
    """
    rng = np.random.default_rng(seed)
    sig = annual_vol / np.sqrt(252.0)
    raw = rng.standard_t(df, size=(n_days, n_names))
    r = raw * sig / np.sqrt(df / (df - 2.0))
    rows = []
    for tol in tols:
        n = int((np.abs(r) > tol).sum())
        rows.append({"threshold_pct": round(100 * tol, 2), "flags": n,
                     "flags_per_name_per_year": round(n / n_names, 3),
                     "pct_of_observations": round(100 * n / r.size, 4)})
    return pd.DataFrame(rows)


# --------------------------------------------------------------------------------------
# 5. mergers: the series ends, and the convention decides the sign
# --------------------------------------------------------------------------------------
def merger_treatments(n_names: int = 20, n_days: int = 252, merger_day: int = 120,
                      premium: float = 0.30, seed: int = SEED) -> dict:
    """Same cash merger, three ways a panel can encode "no more data". Three answers."""
    rng = np.random.default_rng(seed)
    idx = _sessions(n_days)
    sig = ANNUAL_VOL / np.sqrt(252.0)
    rets = pd.DataFrame(rng.normal(0.0002, sig, (n_days, n_names)), index=idx,
                        columns=[f"N{i:02d}" for i in range(n_names)])
    target = rets.columns[0]
    rets.loc[idx[merger_day], target] = premium               # the takeover pop
    rets.loc[idx[merger_day + 1]:, target] = 0.0              # then it is cash

    truth = rets
    dropped = rets.copy()
    dropped.loc[idx[merger_day]:, target] = np.nan            # the panel just stops
    delisted = rets.copy()
    delisted.loc[idx[merger_day], target] = -1.0              # "no data" read as a wipeout
    delisted.loc[idx[merger_day + 1]:, target] = 0.0

    def portfolio(frame: pd.DataFrame) -> float:
        w = frame.notna().div(frame.notna().sum(axis=1), axis=0)
        return float((1.0 + (frame.fillna(0.0) * w).sum(axis=1)).prod() - 1.0)

    t, d, x = portfolio(truth), portfolio(dropped), portfolio(delisted)
    return {"n_names": n_names, "premium_pct": 100 * premium, "target": target,
            "truth_pct": round(100 * t, 4), "dropped_pct": round(100 * d, 4),
            "delisted_at_zero_pct": round(100 * x, 4),
            "truth_minus_dropped_pp": round(100 * (t - d), 4),
            "truth_minus_delisted_pp": round(100 * (t - x), 4),
            "spread_pp": round(100 * (max(t, d, x) - min(t, d, x)), 4)}


# --------------------------------------------------------------------------------------
# 6. ticker changes: the price is continuous, the key is not
# --------------------------------------------------------------------------------------
def ticker_change_cost(n_days: int = 756, change_day: int = 252, lookback: int = 252,
                       seed: int = SEED) -> dict:
    """Rename an instrument mid-sample and ask a 252-day momentum signal for a value."""
    rng = np.random.default_rng(seed)
    idx = _sessions(n_days)
    px = pd.Series(_gbm(n_days, 50.0, rng), index=idx, name="continuous")
    old = px.copy()
    old.iloc[change_day:] = np.nan                            # OLD ticker stops here
    new = px.copy()
    new.iloc[:change_day] = np.nan                            # NEW ticker starts here

    def momentum(s: pd.Series) -> pd.Series:
        return s / s.shift(lookback) - 1.0

    keyed_by_ticker = pd.concat([momentum(old), momentum(new)], axis=1).max(axis=1)
    keyed_by_permid = momentum(px)
    tail = slice(change_day, None)
    return {"n_days": n_days, "change_day": str(idx[change_day].date()),
            "lookback": lookback, "sessions_after_change": n_days - change_day,
            "signal_days_after_change_by_ticker":
                int(keyed_by_ticker.iloc[tail].notna().sum()),
            "signal_days_after_change_by_permid":
                int(keyed_by_permid.iloc[tail].notna().sum()),
            "days_out_of_the_universe":
                int(keyed_by_permid.iloc[tail].notna().sum()
                    - keyed_by_ticker.iloc[tail].notna().sum()),
            "old_ticker_looks_delisted_on": str(idx[change_day].date()),
            "new_ticker_looks_like_an_ipo_on": str(idx[change_day].date())}


def ticker_recycling(n_days: int = 300, handover: int = 150, seed: int = SEED) -> dict:
    """A freed symbol reassigned to a different company. Joining on ticker splices them."""
    rng = np.random.default_rng(seed + 1)
    idx = _sessions(n_days)
    a = _gbm(handover, 40.0, rng, drift=-0.55)                # company A fades out
    b = _gbm(n_days - handover, 12.0, rng, drift=0.10)        # company B, a different name
    spliced = pd.Series(np.concatenate([a, b]), index=idx, name="XYZ")
    seam = float(spliced.iloc[handover] / spliced.iloc[handover - 1] - 1.0)
    lr = np.log(spliced).diff().dropna()
    z = float((np.log1p(seam) - lr.mean()) / lr.std(ddof=1))
    return {"handover": str(idx[handover].date()),
            "last_price_company_a": round(float(spliced.iloc[handover - 1]), 4),
            "first_price_company_b": round(float(spliced.iloc[handover]), 4),
            "seam_return_pct": round(100 * seam, 4), "seam_z_score": round(z, 2),
            "note": "one ticker, two companies; the seam is a return that nobody earned"}


# --------------------------------------------------------------------------------------
def _fmt(rows) -> str:
    df = rows if isinstance(rows, pd.DataFrame) else pd.DataFrame(rows)
    return df.to_string(index=False)


if __name__ == "__main__":
    print("=== 0. which actions need position information beyond a price ratio ===")
    print(_fmt([{"action": a, "simple position ratio": "yes" if ok else "NO",
                 "what it actually needs": need} for a, ok, need in ACTION_TAXONOMY]))

    print("\n=== 1. spin-off: the distribution is booked as a loss ===")
    s = spin_off_gap()
    print(f"    ex-date {s['ex_date']}: parent last cum {s['parent_last_cum']}, "
          f"parent ex {s['parent_ex']}, SpinCo first close {s['spinco_first_close']}")
    print(f"    distributed per parent share: {s['distributed_per_share']}")
    print(f"    event-omitting feed says  {s['series_return_exdate_pct']:>9.4f} %")
    print(f"    the holder earned     {s['holder_return_exdate_pct']:>9.4f} %")
    print(f"    gap {s['gap_pp']:.4f} pp == distributed / last cum price = "
          f"{s['closed_form_pp']:.4f} pp  <- the whole spun-off entity, as a loss")
    print(f"    explicitly adjusted ex-date return {s['adjusted_return_exdate_pct']:.4f} %;")
    print("    adjustment can remove the jump; the subsequent holdings still need a ledger.")
    print(f"    over the 120-session window: series {s['series_return_window_pct']:.4f} %, "
          f"holder {s['holder_return_window_pct']:.4f} %, gap {s['gap_window_pp']:.4f} pp")

    print("\n=== 2. rights issue: the drop is real, the loss is not ===")
    r = rights_issue_gap()
    print(f"    {r['rights_per_share']} rights per share at {r['subscription_price']} "
          f"({r['discount_to_cum_pct']} % below the {r['cum_price']} cum price)")
    print(f"    TERP {r['terp']}, rights worth {r['rights_value_per_share']} per share")
    print(f"    event-omitting feed says  {r['series_return_exdate_pct']:>9.4f} %")
    print(f"    holder who SELLS the rights {r['holder_return_exdate_pct']:>9.4f} %  "
          f"(and one who subscribes: {r['subscriber_return_pct']:.4f} %)")
    print(f"    gap {r['gap_pp']:.4f} pp == rights value / cum price = "
          f"{r['closed_form_pp']:.4f} pp")

    print("\n=== 3. reverse split: the same arithmetic with the sign flipped ===")
    rs = reverse_split_gap()
    print(f"    1-for-{int(rs['ratio'])}: {rs['price_before']} -> {rs['price_after']}, "
          f"{rs['shares_before']} shares -> {rs['shares_after']} plus "
          f"{rs['cash_in_lieu']} cash in lieu")
    print(f"    a feed that missed it says {rs['series_return_exdate_pct']:>10.4f} %")
    print(f"    the holder earned          {rs['holder_return_exdate_pct']:>10.4f} %")
    print(f"    gap {rs['gap_pp']:.4f} pp == -(ratio - 1) = {rs['closed_form_pp']:.4f} pp")

    print("\n=== 4. the three numbers, one table ===")
    print(_fmt(gap_table()))
    print("    two of the three make the position look worse than it was; the third makes")
    print("    it look ten times better. None of them is a return anybody earned.")

    print("\n=== 5. is the feed carrying them at all? ===")
    f = feed_coverage_demo()
    print(f"    one instrument, {f['n_events']} events {f['events']}")
    print(f"    one-day moves past {f['tol_pct']:.0f} %: {f['jumps_found']}")
    print(f"    unexplained by an EMPTY action feed      : {f['unexplained_empty_feed']}")
    print(f"    unexplained by a SPLITS-ONLY action feed : "
          f"{f['unexplained_splits_only_feed']}")
    print(_fmt(f["table"]))
    print(f"    the screen MISSES {f['events_missed_by_the_screen']}: a 13.33 % ex-rights "
          f"drop is an")
    print("    ordinary bad day. Lowering the threshold is not free - on an event-free")
    print("    t(3) panel of 500 names at 28 % annual vol:")
    print(_fmt(screen_false_positives()))
    print("    An empty action feed cannot establish that no event occurred. Check source coverage.")

    print("\n=== 6. a cash merger is indistinguishable from a delisting ===")
    m = merger_treatments()
    print(f"    {m['n_names']} equal-weight names, one taken out at a "
          f"{m['premium_pct']:.0f} % premium on day 120")
    print(f"    truth (premium, then cash)      {m['truth_pct']:>9.4f} %")
    print(f"    panel just stops (NaN dropped)  {m['dropped_pct']:>9.4f} %   "
          f"({m['truth_minus_dropped_pp']:+.4f} pp)")
    print(f"    'no data' read as a wipeout     {m['delisted_at_zero_pct']:>9.4f} %   "
          f"({m['truth_minus_delisted_pp']:+.4f} pp)")
    print(f"    spread across the three conventions: {m['spread_pp']:.4f} pp from ONE name")

    print("\n=== 7. a ticker change moves the key, not the price ===")
    t = ticker_change_cost()
    print(f"    renamed on {t['change_day']}; a {t['lookback']}-day momentum signal over "
          f"the following {t['sessions_after_change']} sessions:")
    print(f"      keyed by ticker             : {t['signal_days_after_change_by_ticker']} "
          f"days with a value")
    print(f"      keyed by a permanent id     : {t['signal_days_after_change_by_permid']} "
          f"days")
    print(f"      -> {t['days_out_of_the_universe']} sessions out of the universe, and the "
          f"old ticker looks delisted")
    rc = ticker_recycling()
    print(f"    ticker recycling: company A ends at {rc['last_price_company_a']} on the "
          f"day before {rc['handover']},")
    print(f"      company B starts at {rc['first_price_company_b']} under the SAME symbol "
          f"-> a {rc['seam_return_pct']:.2f} % 'return'")
    print(f"      ({rc['seam_z_score']} sigma; nobody earned it, and no action feed "
          f"explains it)")

    print("\nThe rule: an adjusted close is a price, not a position - carry an event feed "
          "with a row type for spin-offs, rights, mergers and renames, key every series by "
          "a permanent identifier, and REPORT unexplained jumps instead of adjusting them "
          "away.")
