# GENERATED by scripts/build_package.py from plugins/fin-market-data/skills/finding-and-searching-data/scripts/find_data_source.py - do not edit here.
# Edit the skill script and rerun the generator; validate.py checks they match.
# Owning skill: finding-and-searching-data (fin_skills.load('finding-and-searching-data') returns its SKILL.md).

"""Which free source can SEARCH for what - and the three dates a found document carries.

Every adapter in this library fetches by identifier: `bars("AAPL")`, `macro("DGS10")`,
`fundamentals("0000320193")`. That is the second half of the job. The first half is
finding the identifier, and an agent that guesses one is worse off than an agent that
stops: `DGS10` and `DGS10YR` are both plausible, one of them exists, and the wrong guess
comes back as an empty frame rather than an error.

Two tables live here.

  * `SOURCES` - the free, documented search endpoints, each declaring what its free text
    is matched AGAINST and, more usefully, what it cannot do. The `cannot` column is the
    one to read: three of the four cannot answer "as of a past date" at all, so a universe
    built from them is a current snapshot wearing a historical label.
  * `document_dates()` - a found document has THREE dates and they are not
    interchangeable. Feed it rows shaped like the SEC Submissions API's `filings.recent`
    and it returns all three plus the availability the data layer actually keys on.

Offline, seeded, no writes. The fixture is Apple's own filing metadata, copied verbatim
from data.sec.gov; the counts printed at the bottom are computed from it.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Mapping, Sequence

import pandas as pd

EXCHANGE_TZ = "America/New_York"
CLOSE_HOUR = 16


@dataclass(frozen=True)
class Source:
    """One searchable source, and the sentence that keeps you from misusing it."""

    name: str
    endpoint: str
    searches: str            # what the free text is matched against
    returns: str             # the identifier scheme you get back
    credential: str          # what you must supply, and whether it can be shared
    rate_limit: str
    as_of: str               # can it answer about a PAST date?
    cannot: tuple[str, ...]


#: Verified 2026-09-10 against each vendor's own documentation or a live call.
SOURCES: tuple[Source, ...] = (
    Source(
        name="fred_series_search",
        endpoint="https://api.stlouisfed.org/fred/series/search",
        searches="series TITLE, units, frequency and tags, stemmed - not the series id",
        returns="series_id (e.g. DGS10, CPIAUCSL)",
        credential="FRED_API_KEY; FRED's own terms say every user must use their own key",
        rate_limit="no usable published number - the v1 errors page says 120/min, the v2 "
                   "page says 2/s; pace at 2/s to satisfy both",
        as_of="yes - realtime_start/realtime_end filter which series EXISTED then",
        cannot=(
            "match a series id in the default search_type=full_text mode; pass "
            "search_type='series_id' for substring matching with '*' wildcards",
            "return observations - search answers about the series, never its values",
            "be called without a key, and a shared key cannot ship",
        ),
    ),
    Source(
        name="sec_company_tickers",
        endpoint="https://www.sec.gov/files/company_tickers.json",
        searches="ticker and company title, locally, after one download of the whole file",
        returns="ticker and cik",
        credential="none - but a declared User-Agent is required or every request 403s",
        rate_limit="10 requests/second, regardless of the number of machines used",
        as_of="NO - the file is a current snapshot with no dates in it at all",
        cannot=(
            "find a delisted company: Lehman, Bear Stearns and Enron all return an empty "
            "ticker list, so a universe built here is survivorship-biased",
            "say WHEN a ticker mapped to that CIK - there is no date field",
            "tell a common share from a preferred line or an ETN: one CIK's ticker list "
            "mixes them",
        ),
    ),
    Source(
        name="sec_full_text_search",
        endpoint="https://efts.sec.gov/LATEST/search-index",
        searches="the full text of filings AND their exhibits, 2001 onwards",
        returns="accession number and cik",
        credential="none - the same declared User-Agent",
        rate_limit="10 requests/second, shared across every machine you own",
        as_of="the FILING date only (startdt/enddt), which is not when it became public",
        cannot=(
            "reach filings before 2001",
            "tell you when a hit became PUBLIC: a hit carries file_date and no "
            "acceptanceDateTime, so it is not point-in-time until you enrich it",
            "distinguish the primary document from an exhibit - a 10-K query returns "
            "EX-19 and EX-99 attachments under form '10-K'",
        ),
    ),
    Source(
        name="ccxt_markets",
        endpoint="exchange.load_markets() - one venue per instance",
        searches="unified symbol, base, quote and the venue's own market id, locally",
        returns="market symbol (e.g. BTC/USDT, BTC/USD:BTC-260327)",
        credential="none for public market metadata",
        rate_limit="the instance's own leaky bucket: rateLimit ms x endpoint cost",
        as_of="NO - load_markets() returns what the venue lists right now",
        cannot=(
            "find a delisted pair: it is absent from the listing, not flagged inactive",
            "search across venues in one call - the market map belongs to one instance",
            "tell you a pair's history; crypto listings turn over faster than equities",
        ),
    ),
)

#: plain-English need -> the sources that can actually answer it
ROUTES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("a macro series id", ("fred_series_search",)),
    ("a company's CIK from its ticker", ("sec_company_tickers",)),
    ("a ticker from a company name", ("sec_company_tickers",)),
    ("a filing that mentions a phrase", ("sec_full_text_search",)),
    ("a crypto pair or perpetual symbol", ("ccxt_markets",)),
    ("a delisted company", ()),
    ("a futures contract code", ()),
    ("the ticker a CIK used in 2008", ()),
)


def where_to_search(need: str) -> tuple[str, ...]:
    """Sources that can answer `need`, or an empty tuple - which is also an answer."""
    key = str(need).strip().lower()
    if not key:
        return ()                 # an empty need matches everything, which helps nobody
    for label, names in ROUTES:
        if label.lower() == key:
            return names
    hits = tuple(n for label, names in ROUTES if key in label.lower() for n in names)
    return tuple(dict.fromkeys(hits))


def source_table() -> pd.DataFrame:
    return pd.DataFrame([{"source": s.name, "searches": s.searches, "returns": s.returns,
                          "as_of": s.as_of, "cannot": len(s.cannot)} for s in SOURCES])


# --------------------------------------------------------------- the three document dates
def document_dates(filings: Iterable[Mapping], *, tz: str = EXCHANGE_TZ,
                   close_hour: int = CLOSE_HOUR) -> pd.DataFrame:
    """The three dates of each document, plus the one a backtest may key on.

    period_end       what the document COVERS. Months before it exists. Using it is the
                     30-90 day look-ahead that fundamental studies are famous for.
    filed_at         the date EDGAR stamps, assigned by its own cutoff rules. Off by a
                     day in both directions from the moment the document appeared.
    acceptance_at    the wall-clock instant it became public. The truth, and the only one
                     of the three that is an instant rather than a date.
    available_at     the first session it could be traded on: acceptance converted to
                     exchange-local, rolled to the next session when it lands at or after
                     the close. This is the column to join on.
    """
    rows = []
    for f in filings:
        acc = pd.Timestamp(f["acceptanceDateTime"])
        acc = acc.tz_localize("UTC") if acc.tz is None else acc.tz_convert("UTC")
        local = acc.tz_convert(tz)
        post_close = local.hour >= close_hour
        avail = local.normalize().tz_localize(None) + pd.Timedelta(days=1 if post_close else 0)
        while avail.weekday() >= 5:              # no holiday calendar here: pass one in
            avail += pd.Timedelta(days=1)
        filed = pd.Timestamp(f["filingDate"])
        period = pd.to_datetime(f.get("reportDate") or None, errors="coerce")
        rows.append({"accession": f.get("accessionNumber", ""), "form": f.get("form", ""),
                     "period_end": period, "filed_at": filed,
                     "acceptance_local": local.tz_localize(None),
                     "post_close": post_close, "available_at": avail,
                     "period_lag_days": (filed - period).days if pd.notna(period) else -1,
                     "filed_matches_acceptance":
                         filed.normalize() == local.normalize().tz_localize(None)})
    return pd.DataFrame(rows)


#: forms whose reportDate is a fiscal PERIOD end. An 8-K's reportDate is an event date,
#: so pooling the two makes the period-to-filing lag meaningless.
PERIODIC_FORMS = ("10-K", "10-Q", "20-F", "40-F", "10-K/A", "10-Q/A")


def lookahead_summary(dates: pd.DataFrame,
                      periodic: Sequence[str] = PERIODIC_FORMS) -> dict:
    """How much of a document set each shortcut would have bought you for free."""
    n = len(dates)
    if not n:
        return {"n": 0}
    per = dates[(dates["period_lag_days"] >= 0) & dates["form"].isin(tuple(periodic))]
    return {
        "n_periodic": len(per),
        "n": n,
        "post_close": int(dates["post_close"].sum()),
        "post_close_pct": 100.0 * dates["post_close"].sum() / n,
        "filed_disagrees_with_acceptance": int((~dates["filed_matches_acceptance"]).sum()),
        "same_day_post_close": int((dates["post_close"]
                                    & dates["filed_matches_acceptance"]).sum()),
        "median_period_lag_days": float(per["period_lag_days"].median()) if len(per) else float("nan"),
        "max_period_lag_days": int(per["period_lag_days"].max()) if len(per) else -1,
    }


# --------------------------------------------------------------------------- the fixture
#: Apple's own filing metadata, copied verbatim from
#: data.sec.gov/submissions/CIK0000320193.json on 2026-09-10. Nothing is rounded or edited.
AAPL_FILINGS: tuple[dict, ...] = (
    {"form": "10-Q", "accessionNumber": "0000320193-26-000020", "reportDate": "2026-06-27",
     "filingDate": "2026-07-31", "acceptanceDateTime": "2026-07-31T10:01:02.000Z"},
    {"form": "8-K", "accessionNumber": "0000320193-26-000018", "reportDate": "2026-07-30",
     "filingDate": "2026-07-30", "acceptanceDateTime": "2026-07-30T20:30:28.000Z"},
    {"form": "8-K", "accessionNumber": "0001140361-26-015711", "reportDate": "2026-04-17",
     "filingDate": "2026-04-20", "acceptanceDateTime": "2026-04-20T21:29:51.000Z"},
    {"form": "10-K", "accessionNumber": "0000320193-25-000079", "reportDate": "2025-09-27",
     "filingDate": "2025-10-31", "acceptanceDateTime": "2025-10-31T10:01:26.000Z"},
    {"form": "8-K", "accessionNumber": "0000320193-25-000077", "reportDate": "2025-10-30",
     "filingDate": "2025-10-30", "acceptanceDateTime": "2025-10-30T20:30:35.000Z"},
    {"form": "8-K", "accessionNumber": "0001140361-25-025275", "reportDate": "2025-07-08",
     "filingDate": "2025-07-09", "acceptanceDateTime": "2025-07-09T01:18:13.000Z"},
    {"form": "10-Q", "accessionNumber": "0000320193-24-000081", "reportDate": "2024-06-29",
     "filingDate": "2024-08-02", "acceptanceDateTime": "2024-08-01T22:03:34.000Z"},
    {"form": "8-K", "accessionNumber": "0000320193-24-000080", "reportDate": "2024-08-01",
     "filingDate": "2024-08-01", "acceptanceDateTime": "2024-08-01T20:30:26.000Z"},
    {"form": "10-K", "accessionNumber": "0000320193-24-000123", "reportDate": "2024-09-28",
     "filingDate": "2024-11-01", "acceptanceDateTime": "2024-11-01T10:01:36.000Z"},
    {"form": "8-K", "accessionNumber": "0001140361-24-040659", "reportDate": "2024-09-10",
     "filingDate": "2024-09-10", "acceptanceDateTime": "2024-09-10T13:06:34.000Z"},
)

#: one EDGAR full-text hit, copied verbatim from efts.sec.gov on 2026-09-10 for the query
#: q="supply chain finance"&forms=10-K. Note `file_type`.
FTS_HIT = {
    "_id": "0001739566-24-000054:a20231110utzinsidertrading.htm",
    "adsh": "0001739566-24-000054", "ciks": ["0001739566"],
    "display_names": ["Utz Brands, Inc.  (UTZ)  (CIK 0001739566)"],
    "form": "10-K", "root_forms": ["10-K"], "file_type": "EX-19",
    "file_date": "2024-02-29", "period_ending": "2023-12-31",
}


if __name__ == "__main__":
    pd.set_option("display.width", 130)

    print("=== what each free source can search ===")
    print(source_table().to_string(index=False))

    print("\n=== and what it cannot ===")
    for s in SOURCES:
        print(f"  {s.name}   as-of: {s.as_of}")
        for c in s.cannot:
            print(f"    ! {c}")

    print("\n=== routing a need to a source ===")
    for need, _ in ROUTES:
        found = where_to_search(need)
        print(f"  {need:<38} -> {', '.join(found) if found else 'NOTHING FREE CAN DO THIS'}")
    print("  The empty rows are the honest ones: no free search returns a delisted name,")
    print("  a futures contract code, or the ticker an identifier carried in the past.")

    print("\n=== a full-text hit is a DOCUMENT, not a filing ===")
    print(f"  query   : \"supply chain finance\", forms=10-K")
    print(f"  form    : {FTS_HIT['form']}   root_forms: {FTS_HIT['root_forms']}")
    print(f"  file_type: {FTS_HIT['file_type']}  <- an exhibit, not the 10-K body")
    print(f"  _id     : {FTS_HIT['_id']}")
    print(f"  dates   : file_date={FTS_HIT['file_date']} "
          f"period_ending={FTS_HIT['period_ending']}  acceptanceDateTime=ABSENT")
    print("  Filtering on `form` alone counts exhibits as 10-K text, and the hit carries")
    print("  no acceptance stamp, so it cannot be used point-in-time as returned.")

    print("\n=== the three dates, on Apple's own filings ===")
    d = document_dates(AAPL_FILINGS)
    print(d[["accession", "form", "period_end", "filed_at", "acceptance_local",
             "post_close", "available_at"]].to_string(index=False))

    s = lookahead_summary(d)
    print(f"\n  {s['post_close']}/{s['n']} accepted at or after 16:00 ET "
          f"({s['post_close_pct']:.0f}%); {s['same_day_post_close']} of those still carry "
          f"that same day as filingDate.")
    print(f"  {s['filed_disagrees_with_acceptance']} filing dates disagree with the "
          f"acceptance date outright - in BOTH directions.")
    print(f"  period_end -> filed_at lag over the {s['n_periodic']} periodic reports: "
          f"median {s['median_period_lag_days']:.0f} days, max {s['max_period_lag_days']}. "
          f"That gap is what stamping a number on period_end buys you for free.")

    row = d[d["accession"] == "0000320193-24-000081"].iloc[0]
    print(f"\n  10-Q {row['accession']}: accepted {row['acceptance_local']} ET, "
          f"filingDate {row['filed_at'].date()} - the SEC's cutoff pushed the stamp to the "
          f"NEXT day.")
    row = d[d["accession"] == "0000320193-25-000077"].iloc[0]
    print(f"  8-K  {row['accession']}: accepted {row['acceptance_local']} ET, "
          f"filingDate {row['filed_at'].date()} - same day, 30 minutes after the close, "
          f"tradeable {row['available_at'].date()}.")
    print("  One field, two opposite errors. Only available_at is safe to join on.")
