#!/usr/bin/env python3
"""Generate the importable `fin_skills` package from the skills.

The skills are the source of truth and stay self-contained under plugins/. This script
copies each skill script to an importable module and each SKILL.md (plus references/) to
package data, so the same knowledge can be reached two ways:

    from fin_skills.core.safe_asof import safe_asof      # the executable guards
    fin_skills.load("backtest-validation")               # the SKILL.md text

Layout produced:

    fin_skills/<namespace>/<script>.py     one module per skill script (namespace = plugin
                                           name with the fin- prefix dropped, - -> _)
    fin_skills/<namespace>/__init__.py     lists the modules and which skill owns each
    fin_skills/_skills/<skill>/SKILL.md    the skill text, plus references/*.md
    fin_skills/_skills/index.json          a copy of catalog/index.json

Run:  python scripts/build_package.py           regenerate in place
      python scripts/build_package.py --check   exit 1 if fin_skills/ is out of date

The generated tree is committed, so `pip install git+<repo>` works with no build step.
validate.py and CI run --check, the same way they check catalog/index.json.
"""
from __future__ import annotations

import filecmp
import shutil
import sys
import tempfile
from pathlib import Path

# Tooling output carries markers and dashes; on a stock Windows console (cp1252) a bare
# print of them raises UnicodeEncodeError. Skill scripts stay ASCII; tooling may not.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent
PKG = ROOT / "fin_skills"
HAND_WRITTEN = {"__init__.py"}          # kept as-is; everything else under fin_skills/ is generated
# Hand-written packages that sit ON TOP of the generated modules and survive regeneration:
#   api/    the unified Guard interface and the Bundle
#   tools/  the same guards as JSON-callable tools (schemas, payloads, runner, export)
#   mcp/    the Model Context Protocol server over tools/
HAND_WRITTEN_DIRS = ("api/", "tools/", "mcp/")


def is_hand_written(rel: str) -> bool:
    return rel in HAND_WRITTEN or rel.startswith(HAND_WRITTEN_DIRS)

HEADER = (
    "# GENERATED by scripts/build_package.py from {src} - do not edit here.\n"
    "# Edit the skill script and rerun the generator; validate.py checks they match.\n"
    "# Owning skill: {skill} (fin_skills.load({skill!r}) returns its SKILL.md).\n\n"
)


def namespace(plugin: str) -> str:
    n = plugin[4:] if plugin.startswith("fin-") else plugin
    return n.replace("-", "_")


def generate(out: Path) -> dict[str, list[tuple[str, str]]]:
    """Write the package tree into `out`. Returns {namespace: [(module, skill), ...]}."""
    out.mkdir(parents=True, exist_ok=True)
    if (PKG / "__init__.py").exists() and out.resolve() != PKG.resolve():
        shutil.copy2(PKG / "__init__.py", out / "__init__.py")

    by_ns: dict[str, list[tuple[str, str]]] = {}
    for script in sorted(ROOT.glob("plugins/*/skills/*/scripts/*.py")):
        plugin, skill, mod = script.parts[-5], script.parts[-3], script.stem
        if not mod.isidentifier() or mod.startswith("_"):
            raise SystemExit(f"{script}: {mod!r} is not a valid module name")
        ns = namespace(plugin)
        entries = by_ns.setdefault(ns, [])
        if any(m == mod for m, _ in entries):
            raise SystemExit(f"duplicate module {ns}.{mod} - two skills in {plugin} ship a script "
                             f"with the same name")
        entries.append((mod, skill))
        dst = out / ns / f"{mod}.py"
        dst.parent.mkdir(parents=True, exist_ok=True)
        src_rel = script.relative_to(ROOT).as_posix()
        dst.write_text(HEADER.format(src=src_rel, skill=skill) + script.read_text(encoding="utf-8"),
                       encoding="utf-8", newline="\n")

    for ns, entries in sorted(by_ns.items()):
        lines = [f'"""fin_skills.{ns} - generated from the {ns.replace("_", "-")} plugin\'s skill scripts.\n',
                 "Module -> owning skill:", ""]
        lines += [f"    {m:<28} {s}" for m, s in sorted(entries)]
        lines += ['"""', "", "__all__ = [", *[f"    {m!r}," for m, _ in sorted(entries)], "]", ""]
        (out / ns / "__init__.py").write_text("\n".join(lines), encoding="utf-8", newline="\n")

    data = out / "_skills"
    for md in sorted(ROOT.glob("plugins/*/skills/*/SKILL.md")):
        skill = md.parent.name
        d = data / skill
        d.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(md, d / "SKILL.md")
        refs = md.parent / "references"
        if refs.is_dir():
            (d / "references").mkdir(exist_ok=True)
            for r in sorted(refs.glob("*.md")):
                shutil.copyfile(r, d / "references" / r.name)
    idx = ROOT / "catalog" / "index.json"
    if idx.exists():
        shutil.copyfile(idx, data / "index.json")
    return by_ns


def tree(root: Path) -> set[str]:
    return {p.relative_to(root).as_posix() for p in root.rglob("*")
            if p.is_file() and "__pycache__" not in p.parts}


def check() -> int:
    if not PKG.exists():
        print("fin_skills/ does not exist - run scripts/build_package.py")
        return 1
    with tempfile.TemporaryDirectory() as td:
        fresh = Path(td) / "fin_skills"
        generate(fresh)
        have, want = tree(PKG), tree(fresh)
        problems = []
        for rel in sorted(want - have):
            problems.append(f"missing   {rel}")
        for rel in sorted(have - want):
            if not is_hand_written(rel):
                problems.append(f"stale     {rel} (no longer generated)")
        for rel in sorted(have & want):
            if not filecmp.cmp(PKG / rel, fresh / rel, shallow=False):
                problems.append(f"differs   {rel}")
        if problems:
            print(f"fin_skills/ is out of date ({len(problems)} file(s)) - run scripts/build_package.py:")
            for p in problems[:40]:
                print("  " + p)
            return 1
    print("fin_skills/ is in sync with the skills")
    return 0


def main() -> int:
    if "--check" in sys.argv:
        return check()
    # regenerate in place: remove everything generated, keep the hand-written files
    if PKG.exists():
        for p in sorted(PKG.rglob("*"), reverse=True):
            if p.is_file() and not is_hand_written(p.relative_to(PKG).as_posix()):
                p.unlink()
            elif p.is_dir() and not any(p.iterdir()):
                p.rmdir()
    by_ns = generate(PKG)
    n_mod = sum(len(v) for v in by_ns.values())
    n_sk = len(list((PKG / "_skills").glob("*/SKILL.md")))
    print(f"fin_skills/ written - {n_mod} modules in {len(by_ns)} namespaces "
          f"({', '.join(sorted(by_ns))}); {n_sk} skills as package data")
    return 0


if __name__ == "__main__":
    sys.exit(main())
