"""Export the method inventory for readers without a Python environment.

Run after editing algorithms/_knowledge_data.py or the model registry. Availability
is deliberately not frozen: optional dependencies differ across installations.
"""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from fin_skills.algorithms.knowledge import _cards, method_coverage, validate_inventory


def export(directory, check=False):
    validate_inventory()
    cards = sorted(_cards(), key=lambda c: (c["kind"], c["family"], c["id"]))
    for card in cards:
        if card["status"] == "integrated":
            card["availability"] = "check_model_catalog_at_runtime"
    coverage = method_coverage()
    coverage.pop("availability")
    data = dict(schema_version=1, coverage=coverage, methods=cards)
    lines = ["# Quantitative strategies, decisions and algorithms", "",
             "Generated by `python scripts/export_quant_methods.py`; edit the source catalog.", "",
             coverage["scope"], "", f"Entries: **{coverage['total']}**. "
             f"Curated source review: **{coverage['curated_verified_on']}**.", "",
             "- `integrated`: registered adapter; check dependencies with `list_models`.",
             "- `external`: upstream implementation documented, no local adapter for this card.",
             "- `reference`: a research or method description, no local implementation claim.", "",
             "See [usage and contribution rules](../docs/QUANT_METHODS.md). "
             "[Machine-readable catalog](quant_methods.json) includes required data and cautions.", ""]
    for kind in ("strategy", "decision", "algorithm"):
        lines += [f"## {kind}", "", "| ID | Method / 中文 | Family | Status | Source |",
                  "|---|---|---|---|---|"]
        for card in cards:
            if card["kind"] != kind:
                continue
            source = card["sources"][0]
            url = source.get("url", source.get("location", ""))
            ref = f"[source]({url})" if url.startswith("https://") else "local adapter metadata"
            lines.append(f"| `{card['id']}` | {card['name']} {card['name_zh']} | "
                         f"{card['family']} | {card['status']} | {ref} |")
        lines += [""]
    lines += ["## Known gaps", ""] + ["- " + gap for gap in coverage["gaps"]] + [""]
    outputs = {"quant_methods.json": json.dumps(data, ensure_ascii=False, indent=2) + "\n",
               "QUANT_METHODS.md": "\n".join(lines)}
    directory = Path(directory)
    if not check:
        directory.mkdir(parents=True, exist_ok=True)
    for name, content in outputs.items():
        path = directory / name
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise ValueError(f"stale export: {path}; run scripts/export_quant_methods.py")
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
    return coverage


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=ROOT / "catalog")
    args = parser.parse_args()
    print(json.dumps(export(args.output, args.check), ensure_ascii=True))
