# GENERATED by scripts/build_package.py from plugins/fin-alt-data/skills/insider-form-4/scripts/form4.py - do not edit here.
# Edit the skill script and rerun the generator; validate.py checks they match.
# Owning skill: insider-form-4 (fin_skills.load('insider-form-4') returns its SKILL.md).

#!/usr/bin/env python3
"""Form 4: a two-business-day lag, a 22:00 ET filing window, and 20 transaction codes.

No network, no file writes, no scraper, no credential path. Every filing here is SYNTHETIC
and seeded. The only real content is the SEC's own text - the deadline, the filing-hours
rule and the transaction-code list - transcribed below and read at its primary source on
2026-09-10. The code MIX and the lag distribution are chosen by this file and then MEASURED
back off the panel; they are not a tally of EDGAR.

Five parts:

  1. The rule as constants: the deadline, the deferred-notification branch and its outer
     cap, the 22:00 ET window for ownership forms, and the 20 transaction codes with the
     SEC's own one-line descriptions.
  2. A seeded panel. Business days from execution to acceptance, plus an acceptance HOUR,
     because the 22:00 ET window means a large share of Forms 4 are accepted after the
     market has closed.
  3. The A/B on open-market purchases only: transaction-date key vs disclosure-date key.
     With a two-day deadline the decay costs almost nothing - so the gap that remains is
     the ANNOUNCEMENT reaction on the first session the market can trade the filing, and
     that is the part you structurally cannot have.
  4. The post-close rule. A filing accepted at 20:30 ET carries THAT day's filing date but
     the earliest tradeable bar is the next session. Filling at the filing day's close is
     the 90-minute leak in a form that makes it a six-hour one.
  5. The code filter. Every Form 4 is a signal, or only code P is. This is the whole game.

Run:  python form4.py    (numpy + pandas, seed 20260910)
"""
from __future__ import annotations

import time

import numpy as np
import pandas as pd

SEED = 20260910
TRADING_DAYS_PER_YEAR = 252

# --------------------------------------------------------------------------------------
# 1. The rule, transcribed (read 2026-09-10)
# --------------------------------------------------------------------------------------

# Exchange Act sec. 16(a)(2)(C), 15 U.S.C. 78p(a)(2)(C), and 17 CFR 240.16a-3(g)(1):
# a Form 4 "must be filed before the end of the second business day following the day on
# which the subject transaction has been executed".
FORM4_DEADLINE_BUSINESS_DAYS = 2

# 17 CFR 240.16a-3(g)(2) and (g)(3): for a Rule 10b5-1(c) plan trade where "the reporting
# person does not select the date of execution", and for a discretionary transaction under
# 16b-3(b)(1), the deemed execution date is the date the broker or plan administrator
# "notifies the reporting person".
# 17 CFR 240.16a-3(g)(4) is the cap everyone omits: if notification is later than the THIRD
# business day after the trade date, the execution date is deemed to be that third business
# day. So the outer limit on a deferred filing is T+3 deemed + 2 = T+5 business days.
DEFERRED_NOTIFICATION_CAP_BUSINESS_DAYS = 3
DEFERRED_OUTER_LIMIT_BUSINESS_DAYS = (DEFERRED_NOTIFICATION_CAP_BUSINESS_DAYS
                                      + FORM4_DEADLINE_BUSINESS_DAYS)

# 17 CFR 232.13 (Regulation S-T Rule 13). (a)(2): a filing commencing after 5:30 p.m.
# Eastern "shall be deemed filed as of the next business day". (a)(4): a Form 3, 4 or 5 -
# and also Schedule 14N, Form 144 and Schedules 13D/13G - commencing "on or before 10 p.m.
# Eastern" is "deemed filed on the same business day". sec.gov/os/accessing-edgar-data
# restates it as "or 10:00 p.m. for Ownership forms 3, 4, 5".
EDGAR_CUTOFF_HOUR_ET = 17.5           # 5:30 p.m. - periodic reports
OWNERSHIP_CUTOFF_HOUR_ET = 22.0       # 10:00 p.m. - Forms 3, 4, 5
MARKET_CLOSE_HOUR_ET = 16.0

# sec.gov/os/accessing-edgar-data, read 2026-09-10: "Current max request rate: 10
# requests/second", and "Please declare your user agent in request headers". The header is
# the same one fundamental-and-macro-data already documents; this file makes no request.
EDGAR_MAX_REQUESTS_PER_SECOND = 10

# 17 CFR 240.16a-3(g)(1) as amended in 2022 also pulls "dispositions by bona fide gifts"
# onto Form 4. Before that they went on the Form 5, up to 45 days after fiscal year end.
GIFTS_ON_FORM_4_SINCE = 2023

# Form 4 General Instruction 8 and sec.gov/edgar/searchedgar/ownershipformcodes.html, read
# 2026-09-10. TWENTY codes in five headed groups, with the SEC's own descriptions.
# `acq` is the direction as the signal would read it; None means it depends on the leg.
TRANSACTION_CODES: dict[str, tuple[str, str, str | None]] = {
    # General Transaction Codes
    "P": ("general", "Open market or private purchase of non-derivative or derivative "
                     "security", "A"),
    "S": ("general", "Open market or private sale of non-derivative or derivative "
                     "security", "D"),
    "V": ("general", "Transaction voluntarily reported earlier than required", None),
    # Rule 16b-3 Transaction Codes (Rule 16b-3 is the exemptive rule)
    "A": ("16b-3", "Grant, award or other acquisition pursuant to Rule 16b-3(d)", "A"),
    "D": ("16b-3", "Disposition to the issuer of issuer equity securities pursuant to "
                   "Rule 16b-3(e)", "D"),
    "F": ("16b-3", "Payment of exercise price or tax liability by delivering or "
                   "withholding securities incident to the receipt, exercise or vesting "
                   "of a security issued in accordance with Rule 16b-3", "D"),
    "I": ("16b-3", "Discretionary transaction in accordance with Rule 16b-3(f) resulting "
                   "in acquisition or disposition of issuer securities", None),
    "M": ("16b-3", "Exercise or conversion of derivative security exempted pursuant to "
                   "Rule 16b-3", "A"),
    # Derivative Securities Codes (Except for transactions exempted pursuant to Rule 16b-3)
    "C": ("derivative", "Conversion of derivative security", "A"),
    "E": ("derivative", "Expiration of short derivative position", None),
    "H": ("derivative", "Expiration (or cancellation) of long derivative position with "
                        "value received", None),
    "O": ("derivative", "Exercise of out-of-the-money derivative security", "A"),
    "X": ("derivative", "Exercise of in-the-money or at-the-money derivative security", "A"),
    # Other Section 16(b) Exempt Transaction and Small Acquisition Codes
    "G": ("exempt", "Bona fide gift", None),
    "L": ("exempt", "Small acquisition under Rule 16a-6", "A"),
    "W": ("exempt", "Acquisition or disposition by will or the laws of descent and "
                    "distribution", None),
    "Z": ("exempt", "Deposit into or withdrawal from voting trust", None),
    # Other Transaction Codes
    "J": ("other", "Other acquisition or disposition (describe transaction)", None),
    "K": ("other", "Transaction in equity swap or instrument with similar characteristics",
          None),
    "U": ("other", "Disposition pursuant to a tender of shares in a change of control "
                   "transaction", "D"),
}

# The heading that carries the word "exempt" covers G, L, W and Z only; A, D, F, I and M
# sit under "Rule 16b-3 Transaction Codes", which is the exemptive rule; C, E, H, O and X
# are headed "Except for transactions exempted pursuant to Rule 16b-3".
EXEMPT_HEADED_CODES = ("G", "L", "W", "Z")
RULE_16B3_CODES = ("A", "D", "F", "I", "M")

# The mix this file SIMULATES. Set here, not observed on EDGAR, and chosen so the panel has
# the shape the code-filter measurement is about: open-market purchases are the minority.
CODE_MIX: dict[str, float] = {
    "A": 0.22, "S": 0.24, "F": 0.16, "M": 0.16, "P": 0.12,
    "G": 0.04, "D": 0.03, "X": 0.02, "C": 0.01,
}

ACQUISITION_CODES = tuple(c for c in CODE_MIX if TRANSACTION_CODES[c][2] == "A")
DISPOSITION_CODES = tuple(c for c in CODE_MIX if TRANSACTION_CODES[c][2] == "D")

# Codes whose timing is scheduled by the issuer rather than chosen by the insider: annual
# grants and the exercises and tax withholdings that hang off them. They cluster.
SCHEDULED_CODES = ("A", "M", "F")


def code_table() -> pd.DataFrame:
    """The SEC's 20 codes, their group and how a naive signal would read the direction."""
    rows = []
    for c, (grp, desc, acq) in TRANSACTION_CODES.items():
        rows.append({"code": c, "group": grp, "direction": acq or "-",
                     "simulated_share": CODE_MIX.get(c, 0.0),
                     "description": desc})
    return pd.DataFrame(rows).set_index("code")


# --------------------------------------------------------------------------------------
# 2. The seeded panel
# --------------------------------------------------------------------------------------

# Business days from execution to acceptance. SET here. The on-time branch has to land at
# or inside 2; the deferred branch is the 16a-3(g)(2)/(3) route, capped at 5 by (g)(4);
# a small share is simply late, which happens and is a reporting violation.
ON_TIME_LAG_PMF = {0: 0.08, 1: 0.27, 2: 0.61, 3: 0.03, 4: 0.01}
DEFERRED_SHARE = 0.18
LATE_SHARE = 0.03

# Acceptance hour. The 22:00 ET window is not decoration: a large share of Forms 4 land
# after the close. This split is SET, then measured back.
POST_CLOSE_SHARE = 0.62


def draw_lag_and_hour(n: int, rng: np.random.Generator, lag_scale: float = 1.0
                      ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """(business-day lag, acceptance hour ET, deferred flag) for n filings."""
    codes = np.array(list(ON_TIME_LAG_PMF))
    probs = np.array([ON_TIME_LAG_PMF[c] for c in codes], dtype=float)
    lag = rng.choice(codes, size=n, p=probs / probs.sum()).astype(float)

    deferred = rng.random(n) < DEFERRED_SHARE
    lag = np.where(deferred,
                   rng.choice([3, 4, 5], size=n, p=[0.30, 0.35, 0.35]).astype(float),
                   lag)
    late = rng.random(n) < LATE_SHARE
    lag = np.where(late, 6.0 + rng.gamma(1.5, 6.0, n), lag)
    lag = np.maximum(0.0, np.round(lag * float(lag_scale)))

    # Hours: a pre-close cluster in the morning/early afternoon and a post-close cluster
    # that runs to the 22:00 ownership-form cutoff.
    pre = rng.uniform(9.5, MARKET_CLOSE_HOUR_ET, n)
    post = MARKET_CLOSE_HOUR_ET + rng.beta(1.6, 1.5, n) * (OWNERSHIP_CUTOFF_HOUR_ET
                                                           - MARKET_CLOSE_HOUR_ET)
    hour = np.where(rng.random(n) < POST_CLOSE_SHARE, post, pre)
    return lag.astype(int), hour, deferred


def lag_summary(lag_bd: np.ndarray, hour: np.ndarray) -> dict:
    q = np.percentile(lag_bd, [50, 90, 95, 99])
    return {
        "n": int(len(lag_bd)),
        "mean": float(lag_bd.mean()), "median": float(q[0]),
        "p90": float(q[1]), "p95": float(q[2]), "p99": float(q[3]),
        "max": float(lag_bd.max()),
        "share_within_2": float((lag_bd <= FORM4_DEADLINE_BUSINESS_DAYS).mean()),
        "share_within_5": float((lag_bd <= DEFERRED_OUTER_LIMIT_BUSINESS_DAYS).mean()),
        "share_over_5": float((lag_bd > DEFERRED_OUTER_LIMIT_BUSINESS_DAYS).mean()),
        "share_post_close": float((hour >= MARKET_CLOSE_HOUR_ET).mean()),
        "share_after_1730": float((hour >= EDGAR_CUTOFF_HOUR_ET).mean()),
        "max_hour": float(hour.max()),
    }


def make_returns(n_days: int, n_names: int, rng: np.random.Generator) -> np.ndarray:
    mkt = rng.normal(0.0002, 0.0100, n_days)
    beta = rng.uniform(0.7, 1.3, n_names)
    idio = rng.normal(0.0, 0.0180, (n_days, n_names))
    return mkt[:, None] * beta[None, :] + idio


def decay_weights(hold: int, half_life: float) -> np.ndarray:
    w = np.exp(-np.arange(1, hold + 1) / float(half_life) * np.log(2.0))
    return w / w.sum()


def make_panel(n_events: int = 6_000, n_days: int = 2_520, n_names: int = 200,
               seed: int = SEED, hold: int = 63, half_life: float = 21.0,
               base_alpha: float = 0.030, announce_share: float = 0.40,
               lag_scale: float = 1.0, cluster_scheduled: bool = True
               ) -> tuple[pd.DataFrame, np.ndarray]:
    """A seeded Form 4 panel plus the return matrix its information already lives in.

    ONLY code P carries information here. That is the modelling choice the whole file is
    about, and it is the closest this repo will come to the insider literature's finding
    that purchases predict and sales do not - see the SKILL.md, which cites it as
    secondhand because no SEC source says any such thing.

    `announce_share` of each purchase's total alpha lands as a single-day jump on the first
    session the market can trade the filing; the rest drifts from the execution date.
    """
    rng = np.random.default_rng(seed)
    rets = make_returns(n_days, n_names, rng)

    codes = np.array(list(CODE_MIX))
    p = np.array([CODE_MIX[c] for c in codes], dtype=float)
    code = rng.choice(codes, size=n_events, p=p / p.sum())

    lag_bd, hour, deferred = draw_lag_and_hour(n_events, rng, lag_scale)
    name = rng.integers(0, n_names, n_events)

    # Grants, exercises and tax withholdings are scheduled by the issuer, so they cluster
    # on an anniversary rather than spreading out. That concentration is part of why a
    # naive "every Form 4" signal is worse than 1/N dilution alone would predict.
    lo, hi = 3, n_days - hold - 12
    txn_day = rng.integers(lo, hi, n_events)
    if cluster_scheduled:
        anniversary = rng.integers(0, 252, n_names)
        sched = np.isin(code, SCHEDULED_CODES)
        year = rng.integers(0, n_days // 252, n_events)
        clustered = (anniversary[name] + 252 * year
                     + rng.integers(-8, 9, n_events))
        txn_day = np.where(sched, np.clip(clustered, lo, hi - 1), txn_day)

    file_day = np.minimum(txn_day + lag_bd, n_days - 2)
    # The first session the market can react: same day if accepted before the close,
    # otherwise the next one.
    react_day = np.minimum(file_day + (hour >= MARKET_CLOSE_HOUR_ET).astype(int),
                           n_days - 2)

    informed = code == "P"
    alpha = np.where(informed, base_alpha, 0.0)

    w = decay_weights(hold, half_life)
    idx = np.flatnonzero(informed)
    for i in idx:
        t = txn_day[i] + 1
        rets[t:t + hold, name[i]] += alpha[i] * (1.0 - announce_share) * w
        rets[react_day[i], name[i]] += alpha[i] * announce_share

    filings = pd.DataFrame({
        "name": name, "code": code, "txn_day": txn_day, "lag_bd": lag_bd,
        "hour": hour, "deferred": deferred, "file_day": file_day,
        "react_day": react_day, "alpha": alpha, "informed": informed,
    })
    return filings, rets


# --------------------------------------------------------------------------------------
# 3-5. Portfolios
# --------------------------------------------------------------------------------------

def portfolio(filings: pd.DataFrame, rets: np.ndarray, key: str, hold: int = 63,
              side: np.ndarray | None = None) -> np.ndarray:
    """Daily market-neutral return. Entry at the CLOSE of the key day, so the first return
    earned is the next day's. `side` is +1/-1 per filing; default long-only."""
    n_days, n_names = rets.shape
    W = np.zeros((n_days, n_names))
    entry = filings[key].to_numpy()
    name = filings["name"].to_numpy()
    s = np.ones(len(filings)) if side is None else np.asarray(side, dtype=float)
    for i in range(len(filings)):
        a = entry[i] + 1
        b = min(a + hold, n_days)
        if a < n_days and s[i] != 0.0:
            W[a:b, name[i]] += s[i]
    gross = np.abs(W).sum(axis=1)
    live = gross > 0
    Wn = np.zeros_like(W)
    Wn[live] = W[live] / gross[live, None]
    port = (Wn * rets).sum(axis=1)
    net = Wn.sum(axis=1)                     # residual net exposure to hedge out
    return np.where(live, port - net * rets.mean(axis=1), 0.0)


def sharpe(r: np.ndarray) -> float:
    r = np.asarray(r, dtype=float)
    s = r.std(ddof=1)
    return float("nan") if not np.isfinite(s) or s == 0 else float(
        r.mean() / s * np.sqrt(TRADING_DAYS_PER_YEAR))


def run_ab(seed: int = SEED, hold: int = 63, **kw) -> pd.DataFrame:
    """Open-market purchases only, keyed three ways."""
    f, rets = make_panel(seed=seed, hold=hold, **kw)
    p = f[f["code"] == "P"]
    rows = {}
    for label, key in (("transaction-date", "txn_day"),
                       ("filing-date, same close", "file_day"),
                       ("first tradeable session", "react_day")):
        r = portfolio(p, rets, key, hold)
        rows[label] = {"sharpe": sharpe(r),
                       "ann_return": float(r.mean() * TRADING_DAYS_PER_YEAR),
                       "ann_vol": float(r.std(ddof=1) * np.sqrt(TRADING_DAYS_PER_YEAR))}
    tab = pd.DataFrame(rows).T
    base = tab.loc["first tradeable session", "sharpe"]
    tab["sharpe_gap"] = tab["sharpe"] - base
    tab["retained"] = base / tab["sharpe"]
    return tab


def announce_split(seed: int = SEED, n_seeds: int = 10,
                   shares=(0.0, 0.2, 0.4, 0.6)) -> pd.DataFrame:
    """Where the gap comes from when the deadline is two days: decay or the announcement.

    At announce_share=0 all the information drifts from the execution date, so a two-day
    lag can only cost two days of decay. Raising it moves alpha onto the session the
    filing becomes public, which the honest strategy enters at the close OF - and so
    misses entirely.
    """
    rows = {}
    for a in shares:
        txn, react = [], []
        for k in range(n_seeds):
            t = run_ab(seed=seed + k, announce_share=a)
            txn.append(t.loc["transaction-date", "sharpe"])
            react.append(t.loc["first tradeable session", "sharpe"])
        rows[f"{a:.0%}"] = {"txn": float(np.mean(txn)),
                            "tradeable": float(np.mean(react)),
                            "gap": float(np.mean(txn) - np.mean(react)),
                            "retained": float(np.mean(react) / np.mean(txn))}
    return pd.DataFrame(rows).T


def post_close_cost(seed: int = SEED, n_seeds: int = 10) -> pd.DataFrame:
    """What filling at the filing day's close is worth, and to whom.

    A Form 4 accepted at 20:30 ET carries that day's filing date. Filling at that day's
    close is not a rounding error; it is trading on a document that did not exist when the
    bell rang.
    """
    naive, honest, shares = [], [], []
    for k in range(n_seeds):
        f, rets = make_panel(seed=seed + k)
        p = f[f["code"] == "P"]
        naive.append(sharpe(portfolio(p, rets, "file_day")))
        honest.append(sharpe(portfolio(p, rets, "react_day")))
        shares.append(float((p["hour"] >= MARKET_CLOSE_HOUR_ET).mean()))
    return pd.DataFrame({
        "sharpe": {"filing day's close": float(np.mean(naive)),
                   "first tradeable session": float(np.mean(honest))},
        "sd": {"filing day's close": float(np.std(naive, ddof=1)),
               "first tradeable session": float(np.std(honest, ddof=1))},
        "post_close_share": {"filing day's close": float(np.mean(shares)),
                             "first tradeable session": float(np.mean(shares))},
    })


SIGNALS = ("every Form 4 acquisition", "net insider buying", "purchases and sales (P, S)",
           "open-market purchases (P)")


def signal_sides(f: pd.DataFrame, which: str) -> np.ndarray:
    code = f["code"].to_numpy()
    if which == "every Form 4 acquisition":
        return np.isin(code, ACQUISITION_CODES).astype(float)
    if which == "net insider buying":
        return (np.isin(code, ACQUISITION_CODES).astype(float)
                - np.isin(code, DISPOSITION_CODES).astype(float))
    if which == "purchases and sales (P, S)":
        return (code == "P").astype(float) - (code == "S").astype(float)
    if which == "open-market purchases (P)":
        return (code == "P").astype(float)
    raise ValueError(f"unknown signal {which!r}")


def code_filter_table(seed: int = SEED, n_seeds: int = 10, hold: int = 63) -> pd.DataFrame:
    """The whole game: which Forms 4 you let into the portfolio, honestly keyed."""
    acc = {s: [] for s in SIGNALS}
    n_used = {s: [] for s in SIGNALS}
    for k in range(n_seeds):
        f, rets = make_panel(seed=seed + k, hold=hold)
        for s in SIGNALS:
            side = signal_sides(f, s)
            acc[s].append(sharpe(portfolio(f, rets, "react_day", hold, side=side)))
            n_used[s].append(float((side != 0).mean()))
    tab = pd.DataFrame({
        "sharpe": {s: float(np.mean(acc[s])) for s in SIGNALS},
        "sd": {s: float(np.std(acc[s], ddof=1)) for s in SIGNALS},
        "share_of_filings_used": {s: float(np.mean(n_used[s])) for s in SIGNALS},
    })
    tab["informed_share_of_used"] = np.nan
    f, _ = make_panel(seed=seed)
    for s in SIGNALS:
        side = signal_sides(f, s)
        used = side != 0
        tab.loc[s, "informed_share_of_used"] = float(f.loc[used, "informed"].mean())
    return tab


# --------------------------------------------------------------------------------------

def main() -> None:
    t0 = time.time()
    print("=" * 78)
    print("1. The rule, transcribed (read 2026-09-10 - see the module docstring)")
    print("=" * 78)
    print(f"   Form 4 due: before the end of the {FORM4_DEADLINE_BUSINESS_DAYS}nd business day")
    print("               following the day the transaction was executed")
    print("               [15 U.S.C. 78p(a)(2)(C); 17 CFR 240.16a-3(g)(1)]")
    print("   deferred:   for a Rule 10b5-1(c) plan trade the reporting person did not time,")
    print("               and for a 16b-3(f) discretionary transaction, the DEEMED execution")
    print("               date is the notification date [16a-3(g)(2),(3)] - but 16a-3(g)(4)")
    print(f"               caps that at T+{DEFERRED_NOTIFICATION_CAP_BUSINESS_DAYS}, so the "
          f"outer limit is T+{DEFERRED_OUTER_LIMIT_BUSINESS_DAYS} business days.")
    print("   window:     after 17:30 ET a periodic report is deemed filed the NEXT")
    print(f"               business day, but Forms 3/4/5 filed on or before "
          f"{OWNERSHIP_CUTOFF_HOUR_ET:.0f}:00 ET keep")
    print("               the same day [17 CFR 232.13(a)(2) and (a)(4)]")
    print(f"   access:     max {EDGAR_MAX_REQUESTS_PER_SECOND} requests/second and declare a "
          f"User-Agent; no request is made here")
    print(f"   since {GIFTS_ON_FORM_4_SINCE}:  bona fide gift DISPOSITIONS moved onto Form 4;")
    print("               before that they sat on the Form 5, up to 45 days after year end.")
    ct = code_table()
    print(f"\n   The {len(ct)} transaction codes, SEC's own groupings:")
    print(f"   {'code':<6}{'group':<12}{'dir':<5}{'sim %':>7}  description")
    for c, r in ct.iterrows():
        d = r["description"]
        d = d if len(d) <= 46 else d[:43] + "..."
        share = f"{r['simulated_share']:.0%}" if r["simulated_share"] else "-"
        print(f"   {c:<6}{r['group']:<12}{r['direction']:<5}{share:>7}  {d}")
    print(f"   codes under the heading that says 'Exempt': {', '.join(EXEMPT_HEADED_CODES)}")
    print(f"   codes under 'Rule 16b-3 Transaction Codes': {', '.join(RULE_16B3_CODES)}")
    amb = [c for c, (_, _, a) in TRANSACTION_CODES.items() if a is None]
    print(f"   codes whose OWN description does not fix a direction: {', '.join(amb)}")
    print("   - the direction is a separate acquired/disposed flag on the transaction line,")
    print("     not something the code gives you. 'dir' above is only how a signal keyed on")
    print("     the code alone would have to read it.")
    print("   'sim %' is the mix THIS FILE simulates. It is not a tally of EDGAR.")

    print("\n" + "=" * 78)
    print("2. The seeded panel and its MEASURED lag and hour distributions")
    print("=" * 78)
    f, rets = make_panel()
    s = lag_summary(f["lag_bd"].to_numpy(), f["hour"].to_numpy())
    print(f"   {s['n']:,} synthetic filings, 2,520 trading days, 200 names, seed {SEED}")
    print(f"   business days from execution to acceptance:")
    print(f"   {'mean':>8}{'median':>9}{'p90':>7}{'p95':>7}{'p99':>7}{'max':>8}")
    print(f"   {s['mean']:>8.2f}{s['median']:>9.0f}{s['p90']:>7.0f}{s['p95']:>7.0f}"
          f"{s['p99']:>7.0f}{s['max']:>8.0f}")
    print(f"   inside the 2-business-day deadline: {s['share_within_2']:.1%}")
    print(f"   inside the deferred outer limit of T+{DEFERRED_OUTER_LIMIT_BUSINESS_DAYS}: "
          f"{s['share_within_5']:.1%}    past it: {s['share_over_5']:.1%}")
    print(f"   accepted at or after the 16:00 close: {s['share_post_close']:.1%}"
          f"   after 17:30: {s['share_after_1730']:.1%}   latest {s['max_hour']:.1f} ET")
    print("   Both distributions are SET by draw_lag_and_hour(), then measured back. The")
    print("   two facts that are NOT choices: the deadline is two business days, not 45,")
    print("   and the ownership-form window runs six hours past the closing bell.")

    print("\n" + "=" * 78)
    print("3. The A/B - open-market purchases only, keyed three ways")
    print("=" * 78)
    tab = run_ab()
    print(f"   {'key':<28}{'sharpe':>9}{'ann ret':>10}{'ann vol':>10}{'gap':>8}")
    for k in tab.index:
        r = tab.loc[k]
        print(f"   {k:<28}{r['sharpe']:>9.3f}{r['ann_return']:>10.2%}"
              f"{r['ann_vol']:>10.2%}{r['sharpe_gap']:>8.3f}")
    print("   transaction-date       = the day the insider traded          (LOOK-AHEAD)")
    print("   filing-date same close = filled at the close of the filing day, whatever")
    print("                            hour it was accepted                (LOOK-AHEAD)")
    print("   first tradeable session = the honest one")

    print("\n" + "=" * 78)
    print("4. Where the gap comes from when the deadline is two days")
    print("=" * 78)
    sp = announce_split()
    print("   Share of each purchase's alpha delivered as a jump on the first session the")
    print("   market can trade the filing, rather than as drift from the execution date.")
    print("   10 seeds per row.\n")
    print(f"   {'announce share':<16}{'txn key':>10}{'tradeable':>12}{'gap':>9}"
          f"{'retained':>11}")
    for i in sp.index:
        r = sp.loc[i]
        print(f"   {i:<16}{r['txn']:>10.3f}{r['tradeable']:>12.3f}{r['gap']:>9.3f}"
              f"{r['retained']:>11.1%}")
    print("   At 0% the two-business-day lag costs almost nothing - two days of a 21-day")
    print("   half-life. The gap that exists in real Form 4 data is not the deadline; it")
    print("   is the reaction to the filing, and you enter at the close OF that session.")

    print("\n" + "=" * 78)
    print("5. The 22:00 ET window - filling at the filing day's close")
    print("=" * 78)
    pc = post_close_cost()
    print(f"   {'fill':<28}{'sharpe':>9}{'sd':>8}{'post-close share':>19}")
    for i in pc.index:
        r = pc.loc[i]
        print(f"   {i:<28}{r['sharpe']:>9.3f}{r['sd']:>8.3f}"
              f"{r['post_close_share']:>19.1%}")
    d = pc.loc["filing day's close", "sharpe"] - pc.loc["first tradeable session", "sharpe"]
    print(f"   difference {d:.3f} of Sharpe, bought entirely with filings accepted after")
    print("   the bell. filingDate is a DATE; acceptanceDateTime is the wall clock. Use it.")

    print("\n" + "=" * 78)
    print("6. The code filter - the whole game")
    print("=" * 78)
    cf = code_filter_table()
    print("   All four honestly keyed to the first tradeable session. 10 seeds.")
    print(f"   {'signal':<30}{'sharpe':>9}{'sd':>8}{'% filings used':>16}"
          f"{'% of those informed':>21}")
    for s in SIGNALS:
        r = cf.loc[s]
        print(f"   {s:<30}{r['sharpe']:>9.3f}{r['sd']:>8.3f}"
              f"{r['share_of_filings_used']:>16.1%}"
              f"{r['informed_share_of_used']:>21.1%}")
    best, worst = cf["sharpe"].max(), cf["sharpe"].min()
    print(f"   Spread across the four: {best - worst:.3f} of Sharpe, from the same filings,")
    print("   the same names and the same holding period. Only the code filter differs.")
    print("   Grants, exercises and tax withholdings are not decisions: they are the")
    print("   issuer's calendar, and they outnumber the decisions.")

    print(f"\n   (total runtime {time.time() - t0:.1f}s)")
    print("\nRule: filter Form 4 to open-market purchases by transaction code before you"
          " look at anything else, then key the signal to the first session that can trade"
          " the acceptance timestamp - not to the execution date and not to the filing"
          " day's close.")


if __name__ == "__main__":
    main()
